# monitoring/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: vhhealth-monitoring
resources:
  - chart-tracker.yaml
  - alert-rules.yaml
  - backend-red-alerts.yaml
  - backend-reliability-alerts.yaml
