apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sealed-secrets
  namespace: vhhealth-security
  labels:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/part-of: vhhealth
    app.kubernetes.io/managed-by: kustomize
    release: vhhealth-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sealed-secrets
      app.kubernetes.io/instance: sealed-secrets
  namespaceSelector:
    matchNames:
      - vhhealth-security
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
