-- Migration 098: investigation booking + lab status lifecycle.
--
-- The patient app's "Book Investigation" flow + the lab staff's
-- booking lifecycle (confirm → dispatch → collect → process → result)
-- have been calling controllers that reference three tables that
-- never existed:
--   * investigation_test_catalog  — list of investigations with cost,
--                                   normal range, fasting flag, TAT
--   * investigation_bookings       — patient-initiated booking + lab
--                                   workflow state
--   * investigation_booking_history — audit trail of status transitions
--
-- Until now the controllers either crashed with `42P01` or were patched
-- to return `[]` on the missing-table error. This migration creates
-- all three with the columns the existing controllers already write to.

BEGIN;

-- ─── investigation_test_catalog ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS investigation_test_catalog (
  id                         BIGSERIAL PRIMARY KEY,
  name                       VARCHAR(255) NOT NULL,
  code                       VARCHAR(50)  UNIQUE,
  category                   VARCHAR(100),
  description                TEXT,
  normal_range               TEXT,
  unit                       VARCHAR(50),
  default_cost               NUMERIC(10,2) NOT NULL DEFAULT 0,
  home_collection_surcharge  NUMERIC(10,2) NOT NULL DEFAULT 50,
  turnaround_hours           INTEGER NOT NULL DEFAULT 24,
  requires_fasting           BOOLEAN NOT NULL DEFAULT FALSE,
  patient_instructions       TEXT,
  sample_type                VARCHAR(50),
  is_active                  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at                 TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                 TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_invtestcat_active_category
  ON investigation_test_catalog(category)
  WHERE is_active = TRUE;

-- ─── investigation_bookings ────────────────────────────────────────────
-- Booking number is generated by a trigger so the controller doesn't
-- have to think about uniqueness — `INV-yyyymmdd-<seq>` is short enough
-- to read out over the phone but unambiguous enough to look up.
CREATE SEQUENCE IF NOT EXISTS investigation_bookings_number_seq;

CREATE TABLE IF NOT EXISTS investigation_bookings (
  id                          BIGSERIAL PRIMARY KEY,
  booking_number              VARCHAR(40) UNIQUE,
  patient_id                  INTEGER NOT NULL,
  patient_name                VARCHAR(255),
  patient_phone               VARCHAR(20),
  investigation_id            INTEGER,
  test_name                   VARCHAR(255),
  selected_tests              INTEGER[],
  custom_test_names           TEXT,
  actual_tests                INTEGER[],
  slip_photo_key              TEXT,
  notes                       TEXT,
  collection_type             VARCHAR(20) DEFAULT 'home',
  collection_address          TEXT,
  collection_landmark         TEXT,
  collection_lat              NUMERIC(10,7),
  collection_lng              NUMERIC(10,7),
  collector_lat               NUMERIC(10,7),
  collector_lng               NUMERIC(10,7),
  estimated_collection_mins   INTEGER,
  collection_distance_km      NUMERIC(8,3),
  collection_tracking_active  BOOLEAN NOT NULL DEFAULT FALSE,
  preferred_date              DATE,
  preferred_time_slot         VARCHAR(50),
  scheduled_date              DATE,
  estimated_cost              NUMERIC(10,2),
  final_cost                  NUMERIC(10,2),
  status                      VARCHAR(40) NOT NULL DEFAULT 'BOOKED',
  phlebotomist_id             INTEGER,
  assigned_collector          INTEGER,
  collector_phone             VARCHAR(20),
  confirmed_by                INTEGER,
  confirmed_at                TIMESTAMP WITH TIME ZONE,
  confirmation_notes          TEXT,
  sla_dispatch_target         TIMESTAMP WITH TIME ZONE,
  sla_collect_target          TIMESTAMP WITH TIME ZONE,
  sla_result_target           TIMESTAMP WITH TIME ZONE,
  dispatched_at               TIMESTAMP WITH TIME ZONE,
  collected_at                TIMESTAMP WITH TIME ZONE,
  collected_by                INTEGER,
  collection_notes            TEXT,
  processing_started_at       TIMESTAMP WITH TIME ZONE,
  result_uploaded_at          TIMESTAMP WITH TIME ZONE,
  result_uploaded_by          INTEGER,
  result_file_key             TEXT,
  result_notes                TEXT,
  created_at                  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT investigation_bookings_patient_fk
    FOREIGN KEY (patient_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT investigation_bookings_investigation_fk
    FOREIGN KEY (investigation_id) REFERENCES investigations(id) ON DELETE SET NULL,
  CONSTRAINT investigation_bookings_phlebotomist_fk
    FOREIGN KEY (phlebotomist_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_invbook_patient_id        ON investigation_bookings(patient_id);
CREATE INDEX IF NOT EXISTS idx_invbook_status            ON investigation_bookings(status);
CREATE INDEX IF NOT EXISTS idx_invbook_created_at        ON investigation_bookings(created_at);
CREATE INDEX IF NOT EXISTS idx_invbook_collector_active  ON investigation_bookings(collection_tracking_active) WHERE collection_tracking_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_invbook_dispatched_recent ON investigation_bookings(dispatched_at) WHERE dispatched_at IS NOT NULL;

-- Trigger to auto-generate booking_number on insert when not supplied.
CREATE OR REPLACE FUNCTION investigation_bookings_set_number()
RETURNS TRIGGER AS $fn$
BEGIN
  IF NEW.booking_number IS NULL OR NEW.booking_number = '' THEN
    NEW.booking_number := 'INV-' || to_char(CURRENT_DATE, 'YYYYMMDD')
                          || '-' || lpad(nextval('investigation_bookings_number_seq')::text, 5, '0');
  END IF;
  RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS investigation_bookings_set_number_trg ON investigation_bookings;
CREATE TRIGGER investigation_bookings_set_number_trg
  BEFORE INSERT ON investigation_bookings
  FOR EACH ROW EXECUTE FUNCTION investigation_bookings_set_number();

-- ─── investigation_booking_history ─────────────────────────────────────
-- Append-only audit trail. Every status transition (BOOKED → CONFIRMED →
-- DISPATCHED → COLLECTED → PROCESSING → RESULT_READY) writes a row.
CREATE TABLE IF NOT EXISTS investigation_booking_history (
  id              BIGSERIAL PRIMARY KEY,
  booking_id      BIGINT NOT NULL,
  from_status     VARCHAR(40),
  to_status       VARCHAR(40) NOT NULL,
  changed_by      INTEGER,
  changed_by_role VARCHAR(40),
  notes           TEXT,
  created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT invbookhist_booking_fk
    FOREIGN KEY (booking_id) REFERENCES investigation_bookings(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_invbookhist_booking_id_time
  ON investigation_booking_history(booking_id, created_at);

COMMIT;
