-- Migration 164: PCPNDT Act compliance — Form F + USG register
-- (Sprint 18).
--
-- The Pre-Conception and Pre-Natal Diagnostic Techniques Act mandates
-- that EVERY ultrasound performed on a female patient be recorded in
-- a specific Form F format and entered in a register that's
-- inspectable by the District Appropriate Authority. Failure carries
-- criminal liability for the centre + sonologist.
--
-- We're modelling:
--   1. The USG machine inventory (must be GoI-registered)
--   2. The sonologist roster (must be PCPNDT-trained + signed
--      undertaking)
--   3. The Form F record per ultrasound (32 numbered fields per the
--      official Form F)
--   4. Monthly state submission rollup
--
-- The form itself is filed with the District Authority within 5 days
-- of every test (some states require submission by 5th of next
-- month).

BEGIN;

-- ── 1. USG machine register ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pcpndt_usg_machines (
  id                    SERIAL PRIMARY KEY,
  machine_code          VARCHAR(40) NOT NULL,        -- internal code
  manufacturer          VARCHAR(120) NOT NULL,
  model                 VARCHAR(120) NOT NULL,
  serial_number         VARCHAR(120) NOT NULL,
  -- PCPNDT registration with the District Authority. Without this
  -- the machine cannot be used at all.
  pcpndt_registration_no VARCHAR(80) NOT NULL,
  registered_at         DATE,
  registration_valid_to DATE,                        -- usually 5 years
  location              VARCHAR(160),                -- room / dept
  status                VARCHAR(20) NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'maintenance', 'decommissioned')),
  notes                 TEXT,
  tenant_id             UUID NOT NULL DEFAULT '00000000-0000-4000-8000-000000000001'::uuid,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, machine_code)
);

-- ── 2. Sonologist roster ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pcpndt_sonologists (
  id                       SERIAL PRIMARY KEY,
  staff_uid                UUID,                     -- link to users.uid if available
  name                     VARCHAR(160) NOT NULL,
  qualification            VARCHAR(120),             -- MD radiology / 6mo PCPNDT cert
  medical_council_reg      VARCHAR(80),              -- MCI / SMC
  pcpndt_training_cert_no  VARCHAR(80),              -- 6-month course cert
  pcpndt_training_date     DATE,
  -- Each sonologist signs an undertaking on Form 8 stating they will
  -- not perform sex determination. Date this was signed.
  undertaking_signed_at    DATE,
  active                   BOOLEAN NOT NULL DEFAULT true,
  tenant_id                UUID NOT NULL DEFAULT '00000000-0000-4000-8000-000000000001'::uuid,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── 3. Form F per ultrasound ────────────────────────────────────────
-- The 32-field Form F. Most fields are required by the act; we keep
-- them as named columns rather than JSONB so the inspector report can
-- be generated by a simple query.
CREATE TABLE IF NOT EXISTS pcpndt_form_f (
  id                     SERIAL PRIMARY KEY,
  -- Identity (Form F fields 1-7)
  serial_no              INTEGER NOT NULL,           -- per-tenant register sequence
  test_date              DATE NOT NULL,
  patient_uid            UUID,                       -- internal link, not on the form
  patient_name           VARCHAR(160) NOT NULL,
  patient_age            INTEGER NOT NULL,
  husband_or_father_name VARCHAR(160) NOT NULL,
  full_address           TEXT NOT NULL,
  contact_number         VARCHAR(20),
  -- Pregnancy details (fields 8-12)
  gravida                INTEGER NOT NULL DEFAULT 1,
  parity                 INTEGER NOT NULL DEFAULT 0,
  abortions              INTEGER NOT NULL DEFAULT 0,
  living_children        INTEGER NOT NULL DEFAULT 0,
  living_children_sex    VARCHAR(60),                -- 'M / M / F' format
  lmp_date               DATE,
  gestational_age_weeks  NUMERIC(4, 1),
  -- Indication (field 13) — exhaustive list per the act. The presence
  -- of any of these is what justifies the test in the first place.
  indication             TEXT NOT NULL,
  indication_category    VARCHAR(40)
    CHECK (indication_category IN (
      'to_diagnose_intrauterine_pregnancy',
      'genetic_testing_with_consent',
      'detection_of_anomalies',
      'multiple_pregnancy',
      'placental_localisation',
      'fetal_well_being',
      'cervical_incompetence',
      'placenta_praevia',
      'other'
    )),
  -- Referral (fields 14-15)
  referred_by_doctor_name VARCHAR(160),
  referred_by_reg_no      VARCHAR(80),
  -- Procedure detail (fields 16-22)
  procedure_kind         VARCHAR(40) NOT NULL DEFAULT 'usg'
    CHECK (procedure_kind IN ('usg', 'imaging_other', 'invasive')),
  machine_id             INTEGER REFERENCES pcpndt_usg_machines(id) ON DELETE RESTRICT,
  sonologist_id          INTEGER REFERENCES pcpndt_sonologists(id) ON DELETE RESTRICT,
  procedure_findings     TEXT,
  -- Sex determination disclosure tracking (fields 23-26) — DECLARATION
  -- by the sonologist that sex was NOT determined nor communicated.
  -- This boolean is what the inspector cares most about.
  sex_determination_disclosed BOOLEAN NOT NULL DEFAULT false,
  -- Patient consent declaration (Form G in some states; baked in
  -- here for simplicity)
  consent_taken          BOOLEAN NOT NULL DEFAULT true,
  consent_signed_at      TIMESTAMPTZ DEFAULT NOW(),
  -- Workflow
  status                 VARCHAR(20) NOT NULL DEFAULT 'completed'
    CHECK (status IN ('draft', 'completed', 'submitted_to_authority', 'voided')),
  submitted_at           TIMESTAMPTZ,                -- when the monthly report covered this row
  submission_batch_id    INTEGER,                    -- groups rows by monthly submission
  voided_reason          TEXT,
  -- Audit
  created_by             UUID,
  tenant_id              UUID NOT NULL DEFAULT '00000000-0000-4000-8000-000000000001'::uuid,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, serial_no)
);

CREATE INDEX IF NOT EXISTS idx_pcpndt_form_f_test_date
  ON pcpndt_form_f(tenant_id, test_date DESC);
CREATE INDEX IF NOT EXISTS idx_pcpndt_form_f_pending_submission
  ON pcpndt_form_f(tenant_id, test_date)
  WHERE status = 'completed' AND submitted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_pcpndt_form_f_machine
  ON pcpndt_form_f(machine_id, test_date DESC);
CREATE INDEX IF NOT EXISTS idx_pcpndt_form_f_sonologist
  ON pcpndt_form_f(sonologist_id, test_date DESC);

-- Per-tenant serial number generator.
CREATE TABLE IF NOT EXISTS pcpndt_serial_counter (
  tenant_id   UUID PRIMARY KEY,
  next_value  INTEGER NOT NULL DEFAULT 1
);

-- ── 4. Monthly submission batch ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS pcpndt_submissions (
  id              SERIAL PRIMARY KEY,
  period_year     INTEGER NOT NULL,
  period_month    INTEGER NOT NULL CHECK (period_month BETWEEN 1 AND 12),
  generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  generated_by    UUID,
  -- Counts cached at generation time (immutable after submission).
  total_forms     INTEGER NOT NULL,
  -- District authority acknowledgement
  submitted_to_authority_at TIMESTAMPTZ,
  authority_reference VARCHAR(120),
  notes           TEXT,
  tenant_id       UUID NOT NULL DEFAULT '00000000-0000-4000-8000-000000000001'::uuid,
  UNIQUE (tenant_id, period_year, period_month)
);

CREATE INDEX IF NOT EXISTS idx_pcpndt_submissions_period
  ON pcpndt_submissions(tenant_id, period_year DESC, period_month DESC);

COMMIT;
