---
- name: Restart rke2-server
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted
  listen: restart rke2-server

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd
