// Pins the deployment-wide FILE_SCAN_POLICY ingest contract (871-F1).
//
// fileScanService.js claims "every path that accepts bytes from a caller and
// stores them calls screenUploadBuffer". That claim was false when #871
// shipped — only 2 of ~14 ingest sites screened. This suite makes the claim
// enforceable in two directions:
//
//   1. A pinned list of every known caller-byte ingest module, each of which
//      must call screenUploadBuffer.
//   2. A repository sweep: ANY non-test src file that both stores via
//      uploadFileToR2 and touches a multer-style caller buffer
//      (req.file.buffer / file.buffer / attachmentFile.buffer) must screen.
//      A brand-new ingest route that skips the screen fails here without this
//      file ever being edited. (Server-generated bytes — rendered PDFs — do
//      not match the caller-buffer patterns and are deliberately exempt.)
//
// It also pins the serving gates added by this wave: the stores that carry a
// scan_status must consult the shared servable-set allowlist before bytes or
// signed URLs leave the API.

import { readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

const read = (rel) => readFileSync(path.join(SRC_ROOT, rel), 'utf8');

// Every known caller-byte ingest module. Additions belong here AND in the
// fileScanService.js header coverage map.
const INGEST_MODULES = [
  'controllers/upload/uploadController.js',
  'services/messaging/messagingService.js',
  'services/investigation/fileService.js',
  'controllers/investigation/bookingController.js',
  'controllers/appointment/appointmentDocumentController.js',
  'controllers/patient/patientSearchController.js',
  'controllers/pharmacy/pharmacyOrderController.js',
  'controllers/prescription/ePrescriptionController.js',
  'routes/consentRoutes.js',
  'routes/portal/patientPortalRoutes.js',
  'routes/staff/index.js',
  'services/staff/credentialingService.js',
];

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    const stats = statSync(full);
    if (stats.isDirectory()) {
      if (entry === 'tests' || entry === 'node_modules') continue;
      walk(full, out);
    } else if (entry.endsWith('.js')) {
      out.push(full);
    }
  }
  return out;
}

describe('FILE_SCAN_POLICY ingest coverage (871-F1)', () => {
  it.each(INGEST_MODULES)('%s screens caller bytes through screenUploadBuffer', (rel) => {
    const src = read(rel);
    expect(src).toContain('screenUploadBuffer');
  });

  it('no src module stores caller bytes without screening (repository sweep)', () => {
    const callerBufferRe = /req\.file\.buffer|(?<![A-Za-z0-9_.])file\.buffer|attachmentFile\.buffer/;
    const offenders = [];
    for (const full of walk(SRC_ROOT)) {
      const src = readFileSync(full, 'utf8');
      if (!src.includes('uploadFileToR2(')) continue;
      if (!callerBufferRe.test(src)) continue; // server-generated bytes only
      if (!src.includes('screenUploadBuffer')) {
        offenders.push(path.relative(SRC_ROOT, full));
      }
    }
    expect(offenders).toEqual([]);
  });

  it('the local-disk investigation ingest (fs.writeFile) screens too', () => {
    const src = read('services/investigation/fileService.js');
    const screenAt = src.indexOf('screenUploadBuffer(');
    const writeAt = src.indexOf('fs.writeFile(');
    expect(screenAt).toBeGreaterThan(-1);
    expect(writeAt).toBeGreaterThan(-1);
    expect(screenAt).toBeLessThan(writeAt);
  });
});

describe('scan-status serving gates (871-F1)', () => {
  it('investigation file streaming gates on the shared servable set', () => {
    const src = read('services/investigation/fileService.js');
    expect(src).toContain('isScanStatusServable(file.scan_status)');
    // The gate throws the same 423 contract as the messaging gate.
    expect(src).toContain('FILE_SCAN_NOT_CLEAN');
  });

  it('consent-signature PDF embedding gates on the shared servable set', () => {
    const src = read('routes/consentRoutes.js');
    const gateAt = src.indexOf('isScanStatusServable(sig.scan_status)');
    const embedAt = src.indexOf('getFileFromR2(sig.storage_key)');
    expect(gateAt).toBeGreaterThan(-1);
    expect(embedAt).toBeGreaterThan(-1);
    expect(gateAt).toBeLessThan(embedAt);
  });

  it('booking slip/result signed URLs are issued only through the gated helper', () => {
    const src = read('controllers/investigation/bookingController.js');
    // Every serve site goes through gatedSignedUrl (3 sites × 2 keys), and no
    // raw getSignedFileUrl call remains outside the helper itself.
    const gated = src.match(/gatedSignedUrl\(b\.(slip_photo|result_file)_key/g) || [];
    expect(gated).toHaveLength(6);
    const raw = src.match(/getSignedFileUrl\(/g) || [];
    expect(raw).toHaveLength(1); // the helper's own call
    expect(src).toContain('isScanStatusServable(scanStatus)');
  });

  it('every ingest writer that has a scan_status column persists the screener verdict', () => {
    expect(read('services/investigation/fileService.js')).toContain('screened.scanStatus');
    expect(read('routes/consentRoutes.js')).toContain('screened.scanStatus');
    const booking = read('controllers/investigation/bookingController.js');
    expect(booking).toContain('slip_photo_scan_status');
    expect(booking).toContain('result_file_scan_status');
  });
});
