// src/config/rbacConfig.js
import {
  SUPER_ADMIN,
  ADMIN,
  PATIENT,
  NURSING_STAFF,
  NURSING_INCHARGE,
  OP_STAFF_NURSE,
  OP_INCHARGE,
  IP_STAFF_NURSE,
  IP_INCHARGE,
  OT_NURSE,
  OT_INCHARGE,
  OT_STAFF,
  CATH_LAB_STAFF,
  CATH_LAB_INCHARGE,
  PHARMACY_STAFF,
  PHARMACY_INCHARGE,
  STORES_PURCHASE_INCHARGE,
  LAB_STAFF,
  RADIOLOGY_STAFF,
  DOCTOR,
  ANAESTHETIST,
  ANESTHETIST,
  DUTY_DOCTOR,
  MEDICAL_SUPERINTENDENT,
  CMO,
  CNO,
  GENERAL_STAFF,
  HOUSEKEEPING_STAFF,
  HOUSEKEEPING_INCHARGE,
  MAINTENANCE,
  HR_STAFF,
  RECEPTIONIST,
  RECEPTION_INCHARGE,
  DELIVERY_STAFF,
  DRIVER,
  SECURITY,
  EMERGENCY_RESPONDER,
  BILLING_STAFF,
  BILLING_INCHARGE,
  FINANCE_INCHARGE,
  INSURANCE_COORDINATOR,
  ADMISSION_OFFICER,
  IPD_COUNSELLOR
} from '../utils/roles.js';

export default {
  // Global/default buckets (used by some wrappers)
  ALL: [ADMIN],

  // ✅ Centralized Admin namespace (consistent with /api/v1/admin/*)
  adminDashboard: [ADMIN], // used by routes/admin/index.js wrapAutoRBAC key
  adminRoutes: [ADMIN], // generic catch-all if some modules reference this
  adminDepartmentRoutes: [ADMIN],
  adminDoctorRoutes: [ADMIN],
  adminUserRoutes: [ADMIN],
  adminAppointmentRoutes: [ADMIN],
  adminNotificationRoutes: [ADMIN],
  adminRecordRoutes: [ADMIN],
  adminInvestigationRoutes: [ADMIN],
  adminPharmacyRoutes: [ADMIN],
  adminPharmacySupplyRoutes: [ADMIN, PHARMACY_INCHARGE, STORES_PURCHASE_INCHARGE],
  adminAnalyticsRoutes: [ADMIN],

  // 🔐 Authenticated (non-admin) module route keys
  appointmentRoutes: [PATIENT, NURSING_STAFF, OP_STAFF_NURSE, OP_INCHARGE, DOCTOR, RECEPTIONIST, RECEPTION_INCHARGE, ADMIN],
  doctorRoutes: [DOCTOR, ADMIN],
  departmentRoutes: [GENERAL_STAFF, ADMIN],
  userRoutes: [PATIENT, GENERAL_STAFF, ADMIN],
  // Bell-icon endpoints — every authenticated user (patient + every staff
  // role) needs `GET /notifications/my`. Pharmacy/Lab/HR previously got
  // 403 because they weren't listed; the staff app shows a perpetual
  // empty notifications panel until they're allowed. Stage-5 added the
  // billing / TPA / admission-counter desk roles — same treatment (the
  // role-workflow sweep caught all four 403ing on /notifications/my).
  notificationRoutes: [
    PATIENT,
    GENERAL_STAFF,
    HOUSEKEEPING_STAFF,
    HOUSEKEEPING_INCHARGE,
    MAINTENANCE,
    ADMIN,
    SUPER_ADMIN,
    DOCTOR,
    NURSING_STAFF,
    IP_STAFF_NURSE,
    IP_INCHARGE,
    OP_STAFF_NURSE,
    OP_INCHARGE,
    OT_NURSE,
    OT_INCHARGE,
    CATH_LAB_STAFF,
    PHARMACY_INCHARGE,
    PHARMACY_STAFF,
    STORES_PURCHASE_INCHARGE,
    LAB_STAFF,
    HR_STAFF,
    RECEPTIONIST,
    RECEPTION_INCHARGE,
    BILLING_STAFF,
    INSURANCE_COORDINATOR,
    ADMISSION_OFFICER,
    IPD_COUNSELLOR
  ],
  pharmacyRoutes: [PHARMACY_STAFF, PHARMACY_INCHARGE, NURSING_STAFF, IP_STAFF_NURSE, OP_STAFF_NURSE, DOCTOR, ADMIN],
  // If you use a separate key for /pharmacy-orders in wrappers:
  pharmacyOrdersRoutes: [PATIENT, PHARMACY_STAFF, PHARMACY_INCHARGE, NURSING_STAFF, IP_STAFF_NURSE, OP_STAFF_NURSE, DOCTOR, ADMIN],
  pharmacyOrderRoutes: [PHARMACY_STAFF, PHARMACY_INCHARGE, NURSING_STAFF, IP_STAFF_NURSE, OP_STAFF_NURSE, DOCTOR, ADMIN],
  // Pharmacy lifecycle — patient can place + view own orders
  pharmacyPatientOrderRoutes: [PATIENT, PHARMACY_STAFF, PHARMACY_INCHARGE, NURSING_STAFF, IP_STAFF_NURSE, OP_STAFF_NURSE, DOCTOR, ADMIN],
  // Pharmacy staff/admin lifecycle actions
  pharmacyLifecycleRoutes: [PHARMACY_STAFF, PHARMACY_INCHARGE, ADMIN],
  pharmacyStaffOrderRoutes: [PHARMACY_STAFF, PHARMACY_INCHARGE, ADMIN],
  staffPharmacyRoutes: [PHARMACY_STAFF, PHARMACY_INCHARGE, ADMIN],
  pharmacyStaffMedicationRoutes: [PHARMACY_STAFF, PHARMACY_INCHARGE, STORES_PURCHASE_INCHARGE, ADMIN],
  pharmacyAdminMedicationRoutes: [PHARMACY_INCHARGE, ADMIN],
  pharmacyStaffInventoryRoutes: [PHARMACY_STAFF, PHARMACY_INCHARGE, STORES_PURCHASE_INCHARGE, ADMIN],
  // Pharmacy formulary read access is shared by clinical prescribing flows.
  pharmacyCatalogRoutes: [
    PHARMACY_STAFF,
    PHARMACY_INCHARGE,
    STORES_PURCHASE_INCHARGE,
    NURSING_STAFF,
    IP_STAFF_NURSE,
    OP_STAFF_NURSE,
    DOCTOR,
    DUTY_DOCTOR,
    'CONSULTANT',
    'JUNIOR_DOCTOR',
    'RESIDENT',
    ADMIN
  ],
  // Pharmacy formulary write access is intentionally narrower.
  pharmacyCatalogAdminRoutes: [PHARMACY_INCHARGE, ADMIN],

  // Patient self-service record routes (/records/health-records/my,
  // /records/consultations/my) self-scope from the JWT before returning data.
  recordRoutes: [PATIENT, ADMIN, GENERAL_STAFF, DOCTOR, NURSING_STAFF, IP_STAFF_NURSE, OP_STAFF_NURSE, OT_NURSE, OT_INCHARGE, CATH_LAB_STAFF],
  // ✅ Fix: use NURSING_STAFF constant instead of string 'NURSE'
  healthRecordsRoutes: [PATIENT, ADMIN, DOCTOR, NURSING_STAFF, IP_STAFF_NURSE, OP_STAFF_NURSE, OT_NURSE, OT_INCHARGE, CATH_LAB_STAFF],

  investigationRoutes: [
    PATIENT,
    LAB_STAFF,
    NURSING_STAFF,
    NURSING_INCHARGE,
    IP_STAFF_NURSE,
    IP_INCHARGE,
    OP_STAFF_NURSE,
    OP_INCHARGE,
    OT_NURSE,
    OT_INCHARGE,
    CATH_LAB_STAFF,
    CATH_LAB_INCHARGE,
    RECEPTIONIST,
    RECEPTION_INCHARGE,
    DOCTOR,
    DUTY_DOCTOR,
    MEDICAL_SUPERINTENDENT,
    CNO,
    ADMIN,
    SUPER_ADMIN
  ],
  medicalStaffRoutes: [
    DOCTOR,
    DUTY_DOCTOR,
    MEDICAL_SUPERINTENDENT,
    CNO,
    NURSING_STAFF,
    NURSING_INCHARGE,
    IP_STAFF_NURSE,
    IP_INCHARGE,
    OP_STAFF_NURSE,
    OP_INCHARGE,
    OT_NURSE,
    OT_INCHARGE,
    OT_STAFF,
    CATH_LAB_STAFF,
    CATH_LAB_INCHARGE,
    LAB_STAFF,
    ADMIN,
    SUPER_ADMIN
  ],

  // Mixed/utility
  feedbackRoutes: [PATIENT, GENERAL_STAFF, ADMIN],
  sosRoutes: [PATIENT, GENERAL_STAFF, ADMIN],
  // /api/v1/staff/* — staff profile (GET /:identifier), staff list,
  // staff by department/shift, staff statistics. Every staff role
  // needs to read their OWN profile (the staff app's Profile screen
  // calls GET /staff/:employeeId on launch). Authorisation is then
  // refined inside the controller (only ADMIN/HR_STAFF can read OTHER
  // staff's full PII; non-admins get the limited public-profile
  // shape). Including all staff roles here closes the 403-on-Profile
  // surface that NURSING_STAFF / DOCTOR / PHARMACY_STAFF / LAB_STAFF
  // / HR_STAFF were hitting on the freshly-installed staff app.
  staffRoutes: [
    SUPER_ADMIN,
    ADMIN,
    GENERAL_STAFF,
    HOUSEKEEPING_STAFF,
    HOUSEKEEPING_INCHARGE,
    MAINTENANCE,
    NURSING_STAFF,
    NURSING_INCHARGE,
    IP_STAFF_NURSE,
    IP_INCHARGE,
    OP_STAFF_NURSE,
    OP_INCHARGE,
    OT_NURSE,
    OT_INCHARGE,
    OT_STAFF,
    CATH_LAB_STAFF,
    CATH_LAB_INCHARGE,
    DOCTOR,
    ANAESTHETIST,
    ANESTHETIST,
    DUTY_DOCTOR,
    MEDICAL_SUPERINTENDENT,
    CMO,
    CNO,
    PHARMACY_STAFF,
    PHARMACY_INCHARGE,
    STORES_PURCHASE_INCHARGE,
    LAB_STAFF,
    RADIOLOGY_STAFF,
    RECEPTIONIST,
    RECEPTION_INCHARGE,
    BILLING_STAFF,
    BILLING_INCHARGE,
    FINANCE_INCHARGE,
    INSURANCE_COORDINATOR,
    ADMISSION_OFFICER,
    IPD_COUNSELLOR,
    DRIVER,
    SECURITY,
    EMERGENCY_RESPONDER,
    HR_STAFF
  ],
  // /api/v1/housekeeping/* — staff self-service (raise/complete tickets,
  // submit cleaning logs, view zones). Every operational role can use it
  // because the request workflow spans wards/labs/pharmacy. Admin
  // verification + zone administration is gated separately via
  // housekeepingAdminRoutes below.
  housekeepingRoutes: [
    ADMIN,
    HOUSEKEEPING_STAFF,
    HOUSEKEEPING_INCHARGE,
    NURSING_STAFF,
    NURSING_INCHARGE,
    IP_STAFF_NURSE,
    IP_INCHARGE,
    OP_STAFF_NURSE,
    OP_INCHARGE,
    OT_NURSE,
    OT_INCHARGE,
    CATH_LAB_STAFF,
    DOCTOR,
    DUTY_DOCTOR,
    MEDICAL_SUPERINTENDENT,
    CNO,
    PHARMACY_STAFF,
    LAB_STAFF,
    HR_STAFF
  ],
  housekeepingAdminRoutes: [ADMIN, HR_STAFF, HOUSEKEEPING_INCHARGE],
  housekeepingZoneAdminRoutes: [ADMIN, HR_STAFF],
  staffRosterBoardRoutes: [
    SUPER_ADMIN,
    ADMIN,
    HR_STAFF,
    HOUSEKEEPING_INCHARGE,
    HOUSEKEEPING_STAFF,
    NURSING_INCHARGE,
    NURSING_STAFF,
    IP_STAFF_NURSE,
    IP_INCHARGE,
    OP_STAFF_NURSE,
    OP_INCHARGE,
    OT_NURSE,
    OT_INCHARGE,
    OT_STAFF,
    CATH_LAB_STAFF,
    CATH_LAB_INCHARGE,
    DOCTOR,
    DUTY_DOCTOR,
    MEDICAL_SUPERINTENDENT,
    CMO,
    CNO,
    PHARMACY_STAFF,
    PHARMACY_INCHARGE,
    STORES_PURCHASE_INCHARGE,
    RECEPTIONIST,
    RECEPTION_INCHARGE,
    ADMISSION_OFFICER,
    DELIVERY_STAFF,
    DRIVER,
    MAINTENANCE,
    'AMBULANCE_DRIVER',
    'AMBULANCE_COORDINATOR',
    'EMERGENCY_RESPONDER',
    'CONSULTANT',
    'JUNIOR_DOCTOR',
    'RESIDENT'
  ],
  lookupRoutes: [ADMIN, GENERAL_STAFF, HOUSEKEEPING_STAFF, HOUSEKEEPING_INCHARGE, MAINTENANCE],

  // Public / open routes
  authRoutes: [],
  firebaseAuthRoutes: [],
  otpRoutes: [],
  swaggerRoutes: [],

  // Infra / tooling
  debugRoutes: [ADMIN],
  versionRoutes: [
    ADMIN,
    DOCTOR,
    NURSING_STAFF,
    IP_STAFF_NURSE,
    OP_STAFF_NURSE,
    OT_NURSE,
    OT_INCHARGE,
    CATH_LAB_STAFF,
    PHARMACY_STAFF,
    PHARMACY_INCHARGE,
    STORES_PURCHASE_INCHARGE,
    LAB_STAFF,
    HR_STAFF,
    GENERAL_STAFF,
    HOUSEKEEPING_STAFF,
    HOUSEKEEPING_INCHARGE,
    MAINTENANCE
  ],
  rbacRoutes: [ADMIN, HR_STAFF],
  adminDocumentationRoutes: [ADMIN]
};
