// src/services/appointment/appointmentQueryService.js
// Appointment read paths — every list query uses typed Prisma `include`
// via the relations declared in migration 084 (appointments.doctor_id →
// doctors.id, appointments.patient_id → users.id). Column-rename drift
// on appointments / users / doctors surfaces at query-construction.

import { APPOINTMENT_CONFIG } from '../../config/appointmentConfig.js';
import prisma from '../../lib/prisma.js';
import logger from '../../logging/logger.js';
import { buildPaginationMeta } from '../../utils/appointment/appointmentHelpers.js';

// Base set of appointment columns every list view returns.
const APPT_BASE_SELECT = {
  id: true,
  appointment_date: true,
  appointment_time: true,
  status: true,
  reason: true,
  notes: true,
  patient_id: true,
  doctor_id: true,
  phone: true,
  patient_name: true,
  doctor_name: true,
  created_at: true,
  updated_at: true,
};

// Doctor relation — appointments.doctor_id → users.id. The doctor's
// profile (specialty/department) lives in the `doctors` child table
// with FK doctors.user_id → users.id. `take: 1` limits to the first
// doctor profile since every doctor user has ≤1 row in practice.
const DOCTOR_INCLUDE = {
  select: {
    id: true,
    name: true,
    phone: true,
    email: true,
    doctors: {
      select: { specialty: true, department: true },
      take: 1,
    },
  },
};

// Patient relation — appointments.patient_id → users.id.
const PATIENT_INCLUDE = {
  select: {
    id: true,
    name: true,
    phone: true,
    email: true,
  },
};

// Format a date range filter for `DATE(appointment_date) = $d` — Prisma's
// Date equality on an appointment_date Date column needs the whole day
// covered.
//
// Accepts either an ISO date string ("2026-05-02") OR a relative keyword
// ("today" / "tomorrow" / "yesterday"). The validator's customSanitizer
// would normally rewrite these before hitting the controller, but Express 5
// made `req.query` immutable — sanitizer return values don't persist into
// `req.query.date`. Resolve here as the authoritative second line of defense
// so /appointments/list?date=today renders 200 instead of bombing through
// `new Date("today")` → Invalid Date → Prisma validation error → 500.
const ONE_DAY_MS = 24 * 60 * 60 * 1000;
function resolveDateInput(date) {
  if (typeof date !== 'string') return date;
  const v = date.trim().toLowerCase();
  const now = new Date();
  if (v === 'today') return now.toISOString().slice(0, 10);
  if (v === 'tomorrow') return new Date(now.getTime() + ONE_DAY_MS).toISOString().slice(0, 10);
  if (v === 'yesterday') return new Date(now.getTime() - ONE_DAY_MS).toISOString().slice(0, 10);
  return date;
}

function dateRangeFilter(date) {
  const resolved = resolveDateInput(date);
  const start = new Date(resolved);
  const end = new Date(resolved);
  end.setDate(end.getDate() + 1);
  return { gte: start, lt: end };
}

// Relation field names (auto-generated by Prisma from the two FKs to
// users). Constants so the six list queries + flattener stay in sync.
const REL_PATIENT = 'users_appointments_patient_idTousers';
const REL_DOCTOR = 'users_appointments_doctor_idTousers';

// Flatten the nested relation payload back into the flat-alias response
// shape that the old SQL returned.
function flattenListRow(row) {
  const patient = row[REL_PATIENT] ?? null;
  const doctor = row[REL_DOCTOR] ?? null;
  const profile = doctor?.doctors?.[0] ?? null;
  const flat = { ...row };
  delete flat[REL_PATIENT];
  delete flat[REL_DOCTOR];
  flat.patient_name = patient?.name ?? row.patient_name ?? null;
  flat.patient_phone = patient?.phone ?? row.phone ?? null;
  flat.patient_email = patient?.email ?? null;
  flat.doctor_name = doctor?.name ?? row.doctor_name ?? null;
  flat.doctor_phone = doctor?.phone ?? null;
  flat.doctor_email = doctor?.email ?? null;
  // Legacy aliases used by different callers.
  flat.doctor_specialization = profile?.specialty ?? null;
  flat.specialty = profile?.specialty ?? null;
  flat.doctor_department = profile?.department ?? null;
  flat.department = profile?.department ?? null;
  return flat;
}

export class AppointmentQueryService {
  async getAppointments(filters = {}, pagination = {}, userRole = null, userId = null) {
    try {
      const page = pagination.page || APPOINTMENT_CONFIG.DEFAULT_PAGINATION.PAGE;
      const limit = pagination.limit || APPOINTMENT_CONFIG.DEFAULT_PAGINATION.LIMIT;
      const offset = (page - 1) * limit;

      const where = {};
      if (userRole === 'DOCTOR') where.doctor_id = parseInt(userId);
      if (filters.status) where.status = filters.status.toUpperCase();
      if (filters.doctor_id) where.doctor_id = parseInt(filters.doctor_id);
      if (filters.patient_id) where.patient_id = parseInt(filters.patient_id);
      if (filters.date) where.appointment_date = dateRangeFilter(filters.date);

      const [total, rows] = await Promise.all([
        prisma.appointments.count({ where }),
        prisma.appointments.findMany({
          where,
          select: {
            ...APPT_BASE_SELECT,
            users_appointments_patient_idTousers: PATIENT_INCLUDE,
            users_appointments_doctor_idTousers: DOCTOR_INCLUDE,
          },
          orderBy: [{ appointment_date: 'asc' }, { appointment_time: 'asc' }],
          take: limit,
          skip: offset,
        }),
      ]);

      return {
        appointments: rows.map(flattenListRow),
        pagination: buildPaginationMeta(page, limit, total),
        filters,
      };
    } catch (error) {
      logger.error('Error getting appointments:', error);
      throw error;
    }
  }

  async getDoctorAppointments(doctorId, filters = {}) {
    try {
      const status = (filters.status || APPOINTMENT_CONFIG.STATUSES.SCHEDULED).toUpperCase();

      const where = {
        doctor_id: parseInt(doctorId),
        status,
      };
      if (filters.date) where.appointment_date = dateRangeFilter(filters.date);

      const rows = await prisma.appointments.findMany({
        where,
        select: {
          id: true,
          appointment_date: true,
          appointment_time: true,
          status: true,
          reason: true,
          notes: true,
          patient_id: true,
          users_appointments_patient_idTousers: PATIENT_INCLUDE,
        },
        orderBy: [{ appointment_date: 'asc' }, { appointment_time: 'asc' }],
      });

      // This view only needs patient_* fields, no doctor aliases.
      return rows.map((r) => {
        const p = r[REL_PATIENT] ?? null;
        const flat = { ...r };
        delete flat[REL_PATIENT];
        flat.patient_name = p?.name ?? null;
        flat.patient_phone = p?.phone ?? null;
        flat.patient_email = p?.email ?? null;
        return flat;
      });
    } catch (error) {
      logger.error('Error getting doctor appointments:', error);
      throw error;
    }
  }

  async getPatientAppointments(patientId, filters = {}) {
    try {
      const where = { patient_id: parseInt(patientId) };
      if (filters.status) where.status = filters.status.toUpperCase();

      const rows = await prisma.appointments.findMany({
        where,
        select: {
          id: true,
          appointment_date: true,
          appointment_time: true,
          status: true,
          reason: true,
          notes: true,
          doctor_id: true,
          created_at: true,
          updated_at: true,
          users_appointments_doctor_idTousers: DOCTOR_INCLUDE,
        },
        orderBy: [{ appointment_date: 'desc' }, { appointment_time: 'desc' }],
      });

      // Only doctor_* + specialty/department aliases needed — no patient_*
      // (this view is scoped to one patient).
      return rows.map((r) => {
        const d = r[REL_DOCTOR] ?? null;
        const profile = d?.doctors?.[0] ?? null;
        const flat = { ...r };
        delete flat[REL_DOCTOR];
        flat.doctor_name = d?.name ?? null;
        flat.doctor_phone = d?.phone ?? null;
        flat.specialty = profile?.specialty ?? null;
        flat.department = profile?.department ?? null;
        return flat;
      });
    } catch (error) {
      logger.error('Error getting patient appointments:', error);
      throw error;
    }
  }

  async getTodayAppointments(userRole = null, userId = null) {
    try {
      const todayStr = new Date().toISOString().split('T')[0];
      const where = { appointment_date: dateRangeFilter(todayStr) };
      if (userRole === 'DOCTOR') where.doctor_id = parseInt(userId);

      const rows = await prisma.appointments.findMany({
        where,
        select: {
          id: true,
          appointment_time: true,
          status: true,
          reason: true,
          patient_id: true,
          doctor_id: true,
          [REL_PATIENT]: { select: { name: true, phone: true } },
          [REL_DOCTOR]: {
            select: {
              name: true,
              doctors: {
                select: { specialty: true, department: true },
                take: 1,
              },
            },
          },
        },
        orderBy: { appointment_time: 'asc' },
      });

      const appointments = rows.map((r) => {
        const p = r[REL_PATIENT] ?? null;
        const d = r[REL_DOCTOR] ?? null;
        const profile = d?.doctors?.[0] ?? null;
        const flat = { ...r };
        delete flat[REL_PATIENT];
        delete flat[REL_DOCTOR];
        flat.patient_name = p?.name ?? null;
        flat.patient_phone = p?.phone ?? null;
        flat.doctor_name = d?.name ?? null;
        flat.department = profile?.department ?? null;
        flat.specialty = profile?.specialty ?? null;
        return flat;
      });

      return { appointments, date: todayStr };
    } catch (error) {
      logger.error('Error getting today appointments:', error);
      throw error;
    }
  }

  async getAppointmentById(id) {
    try {
      const row = await prisma.appointments.findUnique({
        where: { id: parseInt(id) },
        select: {
          id: true,
          uid: true,
          phone: true,
          patient_id: true,
          doctor_id: true,
          doctor_name: true,
          patient_name: true,
          appointment_date: true,
          appointment_time: true,
          status: true,
          reason: true,
          notes: true,
          created_at: true,
          updated_at: true,
          users_appointments_patient_idTousers: PATIENT_INCLUDE,
          users_appointments_doctor_idTousers: DOCTOR_INCLUDE,
        },
      });
      if (!row) return null;

      const patient = row[REL_PATIENT] ?? null;
      const doctor = row[REL_DOCTOR] ?? null;
      const profile = doctor?.doctors?.[0] ?? null;
      const flat = { ...row };
      delete flat[REL_PATIENT];
      delete flat[REL_DOCTOR];
      flat.patient_email = patient?.email ?? null;
      // Old raw SQL used `d.name AS doctor_name_detail` — kept for callers
      // that already branch on that alias. The top-level doctor_name
      // (from the appointments row) stays whatever it was.
      flat.doctor_name_detail = doctor?.name ?? null;
      flat.doctor_phone = doctor?.phone ?? null;
      flat.doctor_email = doctor?.email ?? null;
      flat.specialty = profile?.specialty ?? null;
      flat.department = profile?.department ?? null;
      return flat;
    } catch (error) {
      logger.error('Error getting appointment by ID:', error);
      throw error;
    }
  }
}

export default new AppointmentQueryService();
