apiVersion: v1
kind: Namespace
metadata:
  name: vhhealth-security
  labels:
    app.kubernetes.io/part-of: vhhealth
    app.kubernetes.io/managed-by: kustomize
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
  annotations:
    vhhealth.app/description: "Security tooling — cert-manager, sealed-secrets, Vault, step-ca, Falco."
