// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// ─── SECURITY NOTICE (mirrors patient audit PAT-2 / PAT-13) ──────────────
// All Firebase API keys are read from dart-define compile-time variables —
// the same VH_FIREBASE_{WEB,ANDROID,IOS}_API_KEY names the patient app uses.
// The defaultValue strings below are the ORIGINAL committed keys that MUST
// be ROTATED before this build reaches production. They exist only so that
// CI and dev builds continue to compile without secrets; release workflows
// inject the rotated keys from GitHub Actions secrets.
// See docs/runbooks/FIREBASE_KEY_ROTATION.md for the rotation procedure.
//
// ─── APP REGISTRATION NOTICE ─────────────────────────────────────────────
// The appId / iosBundleId values in this file are the PATIENT app's Firebase
// registrations (this file was copied from apps/patient, not generated for
// staff). The staff identifiers — Android `com.vhhealth.staff.vhhealth_staff`
// and iOS `com.vhhealth.staff.vhhealthStaff` — are NOT yet registered in the
// `vhhealth` Firebase project. Until they are registered and this file is
// regenerated with `flutterfire configure`, release-mode App Check
// attestation (Play Integrity / DeviceCheck) cannot mint tokens for staff
// builds. Do NOT hand-edit the app IDs to invented values — that would break
// FCM today. Console steps: docs/runbooks/FIREBASE_KEY_ROTATION.md.
// ─────────────────────────────────────────────────────────────────────────
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web & Windows share the same project-level web API key.
  // ROTATE: VH_FIREBASE_WEB_API_KEY (see security notice above).
  static const _webApiKey = String.fromEnvironment(
    'VH_FIREBASE_WEB_API_KEY',
    defaultValue: 'AIzaSyD66kpN2hC6cbIXguLxhY5slhBX2TuSVCQ',
  );

  // ROTATE: VH_FIREBASE_ANDROID_API_KEY (see security notice above).
  static const _androidApiKey = String.fromEnvironment(
    'VH_FIREBASE_ANDROID_API_KEY',
    defaultValue: 'AIzaSyDiY5ya9Ji0nWXqzNuJIprUQm-t0FVex_8',
  );

  // ROTATE: VH_FIREBASE_IOS_API_KEY (see security notice above).
  // iOS and macOS use the same key.
  static const _iosApiKey = String.fromEnvironment(
    'VH_FIREBASE_IOS_API_KEY',
    defaultValue: 'AIzaSyCwP2m9gvOIQ659FzdlExdAK51ETLhwcsA',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:155620159512:web:ed8e4cc14d5e41549d136d',
    messagingSenderId: '155620159512',
    projectId: 'vhhealth',
    authDomain: 'vhhealth.firebaseapp.com',
    storageBucket: 'vhhealth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:155620159512:android:6b4839756b9f099a9d136d',
    messagingSenderId: '155620159512',
    projectId: 'vhhealth',
    storageBucket: 'vhhealth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:155620159512:ios:5118ce88fcd26ba19d136d',
    messagingSenderId: '155620159512',
    projectId: 'vhhealth',
    storageBucket: 'vhhealth.firebasestorage.app',
    iosBundleId: 'com.example.vhhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _iosApiKey,
    appId: '1:155620159512:ios:5118ce88fcd26ba19d136d',
    messagingSenderId: '155620159512',
    projectId: 'vhhealth',
    storageBucket: 'vhhealth.firebasestorage.app',
    iosBundleId: 'com.example.vhhealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _webApiKey,
    appId: '1:155620159512:web:76026d7a87e0c4eb9d136d',
    messagingSenderId: '155620159512',
    projectId: 'vhhealth',
    authDomain: 'vhhealth.firebaseapp.com',
    storageBucket: 'vhhealth.firebasestorage.app',
  );
}
