// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// WARNING: These Firebase options contain development/default credentials.
// In production, these values should be injected via build flavors
// (e.g. --dart-define or per-flavor firebase_options files) so that
// dev, staging, and prod environments use separate Firebase projects.
// See: https://firebase.google.com/docs/flutter/setup#configure-firebase-different-environments
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD66kpN2hC6cbIXguLxhY5slhBX2TuSVCQ',
    appId: '1:155620159512:web:ed8e4cc14d5e41549d136d',
    messagingSenderId: '155620159512',
    projectId: 'vhhealth',
    authDomain: 'vhhealth.firebaseapp.com',
    storageBucket: 'vhhealth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiY5ya9Ji0nWXqzNuJIprUQm-t0FVex_8',
    appId: '1:155620159512:android:6b4839756b9f099a9d136d',
    messagingSenderId: '155620159512',
    projectId: 'vhhealth',
    storageBucket: 'vhhealth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwP2m9gvOIQ659FzdlExdAK51ETLhwcsA',
    appId: '1:155620159512:ios:5118ce88fcd26ba19d136d',
    messagingSenderId: '155620159512',
    projectId: 'vhhealth',
    storageBucket: 'vhhealth.firebasestorage.app',
    iosBundleId: 'com.example.vhhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwP2m9gvOIQ659FzdlExdAK51ETLhwcsA',
    appId: '1:155620159512:ios:5118ce88fcd26ba19d136d',
    messagingSenderId: '155620159512',
    projectId: 'vhhealth',
    storageBucket: 'vhhealth.firebasestorage.app',
    iosBundleId: 'com.example.vhhealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD66kpN2hC6cbIXguLxhY5slhBX2TuSVCQ',
    appId: '1:155620159512:web:76026d7a87e0c4eb9d136d',
    messagingSenderId: '155620159512',
    projectId: 'vhhealth',
    authDomain: 'vhhealth.firebaseapp.com',
    storageBucket: 'vhhealth.firebasestorage.app',
  );
}
