// src/services/pharmacy/orderService.js
// Legacy pharmacy order service — kept for phone-based patient flows.
// Canonical schema: pharmacy_orders (patient_id int, priority, prescribed_by, dispensed_by,
// confirmation_notes, items_list jsonb, etc.). See also controllers/pharmacy/pharmacyOrderController.js
// for the richer delivery-tracking flow.

import { ORDER_STATUS, ORDER_STATUS_TRANSITIONS } from '../../config/pharmacyConfig.js';
import prisma from '../../lib/prisma.js';
import logger from '../../logging/logger.js';
import { normalizePhone } from '../../utils/phoneUtils.js';

// Relation names generated by Prisma for the three FKs on pharmacy_orders
// (migration 083). Long because of the two-FK-to-same-table disambiguation.
const REL_PATIENT = 'users_pharmacy_orders_patient_idTousers';

// Prisma-select for the base pharmacy_orders columns returned by every
// list view. Swapped out for SELECT-string clumping so renames fail at
// query-construction.
const ORDER_LIST_SELECT = {
  id: true,
  uid: true,
  phone: true,
  patient_id: true,
  patient_name: true,
  order_note: true,
  file_key: true,
  priority: true,
  status: true,
  confirmation_notes: true,
  prescribed_by: true,
  dispensed_by: true,
  ordered_at: true,
  updated_at: true,
  // The dispensed medication schedule per line item. The patient app
  // and pharmacy queue both need this to safely administer multi-drug
  // regimens at home (e.g. post-cataract eye drops). Finding
  // 2026-05-10-surgical-day-care-patient-pharmacy-order-omits-eye-drop-schedule.
  items_list: true,
};

export const createOrder = async (orderData) => {
  const { phone, order_note, file_key, urgent, delivery_type, requestedBy, requestedByRole } = orderData;
  const priority = urgent ? 'urgent' : 'normal';
  // Controller is authoritative for the enum; fall back to the DB
  // default ('delivery') when the caller didn't pass it.
  const resolvedDeliveryType = delivery_type === 'counter' ? 'counter' : 'delivery';

  // Resolve phone → patient_id (users.id). Match against both the canonical
  // E.164 form (`+91…`) and the bare 10-digit national form so a staff user
  // typing `9884123456` still resolves the row stored as `+919884123456`.
  // Previously the lookup used a single equality and silently failed for
  // either form, leaving patient_id/patient_name null on every staff order
  // — see finding 2026-05-08-walk-in-opd-pharmacy-order-patient-id-null.
  const trimmedPhone = String(phone || '').trim();
  const normalizedPhone = normalizePhone(trimmedPhone);
  const nationalPhone = normalizedPhone?.startsWith('+91')
    ? normalizedPhone.slice(3)
    : trimmedPhone.replace(/[^\d]/g, '');
  const users = await prisma.$queryRaw`
    SELECT id, name FROM users
    WHERE phone IN (${trimmedPhone}, ${normalizedPhone}, ${nationalPhone})
    LIMIT 1
  `;
  const patientId = users[0]?.id ?? null;
  const patientName = users[0]?.name ?? null;

  // `prescribed_by` is uuid. Only set it if the requester has a uuid (not "system").
  const prescribedBy = /^[0-9a-f-]{36}$/i.test(String(requestedBy || '')) ? requestedBy : null;

  const order = await prisma.$queryRaw`
    INSERT INTO pharmacy_orders (
      phone, patient_id, patient_name, order_note, file_key,
      priority, status, prescribed_by, delivery_type, ordered_at, updated_at
    ) VALUES (
      ${phone}, ${patientId}, ${patientName}, ${order_note},
      ${file_key ?? null}, ${priority}, ${ORDER_STATUS.PENDING},
      ${prescribedBy}::uuid, ${resolvedDeliveryType}, NOW(), NOW()
    )
    RETURNING id, uid, phone, patient_id, patient_name, order_note, file_key,
      priority, status, prescribed_by, delivery_type, ordered_at, updated_at
  `;

  logger.info(`Pharmacy order created: ${order[0].id} for ${phone}`);
  return { ...order[0], requestedBy, requestedByRole };
};

export const getOrdersByPhone = async (phone, filters) => {
  const { status, limit, offset } = filters;
  const safeLimit = Math.max(1, parseInt(limit) || 50);
  const safeOffset = Math.max(0, parseInt(offset) || 0);

  const where = { phone };
  if (status) where.status = status;

  const rows = await prisma.pharmacy_orders.findMany({
    where,
    select: ORDER_LIST_SELECT,
    orderBy: { ordered_at: 'desc' },
    take: safeLimit,
    skip: safeOffset,
  });

  return { orders: rows, filters: { status, limit: safeLimit, offset: safeOffset } };
};

export const getOrdersByUID = async (uid, filters) => {
  const user = await prisma.users.findUnique({
    where: { uid },
    select: { phone: true },
  });
  if (!user) return { orders: [], filters };
  return getOrdersByPhone(user.phone, filters);
};

export const updateOrderStatus = async (orderId, status, notes, updatedBy, updatedByRole) => {
  const validStatuses = Object.values(ORDER_STATUS);
  if (!validStatuses.includes(status)) throw new Error('INVALID_STATUS');

  return prisma.$transaction(async (tx) => {
    const current = await tx.$queryRaw`
      SELECT id, status FROM pharmacy_orders WHERE id = ${parseInt(orderId)} FOR UPDATE
    `;

    if (current.length === 0) return null;

    const currentStatus = current[0].status;
    const allowed = ORDER_STATUS_TRANSITIONS[currentStatus] || [];
    if (!allowed.includes(status)) throw new Error('INVALID_TRANSITION');

    // `dispensed_by` is uuid; only set when a uuid is supplied.
    const dispensedByUuid = /^[0-9a-f-]{36}$/i.test(String(updatedBy || '')) ? updatedBy : null;

    const updated = await tx.$queryRaw`
      UPDATE pharmacy_orders
      SET status             = ${status},
          confirmation_notes = COALESCE(${notes ?? null}, confirmation_notes),
          dispensed_by       = COALESCE(${dispensedByUuid}::uuid, dispensed_by),
          updated_at         = NOW()
      WHERE id = ${parseInt(orderId)}
      RETURNING id, uid, phone, patient_id, patient_name, order_note, file_key,
        priority, status, confirmation_notes, prescribed_by, dispensed_by,
        ordered_at, updated_at
    `;

    // History trail — changed_by is int (users.id). Accept only numeric updatedBy here.
    const changedByInt = Number.isFinite(Number(updatedBy)) ? parseInt(updatedBy) : null;
    await tx.$queryRaw`
      INSERT INTO pharmacy_order_history (order_id, from_status, to_status, changed_by, changed_by_role, notes)
      VALUES (${parseInt(orderId)}, ${currentStatus}, ${status}, ${changedByInt}, ${updatedByRole ?? null}, ${notes ?? null})
    `;

    logger.info(`Order ${orderId} status updated from ${currentStatus} to ${status} by ${updatedBy}`);
    return { order: updated[0], previousStatus: currentStatus, updatedBy, updatedByRole };
  });
};

// TO_CHAR(po.ordered_at, 'DD-MM-YYYY HH24:MI') preserved from the old SQL —
// expressed in JS after the findMany since Prisma has no first-class
// date-format. Kept in one place so callers don't repeat the pattern.
function formatOrderedAt(d) {
  if (!d) return null;
  const pad = (n) => String(n).padStart(2, '0');
  return `${pad(d.getDate())}-${pad(d.getMonth() + 1)}-${d.getFullYear()} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

export const getAllOrders = async (filters) => {
  const { status, limit, offset, urgent_only } = filters;
  const safeLimit = Math.max(1, parseInt(limit) || 100);
  const safeOffset = Math.max(0, parseInt(offset) || 0);

  // The four `if / else if / else` raw variants collapse to one findMany —
  // all three filter combinations are just different `where` shapes now.
  // Relation rename drift on users (e.g. `name` → `full_name`) fails here
  // at query-construction instead of a production 500.
  const where = {};
  if (status) where.status = status;
  if (urgent_only) where.priority = 'urgent';

  const rows = await prisma.pharmacy_orders.findMany({
    where,
    select: {
      ...ORDER_LIST_SELECT,
      // The old raw SQL joined `po.phone = u.phone` to surface
      // `lookup_patient_name`. Switching to the typed patient_id relation
      // — every row with a non-null patient_id gets the same result the
      // phone-join produced (users.phone is unique), and a null
      // patient_id produces null like the old LEFT JOIN miss.
      [REL_PATIENT]: { select: { name: true } },
    },
    orderBy: { ordered_at: 'desc' },
    take: safeLimit,
    skip: safeOffset,
  });

  const orders = rows.map((r) => {
    const patient = r[REL_PATIENT] ?? null;
    const flat = { ...r };
    delete flat[REL_PATIENT];
    flat.lookup_patient_name = patient?.name ?? null;
    flat.ordered_at_formatted = formatOrderedAt(r.ordered_at);
    return flat;
  });

  return { orders, count: orders.length, filters };
};
