import { envelope } from './_helpers.mjs';

const uuid = { type: 'string', format: 'uuid' };
const nullableUuid = { ...uuid, nullable: true };
const dateTime = { type: 'string', format: 'date-time' };
const nullableDateTime = { ...dateTime, nullable: true };
const sha256 = { type: 'string', pattern: '^[0-9a-f]{64}$' };
const expectedVersion = { type: 'integer', minimum: 1 };
const bigintPositive = {
  oneOf: [
    { type: 'integer', minimum: 1, maximum: Number.MAX_SAFE_INTEGER },
    { type: 'string', pattern: '^[1-9][0-9]*$' },
  ],
};
const bigintNonNegative = {
  oneOf: [
    { type: 'integer', minimum: 0, maximum: Number.MAX_SAFE_INTEGER },
    { type: 'string', pattern: '^(0|[1-9][0-9]*)$' },
  ],
};

const commonPaperProperties = {
  expected_version: expectedVersion,
  occurred_at: dateTime,
  original_actor_uid: uuid,
  original_actor_role: { type: 'string', minLength: 1, maxLength: 80 },
  patient_uid: uuid,
  encounter_id: nullableUuid,
  evidence_hash: sha256,
};
const commonPaperRequired = [
  'expected_version', 'occurred_at', 'original_actor_uid',
  'original_actor_role', 'patient_uid', 'encounter_id', 'evidence_hash',
];

export const schemas = {
  ClinicalContinuityIncidentState: {
    type: 'string',
    enum: ['declared', 'restored', 'reconciling', 'closed'],
  },
  ClinicalContinuityQueueType: {
    type: 'string',
    enum: ['needs_review', 'identity', 'interface'],
  },
  ClinicalContinuityPaperDisposition: {
    type: 'string',
    enum: ['unentered', 'claimed', 'applied', 'needs_review', 'excluded', 'voided', 'lost_revoked'],
  },
  ClinicalContinuityIncident: {
    type: 'object',
    additionalProperties: true,
    required: ['id', 'facility_id', 'commander_uid', 'lifecycle_state', 'version', 'declared_at'],
    properties: {
      id: uuid,
      facility_id: { type: 'integer', minimum: 1 },
      packet_id: uuid,
      canonical_incident_id: nullableUuid,
      commander_uid: uuid,
      commander_role: { type: 'string' },
      lifecycle_state: { $ref: '#/components/schemas/ClinicalContinuityIncidentState' },
      version: expectedVersion,
      declared_at: dateTime,
      restored_at: nullableDateTime,
      reconciliation_started_at: nullableDateTime,
      closed_at: nullableDateTime,
      closure_snapshot_hash: { ...sha256, nullable: true },
    },
  },
  ClinicalContinuityIncidentPacket: {
    type: 'object',
    additionalProperties: true,
    required: ['id', 'facility_id', 'reserved_incident_id', 'range_prefix', 'range_first', 'range_last', 'status', 'valid_from', 'valid_until'],
    properties: {
      id: uuid,
      facility_id: { type: 'integer', minimum: 1 },
      reserved_incident_id: uuid,
      range_prefix: { type: 'string' },
      range_first: bigintPositive,
      range_last: bigintPositive,
      status: { type: 'string', enum: ['unused', 'used', 'revoked', 'expired'] },
      valid_from: dateTime,
      valid_until: dateTime,
      revoked_at: nullableDateTime,
      revocation_reason: { type: 'string', nullable: true },
    },
  },
  ClinicalContinuityPaperRange: {
    type: 'object',
    additionalProperties: true,
    required: ['id', 'incident_id', 'range_prefix', 'range_first', 'range_last', 'status', 'version'],
    properties: {
      id: uuid,
      incident_id: uuid,
      range_prefix: { type: 'string' },
      range_first: bigintPositive,
      range_last: bigintPositive,
      status: { type: 'string', enum: ['allocated', 'in_use', 'accounted', 'lost', 'revoked', 'exhausted'] },
      last_accounted_number: { ...bigintPositive, nullable: true },
      reason: { type: 'string', nullable: true },
      version: expectedVersion,
    },
  },
  ClinicalContinuityPaperItem: {
    type: 'object',
    additionalProperties: true,
    required: ['id', 'incident_id', 'paper_item_id', 'item_kind', 'evidence_hash', 'reconciliation_disposition', 'version'],
    properties: {
      id: uuid,
      incident_id: uuid,
      paper_item_id: { type: 'string', minLength: 1, maxLength: 128 },
      item_kind: { type: 'string', enum: ['temporary_identity', 'medication_administration', 'specimen_collection', 'transfusion_verification', 'other'] },
      action_id: { type: 'string', nullable: true },
      patient_uid: nullableUuid,
      temporary_identity_id: nullableUuid,
      occurred_at: nullableDateTime,
      recorded_at: nullableDateTime,
      reviewed_at: nullableDateTime,
      evidence_hash: sha256,
      payload_fingerprint: { ...sha256, nullable: true },
      reconciliation_disposition: { $ref: '#/components/schemas/ClinicalContinuityPaperDisposition' },
      version: expectedVersion,
    },
  },
  ClinicalContinuityReconciliationItem: {
    type: 'object',
    additionalProperties: true,
    required: ['id', 'incident_id', 'queue_type', 'disposition', 'reason_code', 'safety_critical', 'owner_principal', 'version'],
    properties: {
      id: uuid,
      incident_id: uuid,
      queue_type: { $ref: '#/components/schemas/ClinicalContinuityQueueType' },
      disposition: { type: 'string', enum: ['open', 'in_progress', 'resolved', 'excluded', 'superseded'] },
      reason_code: { type: 'string' },
      paper_item_row_id: nullableUuid,
      temporary_identity_id: nullableUuid,
      patient_uid: nullableUuid,
      safety_critical: { type: 'boolean' },
      owner_principal: { type: 'string' },
      assigned_to_uid: nullableUuid,
      task_id: { type: 'integer', minimum: 1, nullable: true },
      task_status: { type: 'string', nullable: true },
      task_due_at: nullableDateTime,
      sla_completion_semantics: { type: 'string', enum: ['none', 'acknowledgement', 'domain_evidence'], nullable: true },
      version: expectedVersion,
    },
  },
  ClinicalContinuityTemporaryIdentity: {
    type: 'object',
    additionalProperties: true,
    required: ['id', 'incident_id', 'paper_item_id', 'display_identifier', 'identity_status', 'safety_critical', 'version'],
    properties: {
      id: uuid,
      incident_id: uuid,
      paper_item_id: { type: 'string' },
      display_identifier: { type: 'string' },
      identity_status: { type: 'string', enum: ['unresolved', 'proposed', 'matched', 'retained_temporary'] },
      matched_patient_uid: nullableUuid,
      merge_request_id: { type: 'integer', minimum: 1, nullable: true },
      safety_critical: { type: 'boolean' },
      version: expectedVersion,
    },
  },
  ClinicalContinuityDeviceOffset: {
    type: 'object',
    additionalProperties: true,
    required: ['id', 'incident_id', 'device_id', 'required_high_water_mark', 'disposition', 'owner_principal', 'version'],
    properties: {
      id: uuid,
      incident_id: uuid,
      device_id: uuid,
      required_high_water_mark: bigintNonNegative,
      observed_high_water_mark: { ...bigintNonNegative, nullable: true },
      disposition: { type: 'string', enum: ['pending', 'reconciled', 'lost_assigned', 'not_applicable'] },
      assigned_to_uid: nullableUuid,
      owner_principal: { type: 'string' },
      version: expectedVersion,
    },
  },
  ClinicalContinuityInterfaceRequirement: {
    type: 'object',
    additionalProperties: true,
    required: ['id', 'incident_id', 'interface_family', 'direction', 'source_partition', 'disposition', 'owner_principal', 'version'],
    properties: {
      id: uuid,
      incident_id: uuid,
      offset_id: nullableUuid,
      interface_family: { type: 'string' },
      direction: { type: 'string' },
      source_partition: { type: 'string' },
      required_generation: { type: 'integer', minimum: 0, nullable: true },
      required_high_water_position: { ...bigintNonNegative, nullable: true },
      required_high_water_token: { type: 'string', nullable: true },
      observed_generation: { type: 'integer', minimum: 0, nullable: true },
      observed_high_water_position: { ...bigintNonNegative, nullable: true },
      observed_high_water_token: { type: 'string', nullable: true },
      observed_recovery_state: { type: 'string', nullable: true },
      disposition: { type: 'string', enum: ['pending', 'reconciled', 'not_applicable', 'assigned_gap'] },
      owner_principal: { type: 'string' },
      assigned_to_uid: nullableUuid,
      version: expectedVersion,
    },
  },
  ClinicalContinuityWorkbench: {
    type: 'object',
    additionalProperties: false,
    required: ['incidents', 'packets', 'paper_ranges', 'paper_items', 'reconciliation_items', 'temporary_identities', 'device_offsets', 'interfaces'],
    properties: {
      incidents: { type: 'array', items: { $ref: '#/components/schemas/ClinicalContinuityIncident' } },
      packets: { type: 'array', items: { $ref: '#/components/schemas/ClinicalContinuityIncidentPacket' } },
      paper_ranges: { type: 'array', items: { $ref: '#/components/schemas/ClinicalContinuityPaperRange' } },
      paper_items: { type: 'array', items: { $ref: '#/components/schemas/ClinicalContinuityPaperItem' } },
      reconciliation_items: { type: 'array', items: { $ref: '#/components/schemas/ClinicalContinuityReconciliationItem' } },
      temporary_identities: { type: 'array', items: { $ref: '#/components/schemas/ClinicalContinuityTemporaryIdentity' } },
      device_offsets: { type: 'array', items: { $ref: '#/components/schemas/ClinicalContinuityDeviceOffset' } },
      interfaces: { type: 'array', items: { $ref: '#/components/schemas/ClinicalContinuityInterfaceRequirement' } },
    },
  },
  ClinicalContinuityWorkbenchResponse: envelope('ClinicalContinuityWorkbench'),
  ClinicalContinuityDeclareRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['expected_version', 'packet_id', 'reserved_incident_id', 'signed_canonical_hash', 'signature', 'occurred_at'],
    properties: {
      expected_version: { type: 'integer', minimum: 0 },
      packet_id: uuid,
      reserved_incident_id: uuid,
      signed_canonical_hash: sha256,
      signature: { type: 'string', minLength: 1 },
      occurred_at: dateTime,
    },
  },
  ClinicalContinuityRegisterPaperItemRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['expected_version', 'item_kind', 'evidence_hash'],
    properties: {
      expected_version: expectedVersion,
      item_kind: { type: 'string', enum: ['temporary_identity', 'medication_administration', 'specimen_collection', 'transfusion_verification', 'other'] },
      action_id: { type: 'string', enum: ['mar.administration.backfill', 'lab.specimen_collection.backfill', 'blood.transfusion_verification.backfill'], nullable: true },
      original_actor_uid: nullableUuid,
      original_actor_role: { type: 'string', nullable: true, maxLength: 80 },
      occurred_at: nullableDateTime,
      patient_uid: nullableUuid,
      temporary_identity_id: nullableUuid,
      encounter_id: nullableUuid,
      evidence_hash: sha256,
    },
  },
  ClinicalContinuityMarBackfillRequest: {
    type: 'object', additionalProperties: false,
    required: [...commonPaperRequired, 'medication_administration_id'],
    properties: { ...commonPaperProperties, medication_administration_id: { type: 'integer', minimum: 1 }, notes: { type: 'string', nullable: true, maxLength: 2000 } },
  },
  ClinicalContinuityLabBackfillRequest: {
    type: 'object', additionalProperties: false,
    required: [...commonPaperRequired, 'investigation_id', 'specimen_barcode'],
    properties: { ...commonPaperProperties, investigation_id: { type: 'integer', minimum: 1 }, specimen_barcode: { type: 'string', minLength: 1, maxLength: 100 }, collection_notes: { type: 'string', nullable: true, maxLength: 2000 } },
  },
  ClinicalContinuityTransfusionBackfillRequest: {
    type: 'object', additionalProperties: false,
    required: [...commonPaperRequired, 'blood_request_id', 'blood_unit_id', 'first_verifier_uid', 'second_verifier_uid', 'scanned_unit_number', 'unit_match', 'patient_match', 'group_compatible', 'expiry_ok'],
    properties: {
      ...commonPaperProperties,
      blood_request_id: { type: 'integer', minimum: 1 },
      blood_unit_id: { type: 'integer', minimum: 1 },
      first_verifier_uid: uuid,
      second_verifier_uid: uuid,
      scanned_unit_number: { type: 'string', minLength: 1, maxLength: 60 },
      unit_match: { type: 'boolean' }, patient_match: { type: 'boolean' },
      group_compatible: { type: 'boolean' }, expiry_ok: { type: 'boolean' },
      override_reason: { type: 'string', nullable: true, maxLength: 2000 },
    },
  },
  ClinicalContinuityCommandResult: {
    type: 'object',
    additionalProperties: true,
    properties: {
      disposition: { type: 'string', enum: ['declared', 'split_brain_needs_review', 'registered', 'applied', 'needs_review', 'exact_duplicate'] },
      client_event_id: nullableUuid,
      outcome_code: { type: 'string', nullable: true },
      replayed: { type: 'boolean', nullable: true },
      incident: { $ref: '#/components/schemas/ClinicalContinuityIncident' },
      paper_item: { $ref: '#/components/schemas/ClinicalContinuityPaperItem' },
    },
  },
  ClinicalContinuityCommandResponse: envelope('ClinicalContinuityCommandResult'),
  ClinicalContinuityDecisionRequest: {
    type: 'object', additionalProperties: false,
    required: ['expected_version', 'decision', 'reason_code'],
    properties: {
      expected_version: expectedVersion,
      decision: { type: 'string', enum: ['accept', 'exclude', 'assign', 'handoff', 'reopen', 'supersede'] },
      reason_code: { type: 'string', minLength: 1, maxLength: 120 },
    },
  },
  ClinicalContinuityIncidentTransitionRequest: {
    type: 'object', additionalProperties: false,
    required: ['expected_version', 'next_state'],
    properties: {
      expected_version: expectedVersion,
      next_state: { $ref: '#/components/schemas/ClinicalContinuityIncidentState' },
    },
  },
  ClinicalContinuityRangeDispositionRequest: {
    type: 'object', additionalProperties: false,
    required: ['expected_version', 'disposition', 'reason_code'],
    properties: {
      expected_version: expectedVersion,
      disposition: { type: 'string', enum: ['in_use', 'accounted', 'lost', 'revoked', 'exhausted'] },
      reason_code: { type: 'string', minLength: 1, maxLength: 120 },
      last_accounted_number: { type: 'integer', minimum: 1, nullable: true },
    },
  },
  ClinicalContinuityIncidentAliasRequest: {
    type: 'object', additionalProperties: false,
    required: ['observed_incident_id', 'canonical_incident_id', 'expected_version', 'reason_code'],
    properties: {
      observed_incident_id: uuid,
      canonical_incident_id: uuid,
      expected_version: expectedVersion,
      reason_code: { type: 'string', minLength: 1, maxLength: 120 },
      supersedes_alias_id: nullableUuid,
    },
  },
  ClinicalContinuityDeviceOffsetRequest: {
    type: 'object', additionalProperties: false,
    required: ['expected_version', 'required_high_water_mark', 'disposition'],
    properties: {
      expected_version: { type: 'integer', minimum: 0 },
      required_high_water_mark: { type: 'integer', minimum: 0 },
      observed_high_water_mark: { type: 'integer', minimum: 0, nullable: true },
      disposition: { type: 'string', enum: ['pending', 'reconciled', 'lost_assigned', 'not_applicable'] },
    },
  },
  ClinicalContinuityInterfaceRequirementRequest: {
    type: 'object', additionalProperties: false,
    required: ['expected_version', 'interface_family', 'direction', 'source_partition', 'disposition'],
    properties: {
      expected_version: { type: 'integer', minimum: 0 },
      offset_id: nullableUuid,
      interface_family: { type: 'string', minLength: 1, maxLength: 8 },
      direction: { type: 'string', minLength: 1, maxLength: 16 },
      source_partition: { type: 'string', minLength: 1, maxLength: 160 },
      required_generation: { type: 'integer', minimum: 0, nullable: true },
      required_high_water_position: { type: 'integer', minimum: 0, nullable: true },
      required_high_water_token: { type: 'string', maxLength: 255, nullable: true },
      disposition: { type: 'string', enum: ['pending', 'reconciled', 'not_applicable', 'assigned_gap'] },
    },
  },
  ClinicalContinuityIdentityMatchRequest: {
    type: 'object', additionalProperties: false,
    required: ['packet_id', 'paper_item_row_id', 'temporary_identity_id', 'target_patient_uid'],
    properties: {
      packet_id: uuid,
      paper_item_row_id: uuid,
      temporary_identity_id: uuid,
      target_patient_uid: uuid,
      note: { type: 'string', maxLength: 2000, nullable: true },
    },
  },
  ClinicalContinuityIdentityApprovalRequest: {
    type: 'object', additionalProperties: false,
    properties: { note: { type: 'string', maxLength: 2000, nullable: true } },
  },
  ClinicalContinuityAdminCommandResult: {
    type: 'object', additionalProperties: true,
  },
  ClinicalContinuityAdminCommandResponse: envelope('ClinicalContinuityAdminCommandResult'),
  ClinicalContinuityClosure: {
    type: 'object', additionalProperties: true,
    required: ['eligible', 'incident', 'predicate_snapshot_hash', 'blockers', 'attestations'],
    properties: {
      eligible: { type: 'boolean' },
      incident: { $ref: '#/components/schemas/ClinicalContinuityIncident' },
      predicate_snapshot_hash: sha256,
      blockers: { type: 'array', items: { type: 'object', additionalProperties: true, required: ['code'], properties: { code: { type: 'string' } } } },
      attestations: { type: 'array', items: { type: 'object', additionalProperties: true } },
    },
  },
  ClinicalContinuityClosureResponse: envelope('ClinicalContinuityClosure'),
  ClinicalContinuityAttestationRequest: {
    type: 'object', additionalProperties: false,
    required: ['expected_version', 'attestation_kind'],
    properties: { expected_version: expectedVersion, attestation_kind: { type: 'string', enum: ['operational', 'clinical'] } },
  },
  ClinicalContinuityCloseRequest: {
    type: 'object', additionalProperties: false,
    required: ['expected_version'], properties: { expected_version: expectedVersion },
  },
};

const base = '/api/v1/downtime/reconciliation';
const paperParams = { incidentId: uuid, paperItemId: { type: 'string', minLength: 1, maxLength: 128 } };

export const operations = {
  [`GET ${base}/workbench`]: { response: 'ClinicalContinuityWorkbenchResponse' },
  [`POST ${base}/incidents/declare`]: { request: 'ClinicalContinuityDeclareRequest', response: 'ClinicalContinuityCommandResponse', responseStatus: 201 },
  [`POST ${base}/incidents/import`]: { request: 'ClinicalContinuityDeclareRequest', response: 'ClinicalContinuityCommandResponse', responseStatus: 201 },
  [`PATCH ${base}/incidents/{incidentId}/state`]: { pathParameters: { incidentId: uuid }, request: 'ClinicalContinuityIncidentTransitionRequest', response: 'ClinicalContinuityAdminCommandResponse' },
  [`POST ${base}/incidents/{incidentId}/range-disposition`]: { pathParameters: { incidentId: uuid }, request: 'ClinicalContinuityRangeDispositionRequest', response: 'ClinicalContinuityAdminCommandResponse' },
  [`POST ${base}/incident-aliases`]: { request: 'ClinicalContinuityIncidentAliasRequest', response: 'ClinicalContinuityAdminCommandResponse', responseStatus: 201 },
  [`POST ${base}/incidents/{incidentId}/paper-items/{paperItemId}`]: { pathParameters: paperParams, request: 'ClinicalContinuityRegisterPaperItemRequest', response: 'ClinicalContinuityCommandResponse', responseStatus: 201 },
  [`POST ${base}/incidents/{incidentId}/paper-items/{paperItemId}/mar-administration`]: { pathParameters: paperParams, request: 'ClinicalContinuityMarBackfillRequest', response: 'ClinicalContinuityCommandResponse', responseStatus: 201 },
  [`POST ${base}/incidents/{incidentId}/paper-items/{paperItemId}/lab-specimen-collection`]: { pathParameters: paperParams, request: 'ClinicalContinuityLabBackfillRequest', response: 'ClinicalContinuityCommandResponse', responseStatus: 201 },
  [`POST ${base}/incidents/{incidentId}/paper-items/{paperItemId}/blood-transfusion-verification`]: { pathParameters: paperParams, request: 'ClinicalContinuityTransfusionBackfillRequest', response: 'ClinicalContinuityCommandResponse', responseStatus: 201 },
  [`POST ${base}/reconciliation-items/{itemId}/decision`]: { pathParameters: { itemId: uuid }, request: 'ClinicalContinuityDecisionRequest', response: 'ClinicalContinuityCommandResponse' },
  [`PUT ${base}/incidents/{incidentId}/devices/{deviceId}/offset`]: { pathParameters: { incidentId: uuid, deviceId: uuid }, request: 'ClinicalContinuityDeviceOffsetRequest', response: 'ClinicalContinuityAdminCommandResponse' },
  [`PUT ${base}/incidents/{incidentId}/interfaces/requirement`]: { pathParameters: { incidentId: uuid }, request: 'ClinicalContinuityInterfaceRequirementRequest', response: 'ClinicalContinuityAdminCommandResponse' },
  [`POST ${base}/incidents/{incidentId}/identity-matches`]: { pathParameters: { incidentId: uuid }, request: 'ClinicalContinuityIdentityMatchRequest', response: 'ClinicalContinuityAdminCommandResponse', responseStatus: 201 },
  [`POST ${base}/identity-matches/{mergeId}/approve`]: { pathParameters: { mergeId: { type: 'integer', minimum: 1 } }, request: 'ClinicalContinuityIdentityApprovalRequest', response: 'ClinicalContinuityAdminCommandResponse' },
  [`POST ${base}/identity-matches/{mergeId}/execute`]: { pathParameters: { mergeId: { type: 'integer', minimum: 1 } }, response: 'ClinicalContinuityAdminCommandResponse' },
  [`GET ${base}/incidents/{incidentId}/closure`]: { pathParameters: { incidentId: uuid }, response: 'ClinicalContinuityClosureResponse' },
  [`POST ${base}/incidents/{incidentId}/closure/attestations`]: { pathParameters: { incidentId: uuid }, request: 'ClinicalContinuityAttestationRequest', response: 'ClinicalContinuityCommandResponse', responseStatus: 201 },
  [`POST ${base}/incidents/{incidentId}/closure/close`]: { pathParameters: { incidentId: uuid }, request: 'ClinicalContinuityCloseRequest', response: 'ClinicalContinuityCommandResponse' },
};
