// apps/backend/scripts/openapi/schemas/money.mjs
// Typed request/response payload schemas for the money/billing surface.
// Populated per sub-surface in Phase 5 tasks T3–T8.
import { envelope, listEnvelope } from './_helpers.mjs';

// V2 money JSON type. V2 uses Decimal(12,2) in rupees, which Prisma serializes
// to a JSON STRING (verified by the V2 contract deep test, same as V1).
const MT = 'string';

export const schemas = {
  // ---- GL ledger reports (read-only; ledgerReportsService.js) ----
  TrialBalanceAccount: {
    type: 'object', additionalProperties: false,
    required: ['code', 'type', 'balancePaise', 'balance'],
    properties: {
      code: { type: 'string', example: 'PATIENT_AR' },
      type: { type: 'string', enum: ['ASSET', 'LIABILITY', 'REVENUE', 'EQUITY', 'CONTRA'] },
      balancePaise: { type: 'integer', example: 100000 },
      balance: { type: 'string', example: '1000.00' },
    },
  },
  TrialBalance: {
    type: 'object', additionalProperties: false,
    required: ['accounts', 'signedTotalPaise', 'balanced'],
    properties: {
      accounts: { type: 'array', items: { $ref: '#/components/schemas/TrialBalanceAccount' } },
      signedTotalPaise: { type: 'integer', example: 0 },
      balanced: { type: 'boolean', example: true },
    },
  },
  TrialBalanceResponse: envelope('TrialBalance'),

  AgingBucket: {
    type: 'object', additionalProperties: false,
    required: ['bucket', 'invoiceCount', 'totalPaise', 'total'],
    properties: {
      bucket: { type: 'string', enum: ['0-30', '31-60', '61-90', '90+'] },
      invoiceCount: { type: 'integer', example: 3 },
      totalPaise: { type: 'integer', example: 250000 },
      total: { type: 'string', example: '2500.00' },
    },
  },
  AgingReport: {
    type: 'object', additionalProperties: false,
    required: ['buckets', 'grandTotalPaise', 'grandTotal'],
    properties: {
      buckets: { type: 'array', items: { $ref: '#/components/schemas/AgingBucket' } },
      grandTotalPaise: { type: 'integer', example: 250000 },
      grandTotal: { type: 'string', example: '2500.00' },
    },
  },
  AgingReportResponse: envelope('AgingReport'),

  DrawerPosition: {
    type: 'object', additionalProperties: false,
    required: ['drawerSessionId', 'netPaise', 'net'],
    properties: {
      drawerSessionId: { type: 'integer', example: 12 },
      netPaise: { type: 'integer', example: 50000 },
      net: { type: 'string', example: '500.00' },
    },
  },
  CashPosition: {
    type: 'object', additionalProperties: false,
    required: ['cashTotalPaise', 'cashTotal', 'bankTotalPaise', 'bankTotal', 'byDrawer'],
    properties: {
      cashTotalPaise: { type: 'integer', example: 50000 },
      cashTotal: { type: 'string', example: '500.00' },
      bankTotalPaise: { type: 'integer', example: 0 },
      bankTotal: { type: 'string', example: '0.00' },
      byDrawer: { type: 'array', items: { $ref: '#/components/schemas/DrawerPosition' } },
    },
  },
  CashPositionResponse: envelope('CashPosition'),

  DailyCollectionDay: {
    type: 'object', additionalProperties: false,
    required: ['day', 'collectedPaise', 'collected'],
    properties: {
      day: { type: 'string', example: '2026-06-24' },
      collectedPaise: { type: 'integer', example: 75000 },
      collected: { type: 'string', example: '750.00' },
    },
  },
  DailyCollection: {
    type: 'object', additionalProperties: false,
    required: ['days', 'totalPaise', 'total'],
    properties: {
      days: { type: 'array', items: { $ref: '#/components/schemas/DailyCollectionDay' } },
      totalPaise: { type: 'integer', example: 75000 },
      total: { type: 'string', example: '750.00' },
    },
  },
  DailyCollectionResponse: envelope('DailyCollection'),

  // ---- V1 billing (billingService.js) — money Decimals serialize as strings ----
  Invoice: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_number', 'patient_uid', 'type', 'items', 'subtotal', 'tax_amount',
      'discount_amount', 'total_amount', 'paid_amount', 'payment_status', 'issued_at', 'created_at', 'updated_at', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string', example: 'INV-202606-0001' },
      patient_uid: { type: 'string', format: 'uuid' },
      appointment_id: { type: 'integer', nullable: true },
      type: { type: 'string', enum: ['consultation', 'investigation', 'pharmacy', 'procedure', 'room_charge'] },
      items: { type: 'array', items: { type: 'object', additionalProperties: true } },
      subtotal: { type: 'string', example: '1000.00' },
      tax_amount: { type: 'string', example: '180.00' },
      discount_amount: { type: 'string', example: '0.00' },
      total_amount: { type: 'string', example: '1180.00' },
      paid_amount: { type: 'string', example: '0.00' },
      payment_status: { type: 'string', enum: ['pending', 'partial', 'paid', 'refunded', 'written_off'] },
      payment_method: { type: 'string', nullable: true, enum: ['cash', 'card', 'upi', 'insurance', 'cheque'] },
      insurance_claim_id: { type: 'integer', nullable: true },
      notes: { type: 'string', nullable: true },
      issued_by: { type: 'string', format: 'uuid', nullable: true },
      issued_at: { type: 'string', format: 'date-time' },
      paid_at: { type: 'string', format: 'date-time', nullable: true },
      due_date: { type: 'string', format: 'date-time', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
      tenant_id: { type: 'string', format: 'uuid' },
    },
  },
  InvoiceResponse: envelope('Invoice'),

  PaymentTransaction: {
    type: 'object', additionalProperties: false,
    required: ['id', 'amount', 'payment_method', 'status', 'created_at', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_id: { type: 'integer', nullable: true },
      amount: { type: 'string', example: '500.00' },
      payment_method: { type: 'string' },
      transaction_ref: { type: 'string', nullable: true },
      status: { type: 'string', example: 'completed' },
      processed_by: { type: 'string', format: 'uuid', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      tenant_id: { type: 'string', format: 'uuid' },
    },
  },
  InsuranceClaimSummary: {
    type: 'object', additionalProperties: false,
    required: ['id', 'claim_number', 'insurance_provider', 'policy_number', 'claim_amount', 'status', 'submitted_at'],
    properties: {
      id: { type: 'integer' },
      claim_number: { type: 'string', example: 'CLM-202606-0001' },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string' },
      claim_amount: { type: 'string', example: '5000.00' },
      approved_amount: { type: 'string', nullable: true },
      status: { type: 'string' },
      submitted_at: { type: 'string', format: 'date-time' },
      reviewed_at: { type: 'string', format: 'date-time', nullable: true },
    },
  },
  InvoiceDetail: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_number', 'patient_uid', 'type', 'total_amount', 'payment_status', 'payment_transactions'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      appointment_id: { type: 'integer', nullable: true },
      type: { type: 'string' },
      items: { type: 'array', items: { type: 'object', additionalProperties: true } },
      subtotal: { type: 'string' },
      tax_amount: { type: 'string' },
      discount_amount: { type: 'string' },
      total_amount: { type: 'string' },
      paid_amount: { type: 'string' },
      payment_status: { type: 'string' },
      payment_method: { type: 'string', nullable: true },
      insurance_claim_id: { type: 'integer', nullable: true },
      notes: { type: 'string', nullable: true },
      issued_by: { type: 'string', format: 'uuid', nullable: true },
      issued_at: { type: 'string', format: 'date-time' },
      paid_at: { type: 'string', format: 'date-time', nullable: true },
      due_date: { type: 'string', format: 'date-time', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
      tenant_id: { type: 'string', format: 'uuid' },
      payment_transactions: { type: 'array', items: { $ref: '#/components/schemas/PaymentTransaction' } },
      insurance_claim: { nullable: true, allOf: [{ $ref: '#/components/schemas/InsuranceClaimSummary' }] },
    },
  },
  InvoiceDetailResponse: envelope('InvoiceDetail'),

  PaymentInvoice: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_number', 'patient_uid', 'total_amount', 'paid_amount', 'payment_status'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      total_amount: { type: 'string' },
      paid_amount: { type: 'string' },
      payment_status: { type: 'string', enum: ['pending', 'partial', 'paid', 'refunded', 'written_off'] },
      payment_method: { type: 'string', nullable: true },
      paid_at: { type: 'string', format: 'date-time', nullable: true },
    },
  },
  PaymentResult: {
    type: 'object', additionalProperties: false,
    required: ['invoice', 'transaction'],
    properties: {
      invoice: { $ref: '#/components/schemas/PaymentInvoice' },
      transaction: { $ref: '#/components/schemas/PaymentTransaction' },
    },
  },
  PaymentResultResponse: envelope('PaymentResult'),

  InvoiceListItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_number', 'type', 'subtotal', 'tax_amount', 'discount_amount',
      'total_amount', 'paid_amount', 'payment_status', 'issued_at', 'created_at'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string' },
      type: { type: 'string' },
      subtotal: { type: 'string' },
      tax_amount: { type: 'string' },
      discount_amount: { type: 'string' },
      total_amount: { type: 'string' },
      paid_amount: { type: 'string' },
      payment_status: { type: 'string' },
      payment_method: { type: 'string', nullable: true },
      issued_at: { type: 'string', format: 'date-time' },
      due_date: { type: 'string', format: 'date-time', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
    },
  },
  PatientInvoicesResponse: listEnvelope('InvoiceListItem'),

  RevenueSummary: {
    type: 'object', additionalProperties: false,
    required: ['total_invoices', 'total_outstanding', 'paid_count', 'pending_count', 'partial_count'],
    properties: {
      total_invoices: { type: 'integer' },
      total_billed: { type: 'string', nullable: true },
      total_collected: { type: 'string', nullable: true },
      total_outstanding: { type: 'string' },
      total_discounts: { type: 'string', nullable: true },
      total_taxes: { type: 'string', nullable: true },
      paid_count: { type: 'integer' },
      pending_count: { type: 'integer' },
      partial_count: { type: 'integer' },
    },
  },
  RevenueByType: {
    type: 'object', additionalProperties: false,
    required: ['type', 'invoice_count', 'outstanding'],
    properties: {
      type: { type: 'string' },
      invoice_count: { type: 'integer' },
      total_billed: { type: 'string', nullable: true },
      total_collected: { type: 'string', nullable: true },
      outstanding: { type: 'string' },
    },
  },
  RevenueByPaymentMethod: {
    type: 'object', additionalProperties: false,
    required: ['payment_method', 'transaction_count'],
    properties: {
      payment_method: { type: 'string' },
      transaction_count: { type: 'integer' },
      total_amount: { type: 'string', nullable: true },
    },
  },
  RevenueDailyTotal: {
    type: 'object', additionalProperties: false,
    required: ['date', 'invoice_count'],
    properties: {
      date: { type: 'string', example: '2026-06-24' },
      invoice_count: { type: 'integer' },
      billed: { type: 'string', nullable: true },
      collected: { type: 'string', nullable: true },
    },
  },
  RevenueStats: {
    type: 'object', additionalProperties: false,
    required: ['summary', 'by_type', 'by_payment_method', 'daily_totals'],
    properties: {
      summary: { $ref: '#/components/schemas/RevenueSummary' },
      by_type: { type: 'array', items: { $ref: '#/components/schemas/RevenueByType' } },
      by_payment_method: { type: 'array', items: { $ref: '#/components/schemas/RevenueByPaymentMethod' } },
      daily_totals: { type: 'array', items: { $ref: '#/components/schemas/RevenueDailyTotal' } },
    },
  },
  RevenueStatsResponse: envelope('RevenueStats'),

  InsuranceClaim: {
    type: 'object', additionalProperties: false,
    required: ['id', 'claim_number', 'patient_uid', 'insurance_provider', 'policy_number',
      'claim_amount', 'status', 'submitted_at', 'created_at', 'updated_at', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      claim_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      invoice_id: { type: 'integer', nullable: true },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string' },
      claim_amount: { type: 'string' },
      approved_amount: { type: 'string', nullable: true },
      non_payable_amount: { type: 'string', nullable: true },
      disallowed_reason: { type: 'string', nullable: true },
      parent_claim_id: { type: 'integer', nullable: true },
      stage: { type: 'string', nullable: true },
      status: {
        type: 'string',
        enum: ['submitted', 'under_review', 'approved', 'partially_approved', 'rejected', 'paid', 'settled_partial', 'settled_full'],
      },
      documents: { nullable: true },
      submitted_at: { type: 'string', format: 'date-time' },
      reviewed_at: { type: 'string', format: 'date-time', nullable: true },
      rejection_reason: { type: 'string', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
      tenant_id: { type: 'string', format: 'uuid' },
    },
  },
  InsuranceClaimResponse: envelope('InsuranceClaim'),

  InsuranceClaimListItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'claim_number', 'patient_uid', 'insurance_provider', 'policy_number', 'claim_amount', 'status', 'submitted_at', 'created_at'],
    properties: {
      id: { type: 'integer' },
      claim_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      invoice_id: { type: 'integer', nullable: true },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string' },
      claim_amount: { type: 'string' },
      approved_amount: { type: 'string', nullable: true },
      status: { type: 'string' },
      submitted_at: { type: 'string', format: 'date-time' },
      reviewed_at: { type: 'string', format: 'date-time', nullable: true },
      rejection_reason: { type: 'string', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
    },
  },
  InsuranceClaimsResponse: listEnvelope('InsuranceClaimListItem'),

  // V1 billing request bodies (validator-backed → strict)
  CreateInvoiceRequest: {
    type: 'object', additionalProperties: false,
    required: ['patient_uid', 'type', 'items', 'subtotal', 'total_amount'],
    properties: {
      patient_uid: { type: 'string', format: 'uuid' },
      appointment_id: { type: 'integer' },
      type: { type: 'string', enum: ['consultation', 'investigation', 'pharmacy', 'procedure', 'room_charge'] },
      items: { type: 'array', items: { type: 'object', additionalProperties: true } },
      subtotal: { type: 'number' },
      tax_amount: { type: 'number' },
      discount_amount: { type: 'number' },
      total_amount: { type: 'number', minimum: 0 },
      payment_method: { type: 'string', enum: ['cash', 'card', 'upi', 'insurance', 'cheque'] },
      notes: { type: 'string' },
      due_date: { type: 'string', format: 'date' },
    },
  },
  RecordPaymentRequest: {
    type: 'object', additionalProperties: false,
    required: ['amount', 'payment_method'],
    properties: {
      amount: { type: 'number', minimum: 0 },
      payment_method: { type: 'string', enum: ['CASH', 'CARD', 'UPI', 'INSURANCE', 'CHEQUE'] },
      transaction_ref: { type: 'string', maxLength: 255 },
    },
  },
  SubmitClaimRequest: {
    type: 'object', additionalProperties: false,
    required: ['patient_uid', 'insurance_provider', 'policy_number', 'claim_amount'],
    properties: {
      patient_uid: { type: 'string', format: 'uuid' },
      invoice_id: { type: 'integer' },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string', maxLength: 50 },
      claim_amount: { type: 'number', minimum: 0 },
      documents: {},
    },
  },
  UpdateClaimRequest: {
    type: 'object', additionalProperties: false,
    required: ['status'],
    properties: {
      status: {
        type: 'string',
        enum: ['submitted', 'under_review', 'approved', 'partially_approved', 'rejected', 'paid', 'settled_partial', 'settled_full'],
      },
      approved_amount: { type: 'number' },
      reason: { type: 'string' },
      rejection_reason: { type: 'string' },
      documents: {},
      payment_reference: { type: 'string' },
      non_payable_amount: { type: 'number' },
      disallowed_reason: { type: 'string' },
    },
  },
  EnhancementClaimRequest: {
    type: 'object', additionalProperties: false,
    required: ['enhancement_amount'],
    properties: {
      enhancement_amount: { type: 'number', minimum: 0 },
      justification: { type: 'string' },
      clinical_justification: {},
    },
  },

  // ---- V2 billing invoices (billingV2Service.js) ----
  ServiceMaster: {
    type: 'object', additionalProperties: false,
    required: ['id', 'code', 'description', 'category', 'default_price', 'gst_rate'],
    properties: {
      id: { type: 'integer' },
      code: { type: 'string' },
      description: { type: 'string' },
      category: { type: 'string' },
      default_price: { type: MT },
      gst_rate: { type: MT },
      hsn_sac: { type: 'string', nullable: true },
      is_active: { type: 'boolean', nullable: true },
    },
  },
  ServiceMasterResponse: envelope('ServiceMaster'),
  ServicesListResponse: listEnvelope('ServiceMaster'),

  InvoiceV2: {
    type: 'object', additionalProperties: false,
    required: ['id', 'patient_uid', 'invoice_type', 'subtotal', 'cgst_amount', 'sgst_amount',
      'igst_amount', 'discount_amount', 'total_amount', 'amount_paid', 'amount_due', 'status', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string', nullable: true },
      patient_uid: { type: 'string', format: 'uuid' },
      patient_name: { type: 'string', nullable: true },
      patient_phone: { type: 'string', nullable: true },
      admission_id: { type: 'integer', nullable: true },
      doctor_uid: { type: 'string', format: 'uuid', nullable: true },
      department: { type: 'string', nullable: true },
      invoice_type: { type: 'string' },
      patient_state: { type: 'string', nullable: true },
      hospital_state: { type: 'string', nullable: true },
      subtotal: { type: MT },
      cgst_amount: { type: MT },
      sgst_amount: { type: MT },
      igst_amount: { type: MT },
      discount_amount: { type: MT },
      discount_reason: { type: 'string', nullable: true },
      discount_approved_by: { type: 'string', format: 'uuid', nullable: true },
      total_amount: { type: MT },
      amount_paid: { type: MT },
      amount_due: { type: MT },
      status: { type: 'string' },
      notes: { type: 'string', nullable: true },
      created_by: { type: 'string', format: 'uuid', nullable: true },
      issued_at: { type: 'string', format: 'date-time', nullable: true },
      voided_at: { type: 'string', format: 'date-time', nullable: true },
      voided_by: { type: 'string', format: 'uuid', nullable: true },
      void_reason: { type: 'string', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      created_at: { type: 'string', format: 'date-time', nullable: true },
      updated_at: { type: 'string', format: 'date-time', nullable: true },
    },
  },
  InvoiceV2Response: envelope('InvoiceV2'),

  TpaUtilisation: {
    type: 'object', additionalProperties: false,
    required: ['root_preauth_id', 'root_preauth_number', 'cumulative_approved', 'total_charged', 'remaining', 'utilisation_pct', 'status'],
    properties: {
      root_preauth_id: { type: 'integer' },
      root_preauth_number: { type: 'string' },
      cumulative_approved: { type: MT },
      total_charged: { type: MT },
      remaining: { type: MT },
      utilisation_pct: { type: MT },
      status: { type: 'string' },
    },
  },
  InvoiceV2ListItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'patient_uid', 'invoice_type', 'total_amount', 'amount_paid', 'amount_due', 'status', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string', nullable: true },
      patient_uid: { type: 'string', format: 'uuid' },
      patient_name: { type: 'string', nullable: true },
      invoice_type: { type: 'string' },
      total_amount: { type: MT },
      amount_paid: { type: MT },
      amount_due: { type: MT },
      status: { type: 'string' },
      admission_id: { type: 'integer', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      issued_at: { type: 'string', format: 'date-time', nullable: true },
      created_at: { type: 'string', format: 'date-time', nullable: true },
      tpa_utilisation: { nullable: true, allOf: [{ $ref: '#/components/schemas/TpaUtilisation' }] },
    },
  },
  InvoicesListResponse: listEnvelope('InvoiceV2ListItem'),

  InvoiceItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_id', 'description', 'quantity', 'unit_price', 'gst_rate',
      'line_subtotal', 'cgst_amount', 'sgst_amount', 'igst_amount', 'line_total', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_id: { type: 'integer' },
      service_code: { type: 'string', nullable: true },
      description: { type: 'string' },
      category: { type: 'string', nullable: true },
      hsn_sac: { type: 'string', nullable: true },
      quantity: { type: MT },
      unit_price: { type: MT },
      gst_rate: { type: MT },
      line_subtotal: { type: MT },
      cgst_amount: { type: MT },
      sgst_amount: { type: MT },
      igst_amount: { type: MT },
      line_total: { type: MT },
      notes: { type: 'string', nullable: true },
      created_at: { type: 'string', format: 'date-time', nullable: true },
      source_ref_type: { type: 'string', nullable: true },
      source_ref_id: { type: 'integer', nullable: true },
      tpa_decision: { type: 'string', nullable: true },
      tpa_non_payable_reason: { type: 'string', nullable: true },
      tpa_decided_at: { type: 'string', format: 'date-time', nullable: true },
      tpa_decided_by: { type: 'string', format: 'uuid', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
    },
  },
  InvoiceItemResponse: envelope('InvoiceItem'),

  InvoiceV2Payment: {
    type: 'object', additionalProperties: false,
    required: ['id', 'patient_uid', 'amount', 'mode', 'reversed', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_id: { type: 'integer', nullable: true },
      patient_uid: { type: 'string', format: 'uuid' },
      amount: { type: MT },
      mode: { type: 'string' },
      reference: { type: 'string', nullable: true },
      denominations: { nullable: true },
      collected_by: { type: 'string', format: 'uuid', nullable: true },
      collected_at: { type: 'string', format: 'date-time', nullable: true },
      shift: { type: 'string', nullable: true },
      notes: { type: 'string', nullable: true },
      reversed: { type: 'boolean' },
      reversed_at: { type: 'string', format: 'date-time', nullable: true },
      reversed_by: { type: 'string', format: 'uuid', nullable: true },
      reversal_reason: { type: 'string', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      created_at: { type: 'string', format: 'date-time', nullable: true },
    },
  },
  AdvanceSettlement: {
    type: 'object', additionalProperties: false,
    required: ['id', 'advance_id', 'invoice_id', 'amount', 'tenant_id', 'advance_mode'],
    properties: {
      id: { type: 'integer' },
      advance_id: { type: 'integer' },
      invoice_id: { type: 'integer' },
      amount: { type: MT },
      settled_by: { type: 'string', format: 'uuid', nullable: true },
      settled_at: { type: 'string', format: 'date-time', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      advance_mode: { type: 'string' },
    },
  },
  TpaPreauth: {
    type: 'object', additionalProperties: false,
    required: ['preauth_id', 'preauth_number', 'tpa_status'],
    properties: {
      preauth_id: { type: 'integer' },
      preauth_number: { type: 'string' },
      tpa_status: { type: 'string' },
      denial_reason: { type: 'string', nullable: true },
      sanctioned_amount: { type: MT, nullable: true },
      policy_id: { type: 'string', format: 'uuid', nullable: true },
    },
  },
  InvoiceV2Detail: {
    type: 'object', additionalProperties: false,
    required: ['id', 'patient_uid', 'invoice_type', 'subtotal', 'total_amount', 'amount_paid',
      'amount_due', 'status', 'tenant_id', 'items', 'payments', 'advance_settlements'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string', nullable: true },
      patient_uid: { type: 'string', format: 'uuid' },
      patient_name: { type: 'string', nullable: true },
      patient_phone: { type: 'string', nullable: true },
      admission_id: { type: 'integer', nullable: true },
      doctor_uid: { type: 'string', format: 'uuid', nullable: true },
      department: { type: 'string', nullable: true },
      invoice_type: { type: 'string' },
      patient_state: { type: 'string', nullable: true },
      hospital_state: { type: 'string', nullable: true },
      subtotal: { type: MT },
      cgst_amount: { type: MT },
      sgst_amount: { type: MT },
      igst_amount: { type: MT },
      discount_amount: { type: MT },
      discount_reason: { type: 'string', nullable: true },
      discount_approved_by: { type: 'string', format: 'uuid', nullable: true },
      total_amount: { type: MT },
      amount_paid: { type: MT },
      amount_due: { type: MT },
      status: { type: 'string' },
      notes: { type: 'string', nullable: true },
      created_by: { type: 'string', format: 'uuid', nullable: true },
      issued_at: { type: 'string', format: 'date-time', nullable: true },
      voided_at: { type: 'string', format: 'date-time', nullable: true },
      voided_by: { type: 'string', format: 'uuid', nullable: true },
      void_reason: { type: 'string', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      created_at: { type: 'string', format: 'date-time', nullable: true },
      updated_at: { type: 'string', format: 'date-time', nullable: true },
      items: { type: 'array', items: { $ref: '#/components/schemas/InvoiceItem' } },
      payments: { type: 'array', items: { $ref: '#/components/schemas/InvoiceV2Payment' } },
      advance_settlements: { type: 'array', items: { $ref: '#/components/schemas/AdvanceSettlement' } },
      tpa_utilisation: { nullable: true, allOf: [{ $ref: '#/components/schemas/TpaUtilisation' }] },
      tpa_preauth: { nullable: true, allOf: [{ $ref: '#/components/schemas/TpaPreauth' }] },
    },
  },
  InvoiceV2DetailResponse: envelope('InvoiceV2Detail'),

  // recomputeInvoiceTotals computes these in JS -> JSON numbers (not Decimal strings).
  InvoiceTotals: {
    type: 'object', additionalProperties: false,
    required: ['subtotal', 'cgst', 'sgst', 'igst', 'discount', 'total', 'paid', 'due'],
    properties: {
      subtotal: { type: 'number' },
      cgst: { type: 'number' },
      sgst: { type: 'number' },
      igst: { type: 'number' },
      discount: { type: 'number' },
      total: { type: 'number' },
      paid: { type: 'number' },
      due: { type: 'number' },
    },
  },
  InvoiceTotalsResponse: envelope('InvoiceTotals'),

  ItemizeSummary: {
    type: 'object', additionalProperties: false,
    required: ['package', 'pharmacy', 'ward_indents', 'lab', 'consults', 'theatre', 'room_upgrade', 'skipped_existing'],
    properties: {
      package: { type: 'integer' },
      pharmacy: { type: 'integer' },
      ward_indents: { type: 'integer' },
      lab: { type: 'integer' },
      consults: { type: 'integer' },
      theatre: { type: 'integer' },
      room_upgrade: { type: 'integer' },
      skipped_existing: { type: 'integer' },
    },
  },
  ItemizeResult: {
    type: 'object', additionalProperties: false,
    required: ['invoice_id', 'admission_id', 'summary'],
    properties: {
      invoice_id: { type: 'integer' },
      admission_id: { type: 'integer' },
      package_id: { type: 'integer', nullable: true },
      summary: { $ref: '#/components/schemas/ItemizeSummary' },
    },
  },
  ItemizeResultResponse: envelope('ItemizeResult'),

  TpaDecisionItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_id', 'description', 'line_total', 'tpa_decision'],
    properties: {
      id: { type: 'integer' },
      invoice_id: { type: 'integer' },
      description: { type: 'string' },
      line_total: { type: MT },
      tpa_decision: { type: 'string' },
      tpa_non_payable_reason: { type: 'string', nullable: true },
      tpa_decided_at: { type: 'string', format: 'date-time', nullable: true },
      tpa_decided_by: { type: 'string', format: 'uuid', nullable: true },
    },
  },
  TpaDecisionItemResponse: envelope('TpaDecisionItem'),

  NonPayableLine: {
    type: 'object', additionalProperties: false,
    required: ['id', 'description', 'line_total', 'tpa_decision'],
    properties: {
      id: { type: 'integer' },
      description: { type: 'string' },
      source_ref_type: { type: 'string', nullable: true },
      source_ref_id: { type: 'integer', nullable: true },
      line_total: { type: MT },
      tpa_decision: { type: 'string' },
      tpa_non_payable_reason: { type: 'string', nullable: true },
      tpa_decided_at: { type: 'string', format: 'date-time', nullable: true },
    },
  },
  NonPayableBreakdown: {
    type: 'object', additionalProperties: false,
    required: ['invoice_id', 'non_payable_total', 'line_count', 'lines'],
    properties: {
      invoice_id: { type: 'integer' },
      non_payable_total: { type: 'number' },
      line_count: { type: 'integer' },
      lines: { type: 'array', items: { $ref: '#/components/schemas/NonPayableLine' } },
    },
  },
  NonPayableBreakdownResponse: envelope('NonPayableBreakdown'),

  // V2 invoice request bodies (no validators → permissive, known fields typed)
  CreateServiceMasterRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.createServiceMaster; not validator-backed.',
    properties: {
      code: { type: 'string' },
      description: { type: 'string' },
      category: { type: 'string' },
      default_price: { type: 'number' },
      gst_rate: { type: 'number' },
      hsn_sac: { type: 'string' },
    },
  },
  UpdateServiceMasterRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.updateServiceMaster; not validator-backed.',
    properties: {
      description: { type: 'string' },
      category: { type: 'string' },
      default_price: { type: 'number' },
      gst_rate: { type: 'number' },
      hsn_sac: { type: 'string' },
      is_active: { type: 'boolean' },
    },
  },
  CreateDraftInvoiceRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.createDraftInvoice; not validator-backed.',
    properties: {
      patient_uid: { type: 'string', format: 'uuid' },
      patient_name: { type: 'string' },
      patient_phone: { type: 'string' },
      admission_id: { type: 'integer' },
      doctor_uid: { type: 'string', format: 'uuid' },
      department: { type: 'string' },
      invoice_type: { type: 'string' },
      patient_state: { type: 'string' },
      hospital_state: { type: 'string' },
      notes: { type: 'string' },
    },
  },
  AddInvoiceItemRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.addInvoiceItem; not validator-backed.',
    properties: {
      service_code: { type: 'string' },
      description: { type: 'string' },
      category: { type: 'string' },
      quantity: { type: 'number' },
      unit_price: { type: 'number' },
      gst_rate: { type: 'number' },
      notes: { type: 'string' },
      source_ref_type: { type: 'string' },
      source_ref_id: { type: 'integer' },
    },
  },
  ItemizeRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.itemizeAdmissionInvoice; not validator-backed.',
    properties: {
      emit_package: { type: 'boolean' },
      emit_pharmacy: { type: 'boolean' },
      emit_ward_indents: { type: 'boolean' },
      emit_lab: { type: 'boolean' },
      emit_consults: { type: 'boolean' },
      emit_theatre: { type: 'boolean' },
    },
  },
  TpaDecisionRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.recordInvoiceItemTpaDecision; not validator-backed.',
    properties: {
      decision: { type: 'string' },
      non_payable_reason: { type: 'string' },
    },
  },
  ApplyDiscountRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.applyDiscount; not validator-backed.',
    properties: {
      amount: { type: 'number' },
      reason: { type: 'string' },
    },
  },
  VoidInvoiceRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.voidInvoice; not validator-backed.',
    properties: {
      reason: { type: 'string' },
    },
  },
};

export const operations = {
  'GET /api/v1/admin/ledger/trial-balance': { response: 'TrialBalanceResponse' },
  'GET /api/v1/admin/ledger/ar-aging': { response: 'AgingReportResponse' },
  'GET /api/v1/admin/ledger/insurer-aging': { response: 'AgingReportResponse' },
  'GET /api/v1/admin/ledger/cash-position': { response: 'CashPositionResponse' },
  'GET /api/v1/admin/ledger/daily-collection': { response: 'DailyCollectionResponse' },

  // V1 billing (billingService.js / billingRoutes.js)
  'POST /api/v1/billing/invoice': { request: 'CreateInvoiceRequest', response: 'InvoiceResponse' },
  'GET /api/v1/billing/invoice/{id}': { response: 'InvoiceDetailResponse' },
  'GET /api/v1/billing/invoices/patient/{patientUid}': { response: 'PatientInvoicesResponse' },
  'POST /api/v1/billing/invoice/{id}/payment': { request: 'RecordPaymentRequest', response: 'PaymentResultResponse' },
  'GET /api/v1/billing/revenue': { response: 'RevenueStatsResponse' },
  'POST /api/v1/billing/insurance/claim': { request: 'SubmitClaimRequest', response: 'InsuranceClaimResponse' },
  'GET /api/v1/billing/insurance/claims': { response: 'InsuranceClaimsResponse' },
  'PUT /api/v1/billing/insurance/claim/{id}': { request: 'UpdateClaimRequest', response: 'InsuranceClaimResponse' },
  // enhancement: request typed (validator-backed); response left generic — its
  // raw-SQL RETURNING shape isn't covered by a live test, so we don't assert it.
  'POST /api/v1/billing/insurance/claim/{id}/enhancement': { request: 'EnhancementClaimRequest' },

  // V2 billing invoices (billingV2Service.js). PDF endpoints omitted (binary).
  'GET /api/v1/billing/v2/services': { response: 'ServicesListResponse' },
  'POST /api/v1/billing/v2/services': { request: 'CreateServiceMasterRequest', response: 'ServiceMasterResponse' },
  'PATCH /api/v1/billing/v2/services/{id}': { request: 'UpdateServiceMasterRequest', response: 'ServiceMasterResponse' },
  'POST /api/v1/billing/v2/invoices': { request: 'CreateDraftInvoiceRequest', response: 'InvoiceV2Response' },
  'GET /api/v1/billing/v2/invoices': { response: 'InvoicesListResponse' },
  'GET /api/v1/billing/v2/invoices/{id}': { response: 'InvoiceV2DetailResponse' },
  'POST /api/v1/billing/v2/invoices/{id}/items': { request: 'AddInvoiceItemRequest', response: 'InvoiceItemResponse' },
  'DELETE /api/v1/billing/v2/invoices/{id}/items/{itemId}': { response: 'InvoiceTotalsResponse' },
  'POST /api/v1/billing/v2/invoices/{id}/itemize': { request: 'ItemizeRequest', response: 'ItemizeResultResponse' },
  'POST /api/v1/billing/v2/invoices/{id}/items/{itemId}/tpa-decision': { request: 'TpaDecisionRequest', response: 'TpaDecisionItemResponse' },
  'GET /api/v1/billing/v2/invoices/{id}/non-payable': { response: 'NonPayableBreakdownResponse' },
  'POST /api/v1/billing/v2/invoices/{id}/discount': { request: 'ApplyDiscountRequest', response: 'InvoiceTotalsResponse' },
  'POST /api/v1/billing/v2/invoices/{id}/issue': { response: 'InvoiceV2DetailResponse' },
  'POST /api/v1/billing/v2/invoices/{id}/void': { request: 'VoidInvoiceRequest', response: 'InvoiceV2DetailResponse' },
};
