// apps/backend/scripts/openapi/schemas/money.mjs
// Typed request/response payload schemas for the money/billing surface.
// Populated per sub-surface in Phase 5 tasks T3–T8.
import { envelope, listEnvelope } from './_helpers.mjs';

export const schemas = {
  // ---- GL ledger reports (read-only; ledgerReportsService.js) ----
  TrialBalanceAccount: {
    type: 'object', additionalProperties: false,
    required: ['code', 'type', 'balancePaise', 'balance'],
    properties: {
      code: { type: 'string', example: 'PATIENT_AR' },
      type: { type: 'string', enum: ['ASSET', 'LIABILITY', 'REVENUE', 'EQUITY', 'CONTRA'] },
      balancePaise: { type: 'integer', example: 100000 },
      balance: { type: 'string', example: '1000.00' },
    },
  },
  TrialBalance: {
    type: 'object', additionalProperties: false,
    required: ['accounts', 'signedTotalPaise', 'balanced'],
    properties: {
      accounts: { type: 'array', items: { $ref: '#/components/schemas/TrialBalanceAccount' } },
      signedTotalPaise: { type: 'integer', example: 0 },
      balanced: { type: 'boolean', example: true },
    },
  },
  TrialBalanceResponse: envelope('TrialBalance'),

  AgingBucket: {
    type: 'object', additionalProperties: false,
    required: ['bucket', 'invoiceCount', 'totalPaise', 'total'],
    properties: {
      bucket: { type: 'string', enum: ['0-30', '31-60', '61-90', '90+'] },
      invoiceCount: { type: 'integer', example: 3 },
      totalPaise: { type: 'integer', example: 250000 },
      total: { type: 'string', example: '2500.00' },
    },
  },
  AgingReport: {
    type: 'object', additionalProperties: false,
    required: ['buckets', 'grandTotalPaise', 'grandTotal'],
    properties: {
      buckets: { type: 'array', items: { $ref: '#/components/schemas/AgingBucket' } },
      grandTotalPaise: { type: 'integer', example: 250000 },
      grandTotal: { type: 'string', example: '2500.00' },
    },
  },
  AgingReportResponse: envelope('AgingReport'),

  DrawerPosition: {
    type: 'object', additionalProperties: false,
    required: ['drawerSessionId', 'netPaise', 'net'],
    properties: {
      drawerSessionId: { type: 'integer', example: 12 },
      netPaise: { type: 'integer', example: 50000 },
      net: { type: 'string', example: '500.00' },
    },
  },
  CashPosition: {
    type: 'object', additionalProperties: false,
    required: ['cashTotalPaise', 'cashTotal', 'bankTotalPaise', 'bankTotal', 'byDrawer'],
    properties: {
      cashTotalPaise: { type: 'integer', example: 50000 },
      cashTotal: { type: 'string', example: '500.00' },
      bankTotalPaise: { type: 'integer', example: 0 },
      bankTotal: { type: 'string', example: '0.00' },
      byDrawer: { type: 'array', items: { $ref: '#/components/schemas/DrawerPosition' } },
    },
  },
  CashPositionResponse: envelope('CashPosition'),

  DailyCollectionDay: {
    type: 'object', additionalProperties: false,
    required: ['day', 'collectedPaise', 'collected'],
    properties: {
      day: { type: 'string', example: '2026-06-24' },
      collectedPaise: { type: 'integer', example: 75000 },
      collected: { type: 'string', example: '750.00' },
    },
  },
  DailyCollection: {
    type: 'object', additionalProperties: false,
    required: ['days', 'totalPaise', 'total'],
    properties: {
      days: { type: 'array', items: { $ref: '#/components/schemas/DailyCollectionDay' } },
      totalPaise: { type: 'integer', example: 75000 },
      total: { type: 'string', example: '750.00' },
    },
  },
  DailyCollectionResponse: envelope('DailyCollection'),

  // ---- V1 billing (billingService.js) — money Decimals serialize as strings ----
  Invoice: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_number', 'patient_uid', 'type', 'items', 'subtotal', 'tax_amount',
      'discount_amount', 'total_amount', 'paid_amount', 'payment_status', 'issued_at', 'created_at', 'updated_at', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string', example: 'INV-202606-0001' },
      patient_uid: { type: 'string', format: 'uuid' },
      appointment_id: { type: 'integer', nullable: true },
      type: { type: 'string', enum: ['consultation', 'investigation', 'pharmacy', 'procedure', 'room_charge'] },
      items: { type: 'array', items: { type: 'object', additionalProperties: true } },
      subtotal: { type: 'string', example: '1000.00' },
      tax_amount: { type: 'string', example: '180.00' },
      discount_amount: { type: 'string', example: '0.00' },
      total_amount: { type: 'string', example: '1180.00' },
      paid_amount: { type: 'string', example: '0.00' },
      payment_status: { type: 'string', enum: ['pending', 'partial', 'paid', 'refunded', 'written_off'] },
      payment_method: { type: 'string', nullable: true, enum: ['cash', 'card', 'upi', 'insurance', 'cheque'] },
      insurance_claim_id: { type: 'integer', nullable: true },
      notes: { type: 'string', nullable: true },
      issued_by: { type: 'string', format: 'uuid', nullable: true },
      issued_at: { type: 'string', format: 'date-time' },
      paid_at: { type: 'string', format: 'date-time', nullable: true },
      due_date: { type: 'string', format: 'date-time', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
      tenant_id: { type: 'string', format: 'uuid' },
    },
  },
  InvoiceResponse: envelope('Invoice'),

  PaymentTransaction: {
    type: 'object', additionalProperties: false,
    required: ['id', 'amount', 'payment_method', 'status', 'created_at', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_id: { type: 'integer', nullable: true },
      amount: { type: 'string', example: '500.00' },
      payment_method: { type: 'string' },
      transaction_ref: { type: 'string', nullable: true },
      status: { type: 'string', example: 'completed' },
      processed_by: { type: 'string', format: 'uuid', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      tenant_id: { type: 'string', format: 'uuid' },
    },
  },
  InsuranceClaimSummary: {
    type: 'object', additionalProperties: false,
    required: ['id', 'claim_number', 'insurance_provider', 'policy_number', 'claim_amount', 'status', 'submitted_at'],
    properties: {
      id: { type: 'integer' },
      claim_number: { type: 'string', example: 'CLM-202606-0001' },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string' },
      claim_amount: { type: 'string', example: '5000.00' },
      approved_amount: { type: 'string', nullable: true },
      status: { type: 'string' },
      submitted_at: { type: 'string', format: 'date-time' },
      reviewed_at: { type: 'string', format: 'date-time', nullable: true },
    },
  },
  InvoiceDetail: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_number', 'patient_uid', 'type', 'total_amount', 'payment_status', 'payment_transactions'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      appointment_id: { type: 'integer', nullable: true },
      type: { type: 'string' },
      items: { type: 'array', items: { type: 'object', additionalProperties: true } },
      subtotal: { type: 'string' },
      tax_amount: { type: 'string' },
      discount_amount: { type: 'string' },
      total_amount: { type: 'string' },
      paid_amount: { type: 'string' },
      payment_status: { type: 'string' },
      payment_method: { type: 'string', nullable: true },
      insurance_claim_id: { type: 'integer', nullable: true },
      notes: { type: 'string', nullable: true },
      issued_by: { type: 'string', format: 'uuid', nullable: true },
      issued_at: { type: 'string', format: 'date-time' },
      paid_at: { type: 'string', format: 'date-time', nullable: true },
      due_date: { type: 'string', format: 'date-time', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
      tenant_id: { type: 'string', format: 'uuid' },
      payment_transactions: { type: 'array', items: { $ref: '#/components/schemas/PaymentTransaction' } },
      insurance_claim: { nullable: true, allOf: [{ $ref: '#/components/schemas/InsuranceClaimSummary' }] },
    },
  },
  InvoiceDetailResponse: envelope('InvoiceDetail'),

  PaymentInvoice: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_number', 'patient_uid', 'total_amount', 'paid_amount', 'payment_status'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      total_amount: { type: 'string' },
      paid_amount: { type: 'string' },
      payment_status: { type: 'string', enum: ['pending', 'partial', 'paid', 'refunded', 'written_off'] },
      payment_method: { type: 'string', nullable: true },
      paid_at: { type: 'string', format: 'date-time', nullable: true },
    },
  },
  PaymentResult: {
    type: 'object', additionalProperties: false,
    required: ['invoice', 'transaction'],
    properties: {
      invoice: { $ref: '#/components/schemas/PaymentInvoice' },
      transaction: { $ref: '#/components/schemas/PaymentTransaction' },
    },
  },
  PaymentResultResponse: envelope('PaymentResult'),

  InvoiceListItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_number', 'type', 'subtotal', 'tax_amount', 'discount_amount',
      'total_amount', 'paid_amount', 'payment_status', 'issued_at', 'created_at'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string' },
      type: { type: 'string' },
      subtotal: { type: 'string' },
      tax_amount: { type: 'string' },
      discount_amount: { type: 'string' },
      total_amount: { type: 'string' },
      paid_amount: { type: 'string' },
      payment_status: { type: 'string' },
      payment_method: { type: 'string', nullable: true },
      issued_at: { type: 'string', format: 'date-time' },
      due_date: { type: 'string', format: 'date-time', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
    },
  },
  PatientInvoicesResponse: listEnvelope('InvoiceListItem'),

  RevenueSummary: {
    type: 'object', additionalProperties: false,
    required: ['total_invoices', 'total_outstanding', 'paid_count', 'pending_count', 'partial_count'],
    properties: {
      total_invoices: { type: 'integer' },
      total_billed: { type: 'string', nullable: true },
      total_collected: { type: 'string', nullable: true },
      total_outstanding: { type: 'string' },
      total_discounts: { type: 'string', nullable: true },
      total_taxes: { type: 'string', nullable: true },
      paid_count: { type: 'integer' },
      pending_count: { type: 'integer' },
      partial_count: { type: 'integer' },
    },
  },
  RevenueByType: {
    type: 'object', additionalProperties: false,
    required: ['type', 'invoice_count', 'outstanding'],
    properties: {
      type: { type: 'string' },
      invoice_count: { type: 'integer' },
      total_billed: { type: 'string', nullable: true },
      total_collected: { type: 'string', nullable: true },
      outstanding: { type: 'string' },
    },
  },
  RevenueByPaymentMethod: {
    type: 'object', additionalProperties: false,
    required: ['payment_method', 'transaction_count'],
    properties: {
      payment_method: { type: 'string' },
      transaction_count: { type: 'integer' },
      total_amount: { type: 'string', nullable: true },
    },
  },
  RevenueDailyTotal: {
    type: 'object', additionalProperties: false,
    required: ['date', 'invoice_count'],
    properties: {
      date: { type: 'string', example: '2026-06-24' },
      invoice_count: { type: 'integer' },
      billed: { type: 'string', nullable: true },
      collected: { type: 'string', nullable: true },
    },
  },
  RevenueStats: {
    type: 'object', additionalProperties: false,
    required: ['summary', 'by_type', 'by_payment_method', 'daily_totals'],
    properties: {
      summary: { $ref: '#/components/schemas/RevenueSummary' },
      by_type: { type: 'array', items: { $ref: '#/components/schemas/RevenueByType' } },
      by_payment_method: { type: 'array', items: { $ref: '#/components/schemas/RevenueByPaymentMethod' } },
      daily_totals: { type: 'array', items: { $ref: '#/components/schemas/RevenueDailyTotal' } },
    },
  },
  RevenueStatsResponse: envelope('RevenueStats'),

  InsuranceClaim: {
    type: 'object', additionalProperties: false,
    required: ['id', 'claim_number', 'patient_uid', 'insurance_provider', 'policy_number',
      'claim_amount', 'status', 'submitted_at', 'created_at', 'updated_at', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      claim_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      invoice_id: { type: 'integer', nullable: true },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string' },
      claim_amount: { type: 'string' },
      approved_amount: { type: 'string', nullable: true },
      non_payable_amount: { type: 'string', nullable: true },
      disallowed_reason: { type: 'string', nullable: true },
      parent_claim_id: { type: 'integer', nullable: true },
      stage: { type: 'string', nullable: true },
      status: {
        type: 'string',
        enum: ['submitted', 'under_review', 'approved', 'partially_approved', 'rejected', 'paid', 'settled_partial', 'settled_full'],
      },
      documents: { nullable: true },
      submitted_at: { type: 'string', format: 'date-time' },
      reviewed_at: { type: 'string', format: 'date-time', nullable: true },
      rejection_reason: { type: 'string', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
      tenant_id: { type: 'string', format: 'uuid' },
    },
  },
  InsuranceClaimResponse: envelope('InsuranceClaim'),

  InsuranceClaimListItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'claim_number', 'patient_uid', 'insurance_provider', 'policy_number', 'claim_amount', 'status', 'submitted_at', 'created_at'],
    properties: {
      id: { type: 'integer' },
      claim_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      invoice_id: { type: 'integer', nullable: true },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string' },
      claim_amount: { type: 'string' },
      approved_amount: { type: 'string', nullable: true },
      status: { type: 'string' },
      submitted_at: { type: 'string', format: 'date-time' },
      reviewed_at: { type: 'string', format: 'date-time', nullable: true },
      rejection_reason: { type: 'string', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
    },
  },
  InsuranceClaimsResponse: listEnvelope('InsuranceClaimListItem'),

  // V1 billing request bodies (validator-backed → strict)
  CreateInvoiceRequest: {
    type: 'object', additionalProperties: false,
    required: ['patient_uid', 'type', 'items', 'subtotal', 'total_amount'],
    properties: {
      patient_uid: { type: 'string', format: 'uuid' },
      appointment_id: { type: 'integer' },
      type: { type: 'string', enum: ['consultation', 'investigation', 'pharmacy', 'procedure', 'room_charge'] },
      items: { type: 'array', items: { type: 'object', additionalProperties: true } },
      subtotal: { type: 'number' },
      tax_amount: { type: 'number' },
      discount_amount: { type: 'number' },
      total_amount: { type: 'number', minimum: 0 },
      payment_method: { type: 'string', enum: ['cash', 'card', 'upi', 'insurance', 'cheque'] },
      notes: { type: 'string' },
      due_date: { type: 'string', format: 'date' },
    },
  },
  RecordPaymentRequest: {
    type: 'object', additionalProperties: false,
    required: ['amount', 'payment_method'],
    properties: {
      amount: { type: 'number', minimum: 0 },
      payment_method: { type: 'string', enum: ['CASH', 'CARD', 'UPI', 'INSURANCE', 'CHEQUE'] },
      transaction_ref: { type: 'string', maxLength: 255 },
    },
  },
  SubmitClaimRequest: {
    type: 'object', additionalProperties: false,
    required: ['patient_uid', 'insurance_provider', 'policy_number', 'claim_amount'],
    properties: {
      patient_uid: { type: 'string', format: 'uuid' },
      invoice_id: { type: 'integer' },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string', maxLength: 50 },
      claim_amount: { type: 'number', minimum: 0 },
      documents: {},
    },
  },
  UpdateClaimRequest: {
    type: 'object', additionalProperties: false,
    required: ['status'],
    properties: {
      status: {
        type: 'string',
        enum: ['submitted', 'under_review', 'approved', 'partially_approved', 'rejected', 'paid', 'settled_partial', 'settled_full'],
      },
      approved_amount: { type: 'number' },
      reason: { type: 'string' },
      rejection_reason: { type: 'string' },
      documents: {},
      payment_reference: { type: 'string' },
      non_payable_amount: { type: 'number' },
      disallowed_reason: { type: 'string' },
    },
  },
  EnhancementClaimRequest: {
    type: 'object', additionalProperties: false,
    required: ['enhancement_amount'],
    properties: {
      enhancement_amount: { type: 'number', minimum: 0 },
      justification: { type: 'string' },
      clinical_justification: {},
    },
  },
};

export const operations = {
  'GET /api/v1/admin/ledger/trial-balance': { response: 'TrialBalanceResponse' },
  'GET /api/v1/admin/ledger/ar-aging': { response: 'AgingReportResponse' },
  'GET /api/v1/admin/ledger/insurer-aging': { response: 'AgingReportResponse' },
  'GET /api/v1/admin/ledger/cash-position': { response: 'CashPositionResponse' },
  'GET /api/v1/admin/ledger/daily-collection': { response: 'DailyCollectionResponse' },

  // V1 billing (billingService.js / billingRoutes.js)
  'POST /api/v1/billing/invoice': { request: 'CreateInvoiceRequest', response: 'InvoiceResponse' },
  'GET /api/v1/billing/invoice/{id}': { response: 'InvoiceDetailResponse' },
  'GET /api/v1/billing/invoices/patient/{patientUid}': { response: 'PatientInvoicesResponse' },
  'POST /api/v1/billing/invoice/{id}/payment': { request: 'RecordPaymentRequest', response: 'PaymentResultResponse' },
  'GET /api/v1/billing/revenue': { response: 'RevenueStatsResponse' },
  'POST /api/v1/billing/insurance/claim': { request: 'SubmitClaimRequest', response: 'InsuranceClaimResponse' },
  'GET /api/v1/billing/insurance/claims': { response: 'InsuranceClaimsResponse' },
  'PUT /api/v1/billing/insurance/claim/{id}': { request: 'UpdateClaimRequest', response: 'InsuranceClaimResponse' },
  // enhancement: request typed (validator-backed); response left generic — its
  // raw-SQL RETURNING shape isn't covered by a live test, so we don't assert it.
  'POST /api/v1/billing/insurance/claim/{id}/enhancement': { request: 'EnhancementClaimRequest' },
};
