// apps/backend/scripts/openapi/schemas/money.mjs
// Typed request/response payload schemas for the money/billing surface.
// Populated per sub-surface in Phase 5 tasks T3–T8.
import { envelope, listEnvelope, countListEnvelope } from './_helpers.mjs';

// V2 money JSON type. V2 uses Decimal(12,2) in rupees, which Prisma serializes
// to a JSON STRING (verified by the V2 contract deep test, same as V1).
const MT = 'string';

export const schemas = {
  // ---- GL ledger reports (read-only; ledgerReportsService.js) ----
  TrialBalanceAccount: {
    type: 'object', additionalProperties: false,
    required: ['code', 'type', 'balancePaise', 'balance'],
    properties: {
      code: { type: 'string', example: 'PATIENT_AR' },
      type: { type: 'string', enum: ['ASSET', 'LIABILITY', 'REVENUE', 'EQUITY', 'CONTRA'] },
      balancePaise: { type: 'integer', example: 100000 },
      balance: { type: 'string', example: '1000.00' },
    },
  },
  TrialBalance: {
    type: 'object', additionalProperties: false,
    required: ['accounts', 'signedTotalPaise', 'balanced'],
    properties: {
      accounts: { type: 'array', items: { $ref: '#/components/schemas/TrialBalanceAccount' } },
      signedTotalPaise: { type: 'integer', example: 0 },
      balanced: { type: 'boolean', example: true },
    },
  },
  TrialBalanceResponse: envelope('TrialBalance'),

  AgingBucket: {
    type: 'object', additionalProperties: false,
    required: ['bucket', 'invoiceCount', 'totalPaise', 'total'],
    properties: {
      bucket: { type: 'string', enum: ['0-30', '31-60', '61-90', '90+'] },
      invoiceCount: { type: 'integer', example: 3 },
      totalPaise: { type: 'integer', example: 250000 },
      total: { type: 'string', example: '2500.00' },
    },
  },
  AgingReport: {
    type: 'object', additionalProperties: false,
    required: ['buckets', 'grandTotalPaise', 'grandTotal'],
    properties: {
      buckets: { type: 'array', items: { $ref: '#/components/schemas/AgingBucket' } },
      grandTotalPaise: { type: 'integer', example: 250000 },
      grandTotal: { type: 'string', example: '2500.00' },
    },
  },
  AgingReportResponse: envelope('AgingReport'),

  DrawerPosition: {
    type: 'object', additionalProperties: false,
    required: ['drawerSessionId', 'netPaise', 'net'],
    properties: {
      drawerSessionId: { type: 'integer', example: 12 },
      netPaise: { type: 'integer', example: 50000 },
      net: { type: 'string', example: '500.00' },
    },
  },
  CashPosition: {
    type: 'object', additionalProperties: false,
    required: ['cashTotalPaise', 'cashTotal', 'bankTotalPaise', 'bankTotal', 'byDrawer'],
    properties: {
      cashTotalPaise: { type: 'integer', example: 50000 },
      cashTotal: { type: 'string', example: '500.00' },
      bankTotalPaise: { type: 'integer', example: 0 },
      bankTotal: { type: 'string', example: '0.00' },
      byDrawer: { type: 'array', items: { $ref: '#/components/schemas/DrawerPosition' } },
    },
  },
  CashPositionResponse: envelope('CashPosition'),

  DailyCollectionDay: {
    type: 'object', additionalProperties: false,
    required: ['day', 'collectedPaise', 'collected'],
    properties: {
      day: { type: 'string', example: '2026-06-24' },
      collectedPaise: { type: 'integer', example: 75000 },
      collected: { type: 'string', example: '750.00' },
    },
  },
  DailyCollection: {
    type: 'object', additionalProperties: false,
    required: ['days', 'totalPaise', 'total'],
    properties: {
      days: { type: 'array', items: { $ref: '#/components/schemas/DailyCollectionDay' } },
      totalPaise: { type: 'integer', example: 75000 },
      total: { type: 'string', example: '750.00' },
    },
  },
  DailyCollectionResponse: envelope('DailyCollection'),

  // ---- V1 billing (billingService.js) — money Decimals serialize as strings ----
  Invoice: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_number', 'patient_uid', 'type', 'items', 'subtotal', 'tax_amount',
      'discount_amount', 'total_amount', 'paid_amount', 'payment_status', 'issued_at', 'created_at', 'updated_at', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string', example: 'INV-202606-0001' },
      patient_uid: { type: 'string', format: 'uuid' },
      appointment_id: { type: 'integer', nullable: true },
      type: { type: 'string', enum: ['consultation', 'investigation', 'pharmacy', 'procedure', 'room_charge'] },
      items: { type: 'array', items: { type: 'object', additionalProperties: true } },
      subtotal: { type: 'string', example: '1000.00' },
      tax_amount: { type: 'string', example: '180.00' },
      discount_amount: { type: 'string', example: '0.00' },
      total_amount: { type: 'string', example: '1180.00' },
      paid_amount: { type: 'string', example: '0.00' },
      payment_status: { type: 'string', enum: ['pending', 'partial', 'paid', 'refunded', 'written_off'] },
      payment_method: { type: 'string', nullable: true, enum: ['cash', 'card', 'upi', 'insurance', 'cheque', null] },
      insurance_claim_id: { type: 'integer', nullable: true },
      notes: { type: 'string', nullable: true },
      issued_by: { type: 'string', format: 'uuid', nullable: true },
      issued_at: { type: 'string', format: 'date-time' },
      paid_at: { type: 'string', format: 'date-time', nullable: true },
      due_date: { type: 'string', format: 'date-time', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
      tenant_id: { type: 'string', format: 'uuid' },
    },
  },
  InvoiceResponse: envelope('Invoice'),

  PaymentTransaction: {
    type: 'object', additionalProperties: false,
    required: ['id', 'amount', 'payment_method', 'status', 'created_at', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_id: { type: 'integer', nullable: true },
      amount: { type: 'string', example: '500.00' },
      payment_method: { type: 'string' },
      transaction_ref: { type: 'string', nullable: true },
      status: { type: 'string', example: 'completed' },
      processed_by: { type: 'string', format: 'uuid', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      tenant_id: { type: 'string', format: 'uuid' },
    },
  },
  InsuranceClaimSummary: {
    type: 'object', additionalProperties: false,
    required: ['id', 'claim_number', 'insurance_provider', 'policy_number', 'claim_amount', 'status', 'submitted_at'],
    properties: {
      id: { type: 'integer' },
      claim_number: { type: 'string', example: 'CLM-202606-0001' },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string' },
      claim_amount: { type: 'string', example: '5000.00' },
      approved_amount: { type: 'string', nullable: true },
      status: { type: 'string' },
      submitted_at: { type: 'string', format: 'date-time' },
      reviewed_at: { type: 'string', format: 'date-time', nullable: true },
    },
  },
  InvoiceDetail: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_number', 'patient_uid', 'type', 'items', 'subtotal', 'tax_amount',
      'discount_amount', 'total_amount', 'paid_amount', 'payment_status', 'payment_transactions'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      appointment_id: { type: 'integer', nullable: true },
      type: { type: 'string' },
      items: { type: 'array', items: { type: 'object', additionalProperties: true } },
      subtotal: { type: 'string' },
      tax_amount: { type: 'string' },
      discount_amount: { type: 'string' },
      total_amount: { type: 'string' },
      paid_amount: { type: 'string' },
      payment_status: { type: 'string' },
      payment_method: { type: 'string', nullable: true },
      insurance_claim_id: { type: 'integer', nullable: true },
      notes: { type: 'string', nullable: true },
      issued_by: { type: 'string', format: 'uuid', nullable: true },
      issued_at: { type: 'string', format: 'date-time' },
      paid_at: { type: 'string', format: 'date-time', nullable: true },
      due_date: { type: 'string', format: 'date-time', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
      tenant_id: { type: 'string', format: 'uuid' },
      payment_transactions: { type: 'array', items: { $ref: '#/components/schemas/PaymentTransaction' } },
      insurance_claim: { nullable: true, allOf: [{ $ref: '#/components/schemas/InsuranceClaimSummary' }] },
    },
  },
  InvoiceDetailResponse: envelope('InvoiceDetail'),

  PaymentInvoice: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_number', 'patient_uid', 'total_amount', 'paid_amount', 'payment_status'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      total_amount: { type: 'string' },
      paid_amount: { type: 'string' },
      payment_status: { type: 'string', enum: ['pending', 'partial', 'paid', 'refunded', 'written_off'] },
      payment_method: { type: 'string', nullable: true },
      paid_at: { type: 'string', format: 'date-time', nullable: true },
    },
  },
  PaymentResult: {
    type: 'object', additionalProperties: false,
    required: ['invoice', 'transaction'],
    properties: {
      invoice: { $ref: '#/components/schemas/PaymentInvoice' },
      transaction: { $ref: '#/components/schemas/PaymentTransaction' },
    },
  },
  PaymentResultResponse: envelope('PaymentResult'),

  InvoiceListItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_number', 'type', 'subtotal', 'tax_amount', 'discount_amount',
      'total_amount', 'paid_amount', 'payment_status', 'issued_at', 'created_at'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string' },
      type: { type: 'string' },
      subtotal: { type: 'string' },
      tax_amount: { type: 'string' },
      discount_amount: { type: 'string' },
      total_amount: { type: 'string' },
      paid_amount: { type: 'string' },
      payment_status: { type: 'string' },
      payment_method: { type: 'string', nullable: true },
      issued_at: { type: 'string', format: 'date-time' },
      due_date: { type: 'string', format: 'date-time', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
    },
  },
  PatientInvoicesResponse: listEnvelope('InvoiceListItem'),

  RevenueSummary: {
    type: 'object', additionalProperties: false,
    required: ['total_invoices', 'total_outstanding', 'paid_count', 'pending_count', 'partial_count'],
    properties: {
      total_invoices: { type: 'integer' },
      total_billed: { type: 'string', nullable: true },
      total_collected: { type: 'string', nullable: true },
      total_outstanding: { type: 'string' },
      total_discounts: { type: 'string', nullable: true },
      total_taxes: { type: 'string', nullable: true },
      paid_count: { type: 'integer' },
      pending_count: { type: 'integer' },
      partial_count: { type: 'integer' },
    },
  },
  RevenueByType: {
    type: 'object', additionalProperties: false,
    required: ['type', 'invoice_count', 'outstanding'],
    properties: {
      type: { type: 'string' },
      invoice_count: { type: 'integer' },
      total_billed: { type: 'string', nullable: true },
      total_collected: { type: 'string', nullable: true },
      outstanding: { type: 'string' },
    },
  },
  RevenueByPaymentMethod: {
    type: 'object', additionalProperties: false,
    required: ['payment_method', 'transaction_count'],
    properties: {
      payment_method: { type: 'string' },
      transaction_count: { type: 'integer' },
      total_amount: { type: 'string', nullable: true },
    },
  },
  RevenueDailyTotal: {
    type: 'object', additionalProperties: false,
    required: ['date', 'invoice_count'],
    properties: {
      date: { type: 'string', example: '2026-06-24' },
      invoice_count: { type: 'integer' },
      billed: { type: 'string', nullable: true },
      collected: { type: 'string', nullable: true },
    },
  },
  RevenueStats: {
    type: 'object', additionalProperties: false,
    required: ['summary', 'by_type', 'by_payment_method', 'daily_totals'],
    properties: {
      summary: { $ref: '#/components/schemas/RevenueSummary' },
      by_type: { type: 'array', items: { $ref: '#/components/schemas/RevenueByType' } },
      by_payment_method: { type: 'array', items: { $ref: '#/components/schemas/RevenueByPaymentMethod' } },
      daily_totals: { type: 'array', items: { $ref: '#/components/schemas/RevenueDailyTotal' } },
    },
  },
  RevenueStatsResponse: envelope('RevenueStats'),

  InsuranceClaim: {
    type: 'object', additionalProperties: false,
    required: ['id', 'claim_number', 'patient_uid', 'insurance_provider', 'policy_number',
      'claim_amount', 'status', 'submitted_at', 'created_at', 'updated_at', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      claim_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      invoice_id: { type: 'integer', nullable: true },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string' },
      claim_amount: { type: 'string' },
      approved_amount: { type: 'string', nullable: true },
      non_payable_amount: { type: 'string', nullable: true },
      disallowed_reason: { type: 'string', nullable: true },
      parent_claim_id: { type: 'integer', nullable: true },
      stage: { type: 'string', nullable: true },
      status: {
        type: 'string',
        enum: ['submitted', 'under_review', 'approved', 'partially_approved', 'rejected', 'paid', 'settled_partial', 'settled_full'],
      },
      documents: { nullable: true },
      submitted_at: { type: 'string', format: 'date-time' },
      reviewed_at: { type: 'string', format: 'date-time', nullable: true },
      rejection_reason: { type: 'string', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
      tenant_id: { type: 'string', format: 'uuid' },
    },
  },
  InsuranceClaimResponse: envelope('InsuranceClaim'),

  InsuranceClaimListItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'claim_number', 'patient_uid', 'insurance_provider', 'policy_number', 'claim_amount', 'status', 'submitted_at', 'created_at'],
    properties: {
      id: { type: 'integer' },
      claim_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      invoice_id: { type: 'integer', nullable: true },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string' },
      claim_amount: { type: 'string' },
      approved_amount: { type: 'string', nullable: true },
      status: { type: 'string' },
      submitted_at: { type: 'string', format: 'date-time' },
      reviewed_at: { type: 'string', format: 'date-time', nullable: true },
      rejection_reason: { type: 'string', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
    },
  },
  InsuranceClaimsResponse: listEnvelope('InsuranceClaimListItem'),

  // V1 billing request bodies (validator-backed → strict)
  CreateInvoiceRequest: {
    type: 'object', additionalProperties: false,
    required: ['patient_uid', 'type', 'items', 'subtotal', 'total_amount'],
    properties: {
      patient_uid: { type: 'string', format: 'uuid' },
      appointment_id: { type: 'integer' },
      type: { type: 'string', enum: ['consultation', 'investigation', 'pharmacy', 'procedure', 'room_charge'] },
      items: { type: 'array', items: { type: 'object', additionalProperties: true } },
      subtotal: { type: 'number' },
      tax_amount: { type: 'number' },
      discount_amount: { type: 'number' },
      total_amount: { type: 'number', minimum: 0 },
      payment_method: { type: 'string', enum: ['cash', 'card', 'upi', 'insurance', 'cheque'] },
      notes: { type: 'string' },
      due_date: { type: 'string', format: 'date' },
    },
  },
  RecordPaymentRequest: {
    type: 'object', additionalProperties: false,
    required: ['amount', 'payment_method'],
    properties: {
      amount: { type: 'number', minimum: 0 },
      payment_method: { type: 'string', enum: ['CASH', 'CARD', 'UPI', 'INSURANCE', 'CHEQUE'] },
      transaction_ref: { type: 'string', maxLength: 255 },
    },
  },
  SubmitClaimRequest: {
    type: 'object', additionalProperties: false,
    required: ['patient_uid', 'insurance_provider', 'policy_number', 'claim_amount'],
    properties: {
      patient_uid: { type: 'string', format: 'uuid' },
      invoice_id: { type: 'integer' },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string', maxLength: 50 },
      claim_amount: { type: 'number', minimum: 0 },
      documents: {},
    },
  },
  UpdateClaimRequest: {
    type: 'object', additionalProperties: false,
    required: ['status'],
    properties: {
      status: {
        type: 'string',
        enum: ['submitted', 'under_review', 'approved', 'partially_approved', 'rejected', 'paid', 'settled_partial', 'settled_full'],
      },
      approved_amount: { type: 'number' },
      reason: { type: 'string' },
      rejection_reason: { type: 'string' },
      documents: {},
      payment_reference: { type: 'string' },
      non_payable_amount: { type: 'number' },
      disallowed_reason: { type: 'string' },
    },
  },
  EnhancementClaimRequest: {
    type: 'object', additionalProperties: false,
    required: ['enhancement_amount'],
    properties: {
      enhancement_amount: { type: 'number', minimum: 0 },
      justification: { type: 'string' },
      clinical_justification: {},
    },
  },

  // ---- V2 billing invoices (billingV2Service.js) ----
  ServiceMaster: {
    type: 'object', additionalProperties: false,
    required: ['id', 'code', 'description', 'category', 'default_price', 'gst_rate'],
    properties: {
      id: { type: 'integer' },
      code: { type: 'string' },
      description: { type: 'string' },
      category: { type: 'string' },
      default_price: { type: MT },
      gst_rate: { type: MT },
      hsn_sac: { type: 'string', nullable: true },
      is_active: { type: 'boolean', nullable: true },
    },
  },
  ServiceMasterResponse: envelope('ServiceMaster'),
  ServicesListResponse: listEnvelope('ServiceMaster'),

  InvoiceV2: {
    type: 'object', additionalProperties: false,
    required: ['id', 'patient_uid', 'invoice_type', 'subtotal', 'cgst_amount', 'sgst_amount',
      'igst_amount', 'discount_amount', 'total_amount', 'amount_paid', 'amount_due', 'status', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string', nullable: true },
      patient_uid: { type: 'string', format: 'uuid' },
      patient_name: { type: 'string', nullable: true },
      patient_phone: { type: 'string', nullable: true },
      admission_id: { type: 'integer', nullable: true },
      doctor_uid: { type: 'string', format: 'uuid', nullable: true },
      department: { type: 'string', nullable: true },
      invoice_type: { type: 'string' },
      patient_state: { type: 'string', nullable: true },
      hospital_state: { type: 'string', nullable: true },
      subtotal: { type: MT },
      cgst_amount: { type: MT },
      sgst_amount: { type: MT },
      igst_amount: { type: MT },
      discount_amount: { type: MT },
      discount_reason: { type: 'string', nullable: true },
      discount_approved_by: { type: 'string', format: 'uuid', nullable: true },
      total_amount: { type: MT },
      amount_paid: { type: MT },
      amount_due: { type: MT },
      status: { type: 'string' },
      notes: { type: 'string', nullable: true },
      created_by: { type: 'string', format: 'uuid', nullable: true },
      issued_at: { type: 'string', format: 'date-time', nullable: true },
      voided_at: { type: 'string', format: 'date-time', nullable: true },
      voided_by: { type: 'string', format: 'uuid', nullable: true },
      void_reason: { type: 'string', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      created_at: { type: 'string', format: 'date-time', nullable: true },
      updated_at: { type: 'string', format: 'date-time', nullable: true },
    },
  },
  InvoiceV2Response: envelope('InvoiceV2'),

  TpaUtilisation: {
    type: 'object', additionalProperties: false,
    required: ['root_preauth_id', 'root_preauth_number', 'cumulative_approved', 'total_charged', 'remaining', 'utilisation_pct', 'status'],
    properties: {
      root_preauth_id: { type: 'integer' },
      root_preauth_number: { type: 'string' },
      cumulative_approved: { type: MT },
      total_charged: { type: MT },
      remaining: { type: MT },
      utilisation_pct: { type: MT },
      status: { type: 'string' },
    },
  },
  InvoiceV2ListItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'patient_uid', 'invoice_type', 'total_amount', 'amount_paid', 'amount_due', 'status', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string', nullable: true },
      patient_uid: { type: 'string', format: 'uuid' },
      patient_name: { type: 'string', nullable: true },
      invoice_type: { type: 'string' },
      total_amount: { type: MT },
      amount_paid: { type: MT },
      amount_due: { type: MT },
      status: { type: 'string' },
      admission_id: { type: 'integer', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      issued_at: { type: 'string', format: 'date-time', nullable: true },
      created_at: { type: 'string', format: 'date-time', nullable: true },
      tpa_utilisation: { nullable: true, allOf: [{ $ref: '#/components/schemas/TpaUtilisation' }] },
    },
  },
  InvoicesListResponse: listEnvelope('InvoiceV2ListItem'),

  InvoiceItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_id', 'description', 'quantity', 'unit_price', 'gst_rate',
      'line_subtotal', 'cgst_amount', 'sgst_amount', 'igst_amount', 'line_total', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_id: { type: 'integer' },
      service_code: { type: 'string', nullable: true },
      description: { type: 'string' },
      category: { type: 'string', nullable: true },
      hsn_sac: { type: 'string', nullable: true },
      quantity: { type: MT },
      unit_price: { type: MT },
      gst_rate: { type: MT },
      line_subtotal: { type: MT },
      cgst_amount: { type: MT },
      sgst_amount: { type: MT },
      igst_amount: { type: MT },
      line_total: { type: MT },
      notes: { type: 'string', nullable: true },
      created_at: { type: 'string', format: 'date-time', nullable: true },
      source_ref_type: { type: 'string', nullable: true },
      source_ref_id: { type: 'integer', nullable: true },
      tpa_decision: { type: 'string', nullable: true },
      tpa_non_payable_reason: { type: 'string', nullable: true },
      tpa_decided_at: { type: 'string', format: 'date-time', nullable: true },
      tpa_decided_by: { type: 'string', format: 'uuid', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
    },
  },
  InvoiceItemResponse: envelope('InvoiceItem'),

  InvoiceV2Payment: {
    type: 'object', additionalProperties: false,
    required: ['id', 'patient_uid', 'amount', 'mode', 'reversed', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      invoice_id: { type: 'integer', nullable: true },
      patient_uid: { type: 'string', format: 'uuid' },
      amount: { type: MT },
      mode: { type: 'string' },
      reference: { type: 'string', nullable: true },
      denominations: { nullable: true },
      collected_by: { type: 'string', format: 'uuid', nullable: true },
      collected_at: { type: 'string', format: 'date-time', nullable: true },
      shift: { type: 'string', nullable: true },
      notes: { type: 'string', nullable: true },
      reversed: { type: 'boolean' },
      reversed_at: { type: 'string', format: 'date-time', nullable: true },
      reversed_by: { type: 'string', format: 'uuid', nullable: true },
      reversal_reason: { type: 'string', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      created_at: { type: 'string', format: 'date-time', nullable: true },
    },
  },
  // advance_mode is JOIN-only (present in invoice-detail advance_settlements[],
  // absent from the raw settle-endpoint response) → optional.
  AdvanceSettlement: {
    type: 'object', additionalProperties: false,
    required: ['id', 'advance_id', 'invoice_id', 'amount', 'tenant_id'],
    properties: {
      id: { type: 'integer' },
      advance_id: { type: 'integer' },
      invoice_id: { type: 'integer' },
      amount: { type: MT },
      settled_by: { type: 'string', format: 'uuid', nullable: true },
      settled_at: { type: 'string', format: 'date-time', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      advance_mode: { type: 'string' },
    },
  },
  TpaPreauth: {
    type: 'object', additionalProperties: false,
    required: ['preauth_id', 'preauth_number', 'tpa_status'],
    properties: {
      preauth_id: { type: 'integer' },
      preauth_number: { type: 'string' },
      tpa_status: { type: 'string' },
      denial_reason: { type: 'string', nullable: true },
      sanctioned_amount: { type: MT, nullable: true },
      policy_id: { type: 'string', format: 'uuid', nullable: true },
    },
  },
  InvoiceV2Detail: {
    type: 'object', additionalProperties: false,
    required: ['id', 'patient_uid', 'invoice_type', 'subtotal', 'total_amount', 'amount_paid',
      'amount_due', 'status', 'tenant_id', 'items', 'payments', 'advance_settlements'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string', nullable: true },
      patient_uid: { type: 'string', format: 'uuid' },
      patient_name: { type: 'string', nullable: true },
      patient_phone: { type: 'string', nullable: true },
      admission_id: { type: 'integer', nullable: true },
      doctor_uid: { type: 'string', format: 'uuid', nullable: true },
      department: { type: 'string', nullable: true },
      invoice_type: { type: 'string' },
      patient_state: { type: 'string', nullable: true },
      hospital_state: { type: 'string', nullable: true },
      subtotal: { type: MT },
      cgst_amount: { type: MT },
      sgst_amount: { type: MT },
      igst_amount: { type: MT },
      discount_amount: { type: MT },
      discount_reason: { type: 'string', nullable: true },
      discount_approved_by: { type: 'string', format: 'uuid', nullable: true },
      total_amount: { type: MT },
      amount_paid: { type: MT },
      amount_due: { type: MT },
      status: { type: 'string' },
      notes: { type: 'string', nullable: true },
      created_by: { type: 'string', format: 'uuid', nullable: true },
      issued_at: { type: 'string', format: 'date-time', nullable: true },
      voided_at: { type: 'string', format: 'date-time', nullable: true },
      voided_by: { type: 'string', format: 'uuid', nullable: true },
      void_reason: { type: 'string', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      created_at: { type: 'string', format: 'date-time', nullable: true },
      updated_at: { type: 'string', format: 'date-time', nullable: true },
      items: { type: 'array', items: { $ref: '#/components/schemas/InvoiceItem' } },
      payments: { type: 'array', items: { $ref: '#/components/schemas/InvoiceV2Payment' } },
      advance_settlements: { type: 'array', items: { $ref: '#/components/schemas/AdvanceSettlement' } },
      tpa_utilisation: { nullable: true, allOf: [{ $ref: '#/components/schemas/TpaUtilisation' }] },
      tpa_preauth: { nullable: true, allOf: [{ $ref: '#/components/schemas/TpaPreauth' }] },
    },
  },
  InvoiceV2DetailResponse: envelope('InvoiceV2Detail'),

  // recomputeInvoiceTotals computes these in JS -> JSON numbers (not Decimal strings).
  InvoiceTotals: {
    type: 'object', additionalProperties: false,
    required: ['subtotal', 'cgst', 'sgst', 'igst', 'discount', 'total', 'paid', 'due'],
    properties: {
      subtotal: { type: 'number' },
      cgst: { type: 'number' },
      sgst: { type: 'number' },
      igst: { type: 'number' },
      discount: { type: 'number' },
      total: { type: 'number' },
      paid: { type: 'number' },
      due: { type: 'number' },
    },
  },
  InvoiceTotalsResponse: envelope('InvoiceTotals'),

  ItemizeSummary: {
    type: 'object', additionalProperties: false,
    required: ['package', 'pharmacy', 'ward_indents', 'lab', 'consults', 'theatre', 'room_upgrade', 'skipped_existing'],
    properties: {
      package: { type: 'integer' },
      pharmacy: { type: 'integer' },
      ward_indents: { type: 'integer' },
      lab: { type: 'integer' },
      consults: { type: 'integer' },
      theatre: { type: 'integer' },
      room_upgrade: { type: 'integer' },
      skipped_existing: { type: 'integer' },
    },
  },
  ItemizeResult: {
    type: 'object', additionalProperties: false,
    required: ['invoice_id', 'admission_id', 'summary'],
    properties: {
      invoice_id: { type: 'integer' },
      admission_id: { type: 'integer' },
      package_id: { type: 'integer', nullable: true },
      summary: { $ref: '#/components/schemas/ItemizeSummary' },
    },
  },
  ItemizeResultResponse: envelope('ItemizeResult'),

  TpaDecisionItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'invoice_id', 'description', 'line_total', 'tpa_decision'],
    properties: {
      id: { type: 'integer' },
      invoice_id: { type: 'integer' },
      description: { type: 'string' },
      line_total: { type: MT },
      tpa_decision: { type: 'string' },
      tpa_non_payable_reason: { type: 'string', nullable: true },
      tpa_decided_at: { type: 'string', format: 'date-time', nullable: true },
      tpa_decided_by: { type: 'string', format: 'uuid', nullable: true },
    },
  },
  TpaDecisionItemResponse: envelope('TpaDecisionItem'),

  NonPayableLine: {
    type: 'object', additionalProperties: false,
    required: ['id', 'description', 'line_total', 'tpa_decision'],
    properties: {
      id: { type: 'integer' },
      description: { type: 'string' },
      source_ref_type: { type: 'string', nullable: true },
      source_ref_id: { type: 'integer', nullable: true },
      line_total: { type: MT },
      tpa_decision: { type: 'string' },
      tpa_non_payable_reason: { type: 'string', nullable: true },
      tpa_decided_at: { type: 'string', format: 'date-time', nullable: true },
    },
  },
  NonPayableBreakdown: {
    type: 'object', additionalProperties: false,
    required: ['invoice_id', 'non_payable_total', 'line_count', 'lines'],
    properties: {
      invoice_id: { type: 'integer' },
      non_payable_total: { type: 'number' },
      line_count: { type: 'integer' },
      lines: { type: 'array', items: { $ref: '#/components/schemas/NonPayableLine' } },
    },
  },
  NonPayableBreakdownResponse: envelope('NonPayableBreakdown'),

  // V2 invoice request bodies (no validators → permissive, known fields typed)
  CreateServiceMasterRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.createServiceMaster; not validator-backed.',
    properties: {
      code: { type: 'string' },
      description: { type: 'string' },
      category: { type: 'string' },
      default_price: { type: 'number' },
      gst_rate: { type: 'number' },
      hsn_sac: { type: 'string' },
    },
  },
  UpdateServiceMasterRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.updateServiceMaster; not validator-backed.',
    properties: {
      description: { type: 'string' },
      category: { type: 'string' },
      default_price: { type: 'number' },
      gst_rate: { type: 'number' },
      hsn_sac: { type: 'string' },
      is_active: { type: 'boolean' },
    },
  },
  CreateDraftInvoiceRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.createDraftInvoice; not validator-backed.',
    properties: {
      patient_uid: { type: 'string', format: 'uuid' },
      patient_name: { type: 'string' },
      patient_phone: { type: 'string' },
      admission_id: { type: 'integer' },
      doctor_uid: { type: 'string', format: 'uuid' },
      department: { type: 'string' },
      invoice_type: { type: 'string' },
      patient_state: { type: 'string' },
      hospital_state: { type: 'string' },
      notes: { type: 'string' },
    },
  },
  AddInvoiceItemRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.addInvoiceItem; not validator-backed.',
    properties: {
      service_code: { type: 'string' },
      description: { type: 'string' },
      category: { type: 'string' },
      quantity: { type: 'number' },
      unit_price: { type: 'number' },
      gst_rate: { type: 'number' },
      notes: { type: 'string' },
      source_ref_type: { type: 'string' },
      source_ref_id: { type: 'integer' },
    },
  },
  ItemizeRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.itemizeAdmissionInvoice; not validator-backed.',
    properties: {
      emit_package: { type: 'boolean' },
      emit_pharmacy: { type: 'boolean' },
      emit_ward_indents: { type: 'boolean' },
      emit_lab: { type: 'boolean' },
      emit_consults: { type: 'boolean' },
      emit_theatre: { type: 'boolean' },
    },
  },
  TpaDecisionRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.recordInvoiceItemTpaDecision; not validator-backed.',
    properties: {
      decision: { type: 'string' },
      non_payable_reason: { type: 'string' },
    },
  },
  ApplyDiscountRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.applyDiscount; not validator-backed.',
    properties: {
      amount: { type: 'number' },
      reason: { type: 'string' },
    },
  },
  VoidInvoiceRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.voidInvoice; not validator-backed.',
    properties: {
      reason: { type: 'string' },
    },
  },

  // ---- V2 billing money movement (payments/advances/refunds/reports) ----
  // Payment response reuses InvoiceV2Payment (billing_payments RETURNING *).
  PaymentV2Response: envelope('InvoiceV2Payment'),

  Advance: {
    type: 'object', additionalProperties: false,
    required: ['id', 'patient_uid', 'amount', 'balance', 'mode', 'collected_at', 'status', 'tenant_id', 'created_at', 'updated_at'],
    properties: {
      id: { type: 'integer' },
      patient_uid: { type: 'string', format: 'uuid' },
      admission_id: { type: 'integer', nullable: true },
      amount: { type: MT },
      balance: { type: MT },
      mode: { type: 'string' },
      reference: { type: 'string', nullable: true },
      collected_by: { type: 'string', format: 'uuid', nullable: true },
      collected_at: { type: 'string', format: 'date-time' },
      status: { type: 'string' },
      notes: { type: 'string', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  AdvanceResponse: envelope('Advance'),
  AdvancesListResponse: listEnvelope('Advance'),
  AdvanceSettlementResponse: envelope('AdvanceSettlement'),

  Refund: {
    type: 'object', additionalProperties: false,
    required: ['id', 'patient_uid', 'amount', 'reason', 'mode', 'approval_status', 'raised_at', 'tenant_id', 'created_at', 'updated_at'],
    properties: {
      id: { type: 'integer' },
      patient_uid: { type: 'string', format: 'uuid' },
      invoice_id: { type: 'integer', nullable: true },
      advance_id: { type: 'integer', nullable: true },
      amount: { type: MT },
      reason: { type: 'string' },
      mode: { type: 'string' },
      reference: { type: 'string', nullable: true },
      approval_status: { type: 'string', enum: ['PENDING', 'APPROVED', 'REJECTED', 'PAID'] },
      raised_by: { type: 'string', format: 'uuid', nullable: true },
      raised_at: { type: 'string', format: 'date-time' },
      approved_by: { type: 'string', format: 'uuid', nullable: true },
      approved_at: { type: 'string', format: 'date-time', nullable: true },
      rejected_by: { type: 'string', format: 'uuid', nullable: true },
      rejected_at: { type: 'string', format: 'date-time', nullable: true },
      rejection_reason: { type: 'string', nullable: true },
      paid_at: { type: 'string', format: 'date-time', nullable: true },
      paid_by: { type: 'string', format: 'uuid', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  RefundResponse: envelope('Refund'),
  RefundsListResponse: listEnvelope('Refund'),

  DailyCollectionV2Summary: {
    type: 'object', additionalProperties: false,
    required: ['mode', 'payment_count', 'net_amount', 'gross_amount'],
    properties: {
      mode: { type: 'string' },
      payment_count: { type: 'integer' },
      net_amount: { type: MT },
      gross_amount: { type: MT },
    },
  },
  DailyCollectionV2InsurerRow: {
    type: 'object', additionalProperties: false,
    required: ['payment_count', 'net_amount', 'gross_amount'],
    properties: {
      insurer: { type: 'string', nullable: true },
      policy_number: { type: 'string', nullable: true },
      claim_number: { type: 'string', nullable: true },
      payment_count: { type: 'integer' },
      net_amount: { type: MT },
      gross_amount: { type: MT },
    },
  },
  DailyCollectionV2Item: {
    type: 'object', additionalProperties: false,
    required: ['id', 'amount', 'mode', 'reversed'],
    properties: {
      id: { type: 'integer' },
      invoice_id: { type: 'integer', nullable: true },
      patient_uid: { type: 'string', format: 'uuid' },
      amount: { type: MT },
      mode: { type: 'string' },
      reference: { type: 'string', nullable: true },
      denominations: { nullable: true },
      collected_by: { type: 'string', format: 'uuid', nullable: true },
      shift: { type: 'string', nullable: true },
      collected_at: { type: 'string', format: 'date-time', nullable: true },
      reversed: { type: 'boolean' },
    },
  },
  DailyCollectionV2: {
    type: 'object', additionalProperties: false,
    required: ['date', 'summary', 'insurer_breakdown', 'items'],
    properties: {
      date: { type: 'string' },
      summary: { type: 'array', items: { $ref: '#/components/schemas/DailyCollectionV2Summary' } },
      insurer_breakdown: { type: 'array', items: { $ref: '#/components/schemas/DailyCollectionV2InsurerRow' } },
      items: { type: 'array', items: { $ref: '#/components/schemas/DailyCollectionV2Item' } },
    },
  },
  DailyCollectionV2Response: envelope('DailyCollectionV2'),

  OutstandingBill: {
    type: 'object', additionalProperties: false,
    required: ['id', 'patient_uid', 'total_amount', 'amount_paid', 'amount_due', 'status', 'days_outstanding'],
    properties: {
      id: { type: 'integer' },
      invoice_number: { type: 'string', nullable: true },
      patient_uid: { type: 'string', format: 'uuid' },
      patient_name: { type: 'string', nullable: true },
      patient_phone: { type: 'string', nullable: true },
      department: { type: 'string', nullable: true },
      total_amount: { type: MT },
      amount_paid: { type: MT },
      amount_due: { type: MT },
      status: { type: 'string' },
      issued_at: { type: 'string', format: 'date-time', nullable: true },
      days_outstanding: { type: 'integer' },
    },
  },
  OutstandingResponse: listEnvelope('OutstandingBill'),

  // V2 money-movement request bodies (no validators → permissive, known fields)
  CollectPaymentRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.collectPayment; not validator-backed. Requires X-Idempotency-Key header.',
    properties: {
      invoice_id: { type: 'integer' },
      patient_uid: { type: 'string', format: 'uuid' },
      amount: { type: 'number' },
      mode: { type: 'string' },
      reference: { type: 'string' },
      denominations: {},
      shift: { type: 'string' },
      notes: { type: 'string' },
    },
  },
  ReversePaymentRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.reversePayment; not validator-backed.',
    properties: { reason: { type: 'string' } },
  },
  CollectAdvanceRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.collectAdvance; not validator-backed. Requires X-Idempotency-Key header.',
    properties: {
      patient_uid: { type: 'string', format: 'uuid' },
      admission_id: { type: 'integer' },
      amount: { type: 'number' },
      mode: { type: 'string' },
      reference: { type: 'string' },
      collected_by: { type: 'string', format: 'uuid' },
      notes: { type: 'string' },
    },
  },
  SettleAdvanceRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.settleAdvance; not validator-backed. Requires X-Idempotency-Key header.',
    properties: {
      invoice_id: { type: 'integer' },
      amount: { type: 'number' },
    },
  },
  RaiseRefundRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.raiseRefund; not validator-backed.',
    properties: {
      patient_uid: { type: 'string', format: 'uuid' },
      invoice_id: { type: 'integer' },
      advance_id: { type: 'integer' },
      amount: { type: 'number' },
      reason: { type: 'string' },
      mode: { type: 'string' },
    },
  },
  RejectRefundRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.rejectRefund; not validator-backed.',
    properties: { rejection_reason: { type: 'string' } },
  },
  MarkRefundPaidRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingV2Service.markRefundPaid; not validator-backed. Requires X-Idempotency-Key header.',
    properties: { reference: { type: 'string' } },
  },

  // ---- V2 cash-drawer + payment-links (cashDrawerService / paymentLinkService) ----
  CashDrawerSession: {
    type: 'object', additionalProperties: false,
    required: ['id', 'tenant_id', 'cashier_uid', 'shift', 'opened_at', 'opening_float',
      'short_count', 'over_count', 'requires_review', 'status', 'created_at', 'updated_at'],
    properties: {
      id: { type: 'integer' },
      tenant_id: { type: 'string', format: 'uuid' },
      cashier_uid: { type: 'string', format: 'uuid' },
      shift: { type: 'string' },
      opened_at: { type: 'string', format: 'date-time' },
      opening_float: { type: MT },
      closed_at: { type: 'string', format: 'date-time', nullable: true },
      counted_total: { type: MT, nullable: true },
      counted_denominations: { type: 'object', additionalProperties: true, nullable: true },
      system_total: { type: MT, nullable: true },
      variance: { type: MT, nullable: true },
      short_count: { type: 'boolean' },
      over_count: { type: 'boolean' },
      requires_review: { type: 'boolean' },
      variance_reason: { type: 'string', nullable: true },
      status: { type: 'string' },
      reviewed_by: { type: 'string', format: 'uuid', nullable: true },
      reviewed_at: { type: 'string', format: 'date-time', nullable: true },
      review_notes: { type: 'string', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  CashDrawerSessionResponse: envelope('CashDrawerSession'),
  CashDrawerSessionsListResponse: listEnvelope('CashDrawerSession'),

  PaymentLink: {
    type: 'object', additionalProperties: false,
    required: ['id', 'link_token', 'patient_uid', 'amount', 'currency', 'provider', 'status', 'tenant_id', 'created_at', 'updated_at'],
    properties: {
      id: { type: 'integer' },
      link_token: { type: 'string' },
      invoice_id: { type: 'integer', nullable: true },
      patient_uid: { type: 'string', format: 'uuid' },
      amount: { type: MT },
      currency: { type: 'string' },
      upi_payee_vpa: { type: 'string', nullable: true },
      upi_payee_name: { type: 'string', nullable: true },
      upi_transaction_ref: { type: 'string', nullable: true },
      upi_deep_link: { type: 'string', nullable: true },
      provider: { type: 'string' },
      provider_invoice_id: { type: 'string', nullable: true },
      provider_payment_url: { type: 'string', nullable: true },
      status: { type: 'string' },
      expires_at: { type: 'string', format: 'date-time', nullable: true },
      notes: { type: 'string', nullable: true },
      linked_payment_id: { type: 'integer', nullable: true },
      paid_at: { type: 'string', format: 'date-time', nullable: true },
      paid_via: { type: 'string', nullable: true },
      paid_reference: { type: 'string', nullable: true },
      cancelled_at: { type: 'string', format: 'date-time', nullable: true },
      sent_via_whatsapp_at: { type: 'string', format: 'date-time', nullable: true },
      sent_via_sms_at: { type: 'string', format: 'date-time', nullable: true },
      sent_via_email_at: { type: 'string', format: 'date-time', nullable: true },
      created_by: { type: 'string', format: 'uuid', nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  PaymentLinkResponse: envelope('PaymentLink'),

  PaymentLinkListItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'link_token', 'patient_uid', 'amount', 'currency', 'provider', 'status', 'created_at'],
    properties: {
      id: { type: 'integer' },
      link_token: { type: 'string' },
      invoice_id: { type: 'integer', nullable: true },
      patient_uid: { type: 'string', format: 'uuid' },
      amount: { type: MT },
      currency: { type: 'string' },
      upi_deep_link: { type: 'string', nullable: true },
      provider: { type: 'string' },
      status: { type: 'string' },
      expires_at: { type: 'string', format: 'date-time', nullable: true },
      paid_at: { type: 'string', format: 'date-time', nullable: true },
      paid_via: { type: 'string', nullable: true },
      sent_via_whatsapp_at: { type: 'string', format: 'date-time', nullable: true },
      sent_via_sms_at: { type: 'string', format: 'date-time', nullable: true },
      sent_via_email_at: { type: 'string', format: 'date-time', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
    },
  },
  PaymentLinksListResponse: listEnvelope('PaymentLinkListItem'),

  // mark-paid returns { link, payment } (the link row + the created billing_payment).
  MarkLinkPaidResult: {
    type: 'object', additionalProperties: false,
    required: ['link', 'payment'],
    properties: {
      link: { $ref: '#/components/schemas/PaymentLink' },
      payment: { $ref: '#/components/schemas/InvoiceV2Payment' },
    },
  },
  MarkLinkPaidResponse: envelope('MarkLinkPaidResult'),

  ExpireStaleResult: {
    type: 'object', additionalProperties: false,
    required: ['expired'],
    properties: { expired: { type: 'integer' } },
  },
  ExpireStaleResponse: envelope('ExpireStaleResult'),

  // V2 cash-drawer + payment-link request bodies (permissive, known fields)
  OpenDrawerRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from cashDrawerService.openSession; not validator-backed.',
    properties: { shift: { type: 'string' }, opening_float: { type: 'number' }, cashier_uid: { type: 'string', format: 'uuid' } },
  },
  CloseDrawerRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from cashDrawerService.closeSession; not validator-backed.',
    properties: { counted_denominations: { type: 'object', additionalProperties: true }, variance_reason: { type: 'string' } },
  },
  ReviewDrawerRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from cashDrawerService.reviewSession; not validator-backed.',
    properties: { review_notes: { type: 'string' } },
  },
  CreatePaymentLinkRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from paymentLinkService.createPaymentLink; not validator-backed.',
    properties: {
      invoice_id: { type: 'integer' },
      patient_uid: { type: 'string', format: 'uuid' },
      amount: { type: 'number' },
      currency: { type: 'string' },
      provider: { type: 'string' },
      expires_in_hours: { type: 'number' },
      notes: { type: 'string' },
    },
  },
  SendPaymentLinkRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from paymentLinkService.sendPaymentLink; not validator-backed.',
    properties: {
      channels: { type: 'array', items: { type: 'string' } },
      patient_phone: { type: 'string' },
      patient_email: { type: 'string' },
    },
  },
  MarkLinkPaidRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from paymentLinkService.markPaymentLinkPaid; not validator-backed. Requires Idempotency-Key header.',
    properties: { paid_via: { type: 'string' }, paid_reference: { type: 'string' } },
  },
  CancelPaymentLinkRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from paymentLinkService.cancelPaymentLink; not validator-backed.',
    properties: { reason: { type: 'string' } },
  },

  // ---- Billing masters (billingMastersService.js) — *_minor are integer paise;
  //      tax_rate_pct / quantity are NUMERIC -> Decimal string; dates are 'YYYY-MM-DD' ----
  Payer: {
    type: 'object', additionalProperties: false,
    required: ['id', 'tenant_id', 'payer_code', 'display_name', 'payer_kind', 'status', 'metadata', 'created_at', 'updated_at'],
    properties: {
      id: { type: 'integer' },
      tenant_id: { type: 'string', format: 'uuid' },
      payer_code: { type: 'string' },
      display_name: { type: 'string' },
      payer_kind: { type: 'string' },
      registration_number: { type: 'string', nullable: true },
      contact_email: { type: 'string', nullable: true },
      contact_phone: { type: 'string', nullable: true },
      address: { type: 'string', nullable: true },
      status: { type: 'string' },
      ehr_external_id: { type: 'string', nullable: true },
      metadata: { type: 'object', additionalProperties: true },
      created_by: { type: 'string', format: 'uuid', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  PayerResponse: envelope('Payer'),
  PayersListResponse: countListEnvelope('payers', 'Payer'),

  Tpa: {
    type: 'object', additionalProperties: false,
    required: ['id', 'tenant_id', 'tpa_code', 'display_name', 'status', 'metadata', 'created_at', 'updated_at'],
    properties: {
      id: { type: 'integer' },
      tenant_id: { type: 'string', format: 'uuid' },
      tpa_code: { type: 'string' },
      display_name: { type: 'string' },
      parent_payer_id: { type: 'integer', nullable: true },
      irda_license_number: { type: 'string', nullable: true },
      contact_email: { type: 'string', nullable: true },
      contact_phone: { type: 'string', nullable: true },
      address: { type: 'string', nullable: true },
      status: { type: 'string' },
      ehr_external_id: { type: 'string', nullable: true },
      metadata: { type: 'object', additionalProperties: true },
      created_by: { type: 'string', format: 'uuid', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  TpaResponse: envelope('Tpa'),
  TpasListResponse: countListEnvelope('tpas', 'Tpa'),

  TariffPlan: {
    type: 'object', additionalProperties: false,
    required: ['id', 'tenant_id', 'plan_code', 'display_name', 'is_default', 'currency', 'status', 'metadata', 'created_at', 'updated_at'],
    properties: {
      id: { type: 'integer' },
      tenant_id: { type: 'string', format: 'uuid' },
      plan_code: { type: 'string' },
      display_name: { type: 'string' },
      description: { type: 'string', nullable: true },
      is_default: { type: 'boolean' },
      currency: { type: 'string' },
      effective_from: { type: 'string', nullable: true },
      effective_to: { type: 'string', nullable: true },
      status: { type: 'string' },
      metadata: { type: 'object', additionalProperties: true },
      created_by: { type: 'string', format: 'uuid', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  TariffPlanResponse: envelope('TariffPlan'),
  TariffPlansListResponse: countListEnvelope('plans', 'TariffPlan'),

  TariffItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'tenant_id', 'tariff_plan_id', 'service_code', 'service_kind', 'display_name', 'unit_price_minor', 'unit_label', 'taxable', 'metadata', 'created_at', 'updated_at'],
    properties: {
      id: { type: 'integer' },
      tenant_id: { type: 'string', format: 'uuid' },
      tariff_plan_id: { type: 'integer' },
      service_code: { type: 'string' },
      service_kind: { type: 'string' },
      display_name: { type: 'string' },
      unit_price_minor: { type: 'integer' },
      unit_label: { type: 'string' },
      taxable: { type: 'boolean' },
      tax_rate_pct: { type: 'string', nullable: true },
      effective_from: { type: 'string', nullable: true },
      effective_to: { type: 'string', nullable: true },
      metadata: { type: 'object', additionalProperties: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  TariffItemResponse: envelope('TariffItem'),
  TariffItemsListResponse: countListEnvelope('items', 'TariffItem'),

  BillingPackage: {
    type: 'object', additionalProperties: false,
    required: ['id', 'tenant_id', 'package_code', 'display_name', 'currency', 'status', 'metadata', 'created_at', 'updated_at'],
    properties: {
      id: { type: 'integer' },
      tenant_id: { type: 'string', format: 'uuid' },
      package_code: { type: 'string' },
      display_name: { type: 'string' },
      description: { type: 'string', nullable: true },
      base_specialty: { type: 'string', nullable: true },
      base_procedure_code: { type: 'string', nullable: true },
      duration_days: { type: 'integer', nullable: true },
      fixed_price_minor: { type: 'integer', nullable: true },
      currency: { type: 'string' },
      status: { type: 'string' },
      exclusion_notes: { type: 'string', nullable: true },
      inclusion_notes: { type: 'string', nullable: true },
      metadata: { type: 'object', additionalProperties: true },
      created_by: { type: 'string', format: 'uuid', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  BillingPackageResponse: envelope('BillingPackage'),
  PackagesListResponse: countListEnvelope('packages', 'BillingPackage'),

  PackageItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'tenant_id', 'package_id', 'service_code', 'service_kind', 'display_name', 'quantity', 'is_included', 'metadata', 'created_at', 'updated_at'],
    properties: {
      id: { type: 'integer' },
      tenant_id: { type: 'string', format: 'uuid' },
      package_id: { type: 'integer' },
      service_code: { type: 'string' },
      service_kind: { type: 'string' },
      display_name: { type: 'string' },
      quantity: { type: 'string' },
      unit_price_minor: { type: 'integer', nullable: true },
      is_included: { type: 'boolean' },
      notes: { type: 'string', nullable: true },
      metadata: { type: 'object', additionalProperties: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  PackageItemResponse: envelope('PackageItem'),
  PackageItemsListResponse: countListEnvelope('items', 'PackageItem'),

  PayerTariffLink: {
    type: 'object', additionalProperties: false,
    required: ['id', 'tenant_id', 'tariff_plan_id', 'is_primary', 'status', 'metadata', 'created_at', 'updated_at'],
    properties: {
      id: { type: 'integer' },
      tenant_id: { type: 'string', format: 'uuid' },
      payer_id: { type: 'integer', nullable: true },
      tpa_id: { type: 'integer', nullable: true },
      tariff_plan_id: { type: 'integer' },
      is_primary: { type: 'boolean' },
      effective_from: { type: 'string', nullable: true },
      effective_to: { type: 'string', nullable: true },
      status: { type: 'string' },
      metadata: { type: 'object', additionalProperties: true },
      created_by: { type: 'string', format: 'uuid', nullable: true },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  PayerTariffLinkResponse: envelope('PayerTariffLink'),
  PayerTariffLinksListResponse: countListEnvelope('links', 'PayerTariffLink'),

  ResolvedPrice: {
    type: 'object', additionalProperties: false,
    required: ['tariff_item_id', 'tariff_plan_id', 'service_code', 'service_kind', 'display_name', 'unit_price_minor', 'unit_label', 'taxable', 'plan_code', 'plan_display_name', 'is_primary'],
    properties: {
      tariff_item_id: { type: 'integer' },
      tariff_plan_id: { type: 'integer' },
      service_code: { type: 'string' },
      service_kind: { type: 'string' },
      display_name: { type: 'string' },
      unit_price_minor: { type: 'integer' },
      unit_label: { type: 'string' },
      taxable: { type: 'boolean' },
      tax_rate_pct: { type: 'string', nullable: true },
      plan_code: { type: 'string' },
      plan_display_name: { type: 'string' },
      payer_id: { type: 'integer', nullable: true },
      tpa_id: { type: 'integer', nullable: true },
      is_primary: { type: 'boolean' },
      link_effective_from: { type: 'string', nullable: true },
      link_effective_to: { type: 'string', nullable: true },
    },
  },
  // resolve-price returns data: ResolvedPrice | null (null when no match).
  ResolvePriceResponse: {
    type: 'object',
    required: ['success'],
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string' },
      data: { nullable: true, allOf: [{ $ref: '#/components/schemas/ResolvedPrice' }] },
    },
  },

  // Billing-masters request bodies (service-layer validation, no express-validator → permissive)
  UpsertPayerRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingMastersService.upsertPayer; service-layer validation, not express-validator.',
    properties: {
      id: { type: 'integer' }, payer_code: { type: 'string' }, display_name: { type: 'string' },
      payer_kind: { type: 'string' }, registration_number: { type: 'string' }, contact_email: { type: 'string' },
      contact_phone: { type: 'string' }, address: { type: 'string' }, status: { type: 'string' },
      ehr_external_id: { type: 'string' }, metadata: { type: 'object', additionalProperties: true },
    },
  },
  UpsertTpaRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingMastersService.upsertTpa; service-layer validation.',
    properties: {
      id: { type: 'integer' }, tpa_code: { type: 'string' }, display_name: { type: 'string' },
      parent_payer_id: { type: 'integer' }, irda_license_number: { type: 'string' }, contact_email: { type: 'string' },
      contact_phone: { type: 'string' }, address: { type: 'string' }, status: { type: 'string' },
      ehr_external_id: { type: 'string' }, metadata: { type: 'object', additionalProperties: true },
    },
  },
  UpsertTariffPlanRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingMastersService.upsertTariffPlan; service-layer validation.',
    properties: {
      id: { type: 'integer' }, plan_code: { type: 'string' }, display_name: { type: 'string' },
      description: { type: 'string' }, is_default: { type: 'boolean' }, currency: { type: 'string' },
      effective_from: { type: 'string' }, effective_to: { type: 'string' }, status: { type: 'string' },
      metadata: { type: 'object', additionalProperties: true },
    },
  },
  UpsertTariffItemRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingMastersService.upsertTariffItem; service-layer validation.',
    properties: {
      id: { type: 'integer' }, tariff_plan_id: { type: 'integer' }, service_code: { type: 'string' },
      service_kind: { type: 'string' }, display_name: { type: 'string' }, unit_price_minor: { type: 'integer' },
      unit_label: { type: 'string' }, taxable: { type: 'boolean' }, tax_rate_pct: { type: 'number' },
      effective_from: { type: 'string' }, effective_to: { type: 'string' }, metadata: { type: 'object', additionalProperties: true },
    },
  },
  UpsertPackageRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingMastersService.upsertPackage; service-layer validation.',
    properties: {
      id: { type: 'integer' }, package_code: { type: 'string' }, display_name: { type: 'string' },
      description: { type: 'string' }, base_specialty: { type: 'string' }, base_procedure_code: { type: 'string' },
      duration_days: { type: 'integer' }, fixed_price_minor: { type: 'integer' }, currency: { type: 'string' },
      status: { type: 'string' }, exclusion_notes: { type: 'string' }, inclusion_notes: { type: 'string' },
      metadata: { type: 'object', additionalProperties: true },
    },
  },
  AddPackageItemRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingMastersService.addPackageItem; service-layer validation.',
    properties: {
      service_code: { type: 'string' }, service_kind: { type: 'string' }, display_name: { type: 'string' },
      quantity: { type: 'number' }, unit_price_minor: { type: 'integer' }, is_included: { type: 'boolean' },
      notes: { type: 'string' }, metadata: { type: 'object', additionalProperties: true },
    },
  },
  LinkPayerTariffRequest: {
    type: 'object', additionalProperties: true,
    description: 'Reverse-engineered from billingMastersService.linkPayerTariff; service-layer validation.',
    properties: {
      payer_id: { type: 'integer' }, tpa_id: { type: 'integer' }, tariff_plan_id: { type: 'integer' },
      is_primary: { type: 'boolean' }, effective_from: { type: 'string' }, effective_to: { type: 'string' },
      status: { type: 'string' }, metadata: { type: 'object', additionalProperties: true },
    },
  },

  // ---- V1 billing revenue-cycle (revenueCycleRoutes.js) — money is ::float -> NUMBER ----
  ArAgingOverall: {
    type: 'object', additionalProperties: false,
    required: ['invoice_count', 'total_outstanding', 'oldest_age_days'],
    properties: {
      invoice_count: { type: 'integer' },
      total_outstanding: { type: 'number' },
      oldest_age_days: { type: 'integer' },
    },
  },
  ArAgingBucketRow: {
    type: 'object', additionalProperties: false,
    required: ['bucket', 'invoice_count', 'outstanding_amount'],
    properties: {
      bucket: { type: 'string', enum: ['0-30', '31-60', '61-90', '90+'] },
      invoice_count: { type: 'integer' },
      outstanding_amount: { type: 'number' },
    },
  },
  ArAgingInvoice: {
    type: 'object', additionalProperties: false,
    required: ['source', 'id', 'invoice_number', 'patient_uid', 'type', 'total_amount', 'paid_amount', 'outstanding_amount', 'issued_at', 'age_days'],
    properties: {
      source: { type: 'string' },
      id: { type: 'integer' },
      invoice_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      patient_name: { type: 'string', nullable: true },
      type: { type: 'string' },
      total_amount: { type: 'number' },
      paid_amount: { type: 'number' },
      outstanding_amount: { type: 'number' },
      issued_at: { type: 'string', format: 'date-time', nullable: true },
      age_days: { type: 'integer' },
      insurer_name: { type: 'string', nullable: true },
      claim_reference: { type: 'string', nullable: true },
    },
  },
  ArAgingSummary: {
    type: 'object', additionalProperties: false,
    required: ['as_of', 'overall', 'buckets', 'invoices'],
    properties: {
      as_of: { type: 'string', format: 'date-time' },
      overall: { $ref: '#/components/schemas/ArAgingOverall' },
      buckets: { type: 'array', items: { $ref: '#/components/schemas/ArAgingBucketRow' } },
      invoices: { type: 'array', items: { $ref: '#/components/schemas/ArAgingInvoice' } },
    },
  },
  ArAgingResponse: envelope('ArAgingSummary'),

  ClaimQueueSummaryRow: {
    type: 'object', additionalProperties: false,
    required: ['status', 'count', 'claim_amount', 'payer_balance'],
    properties: {
      status: { type: 'string' },
      count: { type: 'integer' },
      claim_amount: { type: 'number' },
      payer_balance: { type: 'number' },
    },
  },
  ClaimQueueItem: {
    type: 'object', additionalProperties: false,
    required: ['id', 'claim_number', 'patient_uid', 'insurance_provider', 'policy_number', 'claim_amount', 'payer_balance', 'status', 'submitted_at', 'days_in_queue'],
    properties: {
      id: { type: 'integer' },
      claim_number: { type: 'string' },
      patient_uid: { type: 'string', format: 'uuid' },
      patient_name: { type: 'string', nullable: true },
      invoice_id: { type: 'integer', nullable: true },
      invoice_number: { type: 'string', nullable: true },
      insurance_provider: { type: 'string' },
      policy_number: { type: 'string' },
      claim_amount: { type: 'number' },
      approved_amount: { type: 'number', nullable: true },
      payer_balance: { type: 'number' },
      status: { type: 'string' },
      submitted_at: { type: 'string', format: 'date-time' },
      reviewed_at: { type: 'string', format: 'date-time', nullable: true },
      rejection_reason: { type: 'string', nullable: true },
      days_in_queue: { type: 'integer' },
    },
  },
  ClaimQueue: {
    type: 'object', additionalProperties: false,
    required: ['statuses', 'summary', 'claims'],
    properties: {
      statuses: { type: 'array', items: { type: 'string' } },
      summary: { type: 'array', items: { $ref: '#/components/schemas/ClaimQueueSummaryRow' } },
      claims: { type: 'array', items: { $ref: '#/components/schemas/ClaimQueueItem' } },
    },
  },
  ClaimQueueResponse: envelope('ClaimQueue'),
};

export const operations = {
  'GET /api/v1/admin/ledger/trial-balance': { response: 'TrialBalanceResponse' },
  'GET /api/v1/admin/ledger/ar-aging': { response: 'AgingReportResponse' },
  'GET /api/v1/admin/ledger/insurer-aging': { response: 'AgingReportResponse' },
  'GET /api/v1/admin/ledger/cash-position': { response: 'CashPositionResponse' },
  'GET /api/v1/admin/ledger/daily-collection': { response: 'DailyCollectionResponse' },

  // V1 billing (billingService.js / billingRoutes.js)
  'POST /api/v1/billing/invoice': { request: 'CreateInvoiceRequest', response: 'InvoiceResponse' },
  'GET /api/v1/billing/invoice/{id}': { response: 'InvoiceDetailResponse' },
  'GET /api/v1/billing/invoices/patient/{patientUid}': { response: 'PatientInvoicesResponse' },
  'POST /api/v1/billing/invoice/{id}/payment': { request: 'RecordPaymentRequest', response: 'PaymentResultResponse' },
  'GET /api/v1/billing/revenue': { response: 'RevenueStatsResponse' },
  'POST /api/v1/billing/insurance/claim': { request: 'SubmitClaimRequest', response: 'InsuranceClaimResponse' },
  'GET /api/v1/billing/insurance/claims': { response: 'InsuranceClaimsResponse' },
  'PUT /api/v1/billing/insurance/claim/{id}': { request: 'UpdateClaimRequest', response: 'InsuranceClaimResponse' },
  'GET /api/v1/billing/ar-aging': { response: 'ArAgingResponse' },
  'GET /api/v1/billing/claim-queue': { response: 'ClaimQueueResponse' },
  // enhancement: request typed (validator-backed); response left generic — its
  // raw-SQL RETURNING shape isn't covered by a live test, so we don't assert it.
  'POST /api/v1/billing/insurance/claim/{id}/enhancement': { request: 'EnhancementClaimRequest' },

  // V2 billing invoices (billingV2Service.js). PDF endpoints omitted (binary).
  'GET /api/v1/billing/v2/services': { response: 'ServicesListResponse' },
  'POST /api/v1/billing/v2/services': { request: 'CreateServiceMasterRequest', response: 'ServiceMasterResponse' },
  'PATCH /api/v1/billing/v2/services/{id}': { request: 'UpdateServiceMasterRequest', response: 'ServiceMasterResponse' },
  'POST /api/v1/billing/v2/invoices': { request: 'CreateDraftInvoiceRequest', response: 'InvoiceV2Response' },
  'GET /api/v1/billing/v2/invoices': { response: 'InvoicesListResponse' },
  'GET /api/v1/billing/v2/invoices/{id}': { response: 'InvoiceV2DetailResponse' },
  'POST /api/v1/billing/v2/invoices/{id}/items': { request: 'AddInvoiceItemRequest', response: 'InvoiceItemResponse' },
  'DELETE /api/v1/billing/v2/invoices/{id}/items/{itemId}': { response: 'InvoiceTotalsResponse' },
  'POST /api/v1/billing/v2/invoices/{id}/itemize': { request: 'ItemizeRequest', response: 'ItemizeResultResponse' },
  'POST /api/v1/billing/v2/invoices/{id}/items/{itemId}/tpa-decision': { request: 'TpaDecisionRequest', response: 'TpaDecisionItemResponse' },
  'GET /api/v1/billing/v2/invoices/{id}/non-payable': { response: 'NonPayableBreakdownResponse' },
  'POST /api/v1/billing/v2/invoices/{id}/discount': { request: 'ApplyDiscountRequest', response: 'InvoiceTotalsResponse' },
  'POST /api/v1/billing/v2/invoices/{id}/issue': { response: 'InvoiceV2DetailResponse' },
  'POST /api/v1/billing/v2/invoices/{id}/void': { request: 'VoidInvoiceRequest', response: 'InvoiceV2DetailResponse' },

  // V2 money movement (payments/advances/refunds/reports)
  'POST /api/v1/billing/v2/payments': { request: 'CollectPaymentRequest', response: 'PaymentV2Response' },
  'POST /api/v1/billing/v2/payments/{id}/reverse': { request: 'ReversePaymentRequest', response: 'PaymentV2Response' },
  'POST /api/v1/billing/v2/advances': { request: 'CollectAdvanceRequest', response: 'AdvanceResponse' },
  'GET /api/v1/billing/v2/advances': { response: 'AdvancesListResponse' },
  'POST /api/v1/billing/v2/advances/{id}/settle': { request: 'SettleAdvanceRequest', response: 'AdvanceSettlementResponse' },
  'POST /api/v1/billing/v2/refunds': { request: 'RaiseRefundRequest', response: 'RefundResponse' },
  'GET /api/v1/billing/v2/refunds': { response: 'RefundsListResponse' },
  'POST /api/v1/billing/v2/refunds/{id}/approve': { response: 'RefundResponse' },
  'POST /api/v1/billing/v2/refunds/{id}/reject': { request: 'RejectRefundRequest', response: 'RefundResponse' },
  'POST /api/v1/billing/v2/refunds/{id}/pay': { request: 'MarkRefundPaidRequest', response: 'RefundResponse' },
  'GET /api/v1/billing/v2/reports/daily-collection': { response: 'DailyCollectionV2Response' },
  'GET /api/v1/billing/v2/reports/outstanding': { response: 'OutstandingResponse' },

  // V2 cash-drawer + payment-links
  'POST /api/v1/billing/v2/cash-drawer/sessions/open': { request: 'OpenDrawerRequest', response: 'CashDrawerSessionResponse' },
  'POST /api/v1/billing/v2/cash-drawer/sessions/{id}/close': { request: 'CloseDrawerRequest', response: 'CashDrawerSessionResponse' },
  'POST /api/v1/billing/v2/cash-drawer/sessions/{id}/review': { request: 'ReviewDrawerRequest', response: 'CashDrawerSessionResponse' },
  'GET /api/v1/billing/v2/cash-drawer/sessions': { response: 'CashDrawerSessionsListResponse' },
  'GET /api/v1/billing/v2/cash-drawer/sessions/{id}': { response: 'CashDrawerSessionResponse' },
  'POST /api/v1/billing/v2/payment-links': { request: 'CreatePaymentLinkRequest', response: 'PaymentLinkResponse' },
  'GET /api/v1/billing/v2/payment-links': { response: 'PaymentLinksListResponse' },
  'GET /api/v1/billing/v2/payment-links/{token}': { response: 'PaymentLinkResponse' },
  'POST /api/v1/billing/v2/payment-links/{token}/send': { request: 'SendPaymentLinkRequest', response: 'PaymentLinkResponse' },
  'POST /api/v1/billing/v2/payment-links/{token}/mark-paid': { request: 'MarkLinkPaidRequest', response: 'MarkLinkPaidResponse' },
  'POST /api/v1/billing/v2/payment-links/{token}/cancel': { request: 'CancelPaymentLinkRequest', response: 'PaymentLinkResponse' },
  'POST /api/v1/billing/v2/payment-links/run-expire-stale': { response: 'ExpireStaleResponse' },

  // Billing masters (billingMastersService.js)
  'PUT /api/v1/admin/billing-masters/payers': { request: 'UpsertPayerRequest', response: 'PayerResponse' },
  'GET /api/v1/admin/billing-masters/payers': { response: 'PayersListResponse' },
  'PUT /api/v1/admin/billing-masters/tpas': { request: 'UpsertTpaRequest', response: 'TpaResponse' },
  'GET /api/v1/admin/billing-masters/tpas': { response: 'TpasListResponse' },
  'PUT /api/v1/admin/billing-masters/tariff-plans': { request: 'UpsertTariffPlanRequest', response: 'TariffPlanResponse' },
  'GET /api/v1/admin/billing-masters/tariff-plans': { response: 'TariffPlansListResponse' },
  'PUT /api/v1/admin/billing-masters/tariff-items': { request: 'UpsertTariffItemRequest', response: 'TariffItemResponse' },
  'GET /api/v1/admin/billing-masters/tariff-plans/{planId}/items': { response: 'TariffItemsListResponse' },
  'PUT /api/v1/admin/billing-masters/packages': { request: 'UpsertPackageRequest', response: 'BillingPackageResponse' },
  'GET /api/v1/admin/billing-masters/packages': { response: 'PackagesListResponse' },
  'POST /api/v1/admin/billing-masters/packages/{packageId}/items': { request: 'AddPackageItemRequest', response: 'PackageItemResponse' },
  'GET /api/v1/admin/billing-masters/packages/{packageId}/items': { response: 'PackageItemsListResponse' },
  'POST /api/v1/admin/billing-masters/payer-tariff-links': { request: 'LinkPayerTariffRequest', response: 'PayerTariffLinkResponse' },
  'GET /api/v1/admin/billing-masters/payer-tariff-links': { response: 'PayerTariffLinksListResponse' },
  'GET /api/v1/admin/billing-masters/resolve-price': { response: 'ResolvePriceResponse' },
};
