import { envelope } from './_helpers.mjs';

const nullableDateTime = { type: 'string', format: 'date-time', nullable: true };
const nullableUuid = { type: 'string', format: 'uuid', nullable: true };
const bigintId = { type: 'string', pattern: '^[1-9][0-9]*$' };
const reasonRequest = {
  type: 'object',
  additionalProperties: false,
  required: ['reason'],
  properties: {
    reason: { type: 'string', minLength: 1, maxLength: 1000 },
  },
};

export const schemas = {
  OutboxReasonRequest: reasonRequest,
  EventOutboxRow: {
    type: 'object',
    additionalProperties: true,
    required: ['id', 'event_type', 'aggregate_type', 'status', 'attempts', 'redrive_count'],
    properties: {
      id: bigintId,
      event_type: { type: 'string', minLength: 1, maxLength: 120 },
      aggregate_type: { type: 'string', minLength: 1, maxLength: 80 },
      aggregate_id: { type: 'string', nullable: true, maxLength: 120 },
      patient_uid: nullableUuid,
      payload: { type: 'object', additionalProperties: true },
      status: { type: 'string', enum: ['pending', 'processing', 'delivered', 'failed'] },
      attempts: { type: 'integer', minimum: 0 },
      available_at: { type: 'string', format: 'date-time' },
      last_error: { type: 'string', nullable: true },
      delivered_at: nullableDateTime,
      lease_owner: nullableUuid,
      lease_expires_at: nullableDateTime,
      redrive_count: { type: 'integer', minimum: 0 },
      created_at: { type: 'string', format: 'date-time' },
    },
  },
  EventOutboxList: {
    type: 'object',
    additionalProperties: false,
    required: ['events', 'count'],
    properties: {
      events: { type: 'array', items: { $ref: '#/components/schemas/EventOutboxRow' } },
      count: { type: 'integer', minimum: 0 },
    },
  },
  EventOutboxListResponse: envelope('EventOutboxList'),
  EventOutboxRowResponse: envelope('EventOutboxRow'),

  WebhookDeliveryRow: {
    type: 'object',
    additionalProperties: true,
    required: ['id', 'event_type', 'status', 'attempt_number', 'redrive_count'],
    properties: {
      id: { type: 'integer', minimum: 1 },
      subscription_id: { type: 'integer', minimum: 1, nullable: true },
      tenant_id: { type: 'string', format: 'uuid' },
      event_outbox_id: { ...bigintId, nullable: true },
      event_type: { type: 'string', minLength: 1, maxLength: 120 },
      payload: { type: 'object', additionalProperties: true },
      status: { type: 'string', enum: ['pending', 'in_flight', 'succeeded', 'failed', 'dead'] },
      attempt_number: { type: 'integer', minimum: 0 },
      http_status: { type: 'integer', nullable: true, minimum: 100, maximum: 599 },
      response_excerpt: { type: 'string', nullable: true, maxLength: 2000 },
      error_message: { type: 'string', nullable: true },
      request_id: { type: 'string', nullable: true, maxLength: 64 },
      started_at: nullableDateTime,
      completed_at: nullableDateTime,
      next_retry_at: nullableDateTime,
      lease_owner: nullableUuid,
      lease_expires_at: nullableDateTime,
      redrive_count: { type: 'integer', minimum: 0 },
      created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  WebhookDeliveryList: {
    type: 'object',
    additionalProperties: false,
    required: ['deliveries', 'count'],
    properties: {
      deliveries: { type: 'array', items: { $ref: '#/components/schemas/WebhookDeliveryRow' } },
      count: { type: 'integer', minimum: 0 },
    },
  },
  WebhookDeliveryListResponse: envelope('WebhookDeliveryList'),
  WebhookDeliveryRowResponse: envelope('WebhookDeliveryRow'),
  WebhookEnqueueRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['event_type'],
    properties: {
      event_type: { type: 'string', minLength: 1, maxLength: 120 },
      payload: { type: 'object', additionalProperties: true },
      request_id: { type: 'string', minLength: 1, maxLength: 64 },
    },
  },
  WebhookEnqueueResult: {
    type: 'object',
    additionalProperties: false,
    required: ['matched', 'enqueued'],
    properties: {
      matched: { type: 'integer', minimum: 0 },
      enqueued: { type: 'array', items: { $ref: '#/components/schemas/WebhookDeliveryRow' } },
    },
  },
  WebhookEnqueueResponse: envelope('WebhookEnqueueResult'),
  WebhookDispatchRequest: {
    type: 'object',
    additionalProperties: false,
    properties: {
      batch_size: { type: 'integer', minimum: 1, maximum: 200 },
    },
  },
  WebhookDispatchResult: {
    type: 'object',
    additionalProperties: false,
    required: ['dispatched', 'succeeded', 'failed', 'dead', 'parked', 'lost_fence', 'orphaned'],
    properties: {
      dispatched: { type: 'integer', minimum: 0 },
      succeeded: { type: 'integer', minimum: 0 },
      failed: { type: 'integer', minimum: 0 },
      dead: { type: 'integer', minimum: 0 },
      parked: { type: 'integer', minimum: 0 },
      lost_fence: { type: 'integer', minimum: 0 },
      orphaned: { type: 'integer', minimum: 0 },
    },
  },
  WebhookDispatchResponse: envelope('WebhookDispatchResult'),

  NotificationOutboxRow: {
    type: 'object',
    additionalProperties: true,
    required: ['id', 'type', 'channel', 'status', 'retry_count'],
    properties: {
      id: { type: 'integer', minimum: 1 },
      type: { type: 'string', maxLength: 80 },
      channel: { type: 'string', enum: ['push', 'email', 'inapp', 'whatsapp', 'voice', 'sms', 'print'] },
      status: {
        type: 'string',
        enum: ['PENDING', 'CLAIMED', 'SENT', 'FAILED', 'RECONCILIATION_REQUIRED', 'SUPPRESSED'],
      },
      recipient_id: { type: 'string', nullable: true, maxLength: 320 },
      recipient_phone: { type: 'string', nullable: true, maxLength: 32 },
      title: { type: 'string', nullable: true },
      source_event_key: { type: 'string', maxLength: 255 },
      recipient_key: { type: 'string', maxLength: 320 },
      template_version: { type: 'string', maxLength: 80 },
      retry_count: { type: 'integer', minimum: 0 },
      failure_reason: { type: 'string', nullable: true, maxLength: 500 },
      created_at: { type: 'string', format: 'date-time' },
      last_attempt_at: nullableDateTime,
      sent_at: nullableDateTime,
      lease_expires_at: nullableDateTime,
      delivery_attempts: {
        type: 'array',
        items: { $ref: '#/components/schemas/NotificationDeliveryAttemptEvidence' },
      },
      dead_letter: { type: 'boolean' },
    },
  },
  NotificationDeliveryAttemptEvidence: {
    type: 'object',
    additionalProperties: false,
    required: ['attempt_id', 'channel', 'provider', 'attempt_number', 'started_at'],
    properties: {
      attempt_id: { type: 'string', format: 'uuid' },
      channel: { type: 'string', enum: ['push', 'email', 'inapp', 'whatsapp', 'voice', 'sms', 'print'] },
      provider: { type: 'string', maxLength: 40 },
      attempt_number: { type: 'integer', minimum: 1 },
      started_at: { type: 'string', format: 'date-time' },
      receipt_id: nullableUuid,
      outcome: { type: 'string', enum: ['acknowledged', 'rejected', 'uncertain'], nullable: true },
      receipt_source: { type: 'string', nullable: true, maxLength: 32 },
      provider_reference: { type: 'string', nullable: true, maxLength: 255 },
      provider_code: { type: 'string', nullable: true, maxLength: 120 },
      evidence: { type: 'object', additionalProperties: true, nullable: true },
      observed_at: nullableDateTime,
      owner_actor_uid: nullableUuid,
      owner_reason: { type: 'string', nullable: true, maxLength: 500 },
    },
  },
  NotificationOutboxList: {
    type: 'object',
    additionalProperties: false,
    required: ['rows', 'count'],
    properties: {
      rows: { type: 'array', items: { $ref: '#/components/schemas/NotificationOutboxRow' } },
      count: { type: 'integer', minimum: 0 },
    },
  },
  NotificationOutboxListResponse: envelope('NotificationOutboxList'),
  NotificationOutboxReplayResult: {
    type: 'object',
    additionalProperties: false,
    required: ['mode', 'row'],
    properties: {
      mode: { type: 'string', enum: ['retry_reset', 'requeued_new_intent'] },
      row: { $ref: '#/components/schemas/NotificationOutboxRow' },
      replacement_id: { type: 'integer', minimum: 1, nullable: true },
    },
  },
  NotificationOutboxReplayResponse: envelope('NotificationOutboxReplayResult'),
  NotificationOutboxReconcileRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['attempt_id', 'provider_reference', 'evidence', 'reason'],
    properties: {
      attempt_id: { type: 'string', format: 'uuid' },
      provider_reference: { type: 'string', minLength: 1, maxLength: 255 },
      evidence: { type: 'object', additionalProperties: true, minProperties: 1 },
      reason: { type: 'string', minLength: 1, maxLength: 500 },
    },
  },
  NotificationOutboxReconcileResult: {
    type: 'object',
    additionalProperties: false,
    required: ['row', 'receipt', 'cursor', 'fully_reconciled'],
    properties: {
      row: { $ref: '#/components/schemas/NotificationOutboxRow' },
      receipt: { type: 'object', additionalProperties: true },
      cursor: { $ref: '#/components/schemas/NotificationDeliveryCursorRow' },
      fully_reconciled: { type: 'boolean' },
    },
  },
  NotificationOutboxReconcileResponse: envelope('NotificationOutboxReconcileResult'),
  NotificationDeliveryCursorRow: {
    type: 'object',
    additionalProperties: true,
    required: ['channel', 'state'],
    properties: {
      tenant_id: { type: 'string', format: 'uuid' },
      channel: { type: 'string', enum: ['push', 'email', 'inapp', 'whatsapp', 'voice', 'sms', 'print'] },
      last_contiguous_outbox_id: { type: 'integer', minimum: 1, nullable: true },
      state: { type: 'string', enum: ['ready', 'delivering', 'paused_rejected', 'paused_uncertain'] },
      blocked_outbox_id: { type: 'integer', minimum: 1, nullable: true },
      inflight_outbox_id: { type: 'integer', minimum: 1, nullable: true },
      updated_at: { type: 'string', format: 'date-time' },
    },
  },
  NotificationDeliveryCursorList: {
    type: 'object',
    additionalProperties: false,
    required: ['cursors', 'count'],
    properties: {
      cursors: { type: 'array', items: { $ref: '#/components/schemas/NotificationDeliveryCursorRow' } },
      count: { type: 'integer', minimum: 0 },
    },
  },
  NotificationDeliveryCursorListResponse: envelope('NotificationDeliveryCursorList'),
  NotificationDeliveryCursorResponse: envelope('NotificationDeliveryCursorRow'),
};

export const operations = {
  'GET /api/v1/admin/events': {
    response: 'EventOutboxListResponse',
    parameters: [
      {
        name: 'status',
        in: 'query',
        required: false,
        schema: { type: 'string', enum: ['pending', 'processing', 'delivered', 'failed'], default: 'pending' },
      },
      { name: 'limit', in: 'query', required: false, schema: { type: 'integer', minimum: 1, maximum: 200, default: 50 } },
      { name: 'offset', in: 'query', required: false, schema: { type: 'integer', minimum: 0, maximum: 10000, default: 0 } },
    ],
  },
  'POST /api/v1/admin/events/{id}/redrive': {
    pathParameters: { id: bigintId },
    request: 'OutboxReasonRequest',
    response: 'EventOutboxRowResponse',
  },
  'GET /api/v1/admin/webhook-deliveries': {
    response: 'WebhookDeliveryListResponse',
  },
  'POST /api/v1/admin/webhook-deliveries/enqueue': {
    request: 'WebhookEnqueueRequest',
    response: 'WebhookEnqueueResponse',
    responseStatus: 201,
  },
  'POST /api/v1/admin/webhook-deliveries/dispatch-now': {
    request: 'WebhookDispatchRequest',
    requestRequired: false,
    response: 'WebhookDispatchResponse',
    responseStatus: 201,
  },
  'GET /api/v1/admin/webhook-deliveries/{id}': {
    pathParameters: { id: { type: 'integer', minimum: 1 } },
    response: 'WebhookDeliveryRowResponse',
  },
  'PATCH /api/v1/admin/webhook-deliveries/{id}/mark-dead': {
    pathParameters: { id: { type: 'integer', minimum: 1 } },
    request: 'OutboxReasonRequest',
    response: 'WebhookDeliveryRowResponse',
  },
  'POST /api/v1/admin/webhook-deliveries/{id}/redrive': {
    pathParameters: { id: { type: 'integer', minimum: 1 } },
    request: 'OutboxReasonRequest',
    response: 'WebhookDeliveryRowResponse',
    responseStatus: 201,
  },
  'GET /api/v1/admin/notification-outbox': {
    summary: 'List notification outbox rows by status',
    description: 'Tenant-scoped listing of notification_outbox rows (default status FAILED). FAILED rows with retry_count >= 3 and all RECONCILIATION_REQUIRED rows are dead letters no automatic path will retry.',
    response: 'NotificationOutboxListResponse',
    parameters: [
      {
        name: 'status',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['PENDING', 'CLAIMED', 'SENT', 'FAILED', 'RECONCILIATION_REQUIRED', 'SUPPRESSED'],
          default: 'FAILED',
        },
      },
      { name: 'limit', in: 'query', required: false, schema: { type: 'integer', minimum: 1, maximum: 200, default: 50 } },
      { name: 'offset', in: 'query', required: false, schema: { type: 'integer', minimum: 0, maximum: 10000, default: 0 } },
    ],
  },
  'POST /api/v1/admin/notification-outbox/{id}/replay': {
    summary: 'Replay a dead-lettered notification outbox row',
    description: 'Operator replay with a required reason. A FAILED row has its retry budget reset in place; a RECONCILIATION_REQUIRED row (original provider state unknowable) is superseded by a NEW outbox intent — the operator explicitly accepts duplicate-delivery risk. Audited to audit_logs.',
    pathParameters: { id: { type: 'integer', minimum: 1 } },
    request: 'OutboxReasonRequest',
    response: 'NotificationOutboxReplayResponse',
  },
  'POST /api/v1/admin/notification-outbox/{id}/reconcile': {
    summary: 'Record verified provider acceptance for a notification attempt',
    description: 'Appends actor-attributed provider acceptance evidence for one current uncertain or rejected attempt. Advances only the exact paused channel cursor and marks the outbox row sent only after every current channel attempt is acknowledged. Audited to audit_logs.',
    pathParameters: { id: { type: 'integer', minimum: 1 } },
    request: 'NotificationOutboxReconcileRequest',
    response: 'NotificationOutboxReconcileResponse',
  },
  'GET /api/v1/admin/notification-outbox/cursors': {
    summary: 'List notification delivery channel cursors',
    description: 'Per-channel delivery cursors for the tenant, including paused_rejected / paused_uncertain states that block the channel.',
    response: 'NotificationDeliveryCursorListResponse',
  },
  'POST /api/v1/admin/notification-outbox/cursors/{channel}/reset': {
    summary: 'Reset a paused notification delivery cursor',
    description: 'Operator un-pause for a wedged channel cursor (paused_rejected / paused_uncertain / stuck delivering). Requires a reason; audited to audit_logs. last_contiguous_outbox_id is never moved by this operation.',
    pathParameters: {
      channel: { type: 'string', enum: ['push', 'email', 'inapp', 'whatsapp', 'voice', 'sms', 'print'] },
    },
    request: 'OutboxReasonRequest',
    response: 'NotificationDeliveryCursorResponse',
  },
};
