// src/app/api/login/mfa/setup-confirm/route.ts
//
// Second leg of first-time SUPER_ADMIN MFA enrollment. The client holds the
// setup token from /api/login plus the encryptedSecret + backupCodes + the
// 6-digit code generated by the authenticator app. On success the backend
// returns a standard full-access JWT which we install as the auth_token
// cookie — identical to the non-MFA login flow.

import { NextResponse } from "next/server";

const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_URL || "https://api.vhhealth.app";
const SERVER_API_KEY = process.env.BACKEND_API_KEY || process.env.API_KEY || "";

function validateOrigin(request: Request): NextResponse | null {
  const origin = request.headers.get("origin");
  const allowed = process.env.NEXT_PUBLIC_ALLOWED_ORIGIN || "http://localhost:3000";
  if (origin && origin !== allowed) {
    const allowedHosts = allowed.split(",").map((s: string) => s.trim());
    const originHost = new URL(origin).origin;
    const isAllowed = allowedHosts.some((h: string) => {
      if (h === origin) return true;
      if (h.startsWith("https://") && h.endsWith(".vhhealth.app")) {
        return originHost === h;
      }
      return false;
    });
    if (!isAllowed) {
      return NextResponse.json(
        { message: "Forbidden: Origin not allowed", success: false },
        { status: 403 },
      );
    }
  }
  return null;
}

export async function POST(request: Request) {
  const csrfError = validateOrigin(request);
  if (csrfError) return csrfError;

  const body = await request.json().catch(() => null);
  if (!body?.setupToken || !body?.code || !body?.encryptedSecret || !Array.isArray(body?.backupCodes)) {
    return NextResponse.json(
      {
        message:
          "setupToken, code, encryptedSecret, and backupCodes are required",
        success: false,
      },
      { status: 400 },
    );
  }

  try {
    const upstream = await fetch(
      `${API_BASE_URL}/api/v1/auth/admin/mfa/setup-confirm`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${body.setupToken}`,
          ...(SERVER_API_KEY ? { "x-api-key": SERVER_API_KEY } : {}),
        },
        body: JSON.stringify({
          code: body.code,
          encryptedSecret: body.encryptedSecret,
          backupCodes: body.backupCodes,
        }),
      },
    );

    const data = await upstream.json();
    if (!upstream.ok) {
      return NextResponse.json(
        { message: data?.message ?? "Failed to complete MFA setup", success: false },
        { status: upstream.status },
      );
    }

    const token = data?.data?.token ?? data?.token;
    if (!token) {
      return NextResponse.json(
        { message: "No token in setup-confirm response", success: false },
        { status: 502 },
      );
    }

    const response = NextResponse.json(data);
    response.cookies.set("auth_token", token, {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "strict",
      path: "/",
      maxAge: 60 * 60 * 4,
    });
    return response;
  } catch {
    return NextResponse.json(
      { message: "MFA setup service unavailable", success: false },
      { status: 502 },
    );
  }
}
