// src/app/api/login/mfa/setup-confirm/route.ts
//
// Second leg of first-time SUPER_ADMIN MFA enrollment. The client holds the
// setup token from /api/login plus the encryptedSecret + backupCodes + the
// 6-digit code generated by the authenticator app. On success the backend
// returns a standard full-access JWT which we install as the auth_token
// cookie — identical to the non-MFA login flow.

import { NextResponse } from "next/server";
import { getServerBackendUrl } from "@/lib/api-config";
import { assertSameOriginOrAllowed } from "@/lib/csrfOrigin";

const API_BASE_URL = getServerBackendUrl();
const SERVER_API_KEY = process.env.BACKEND_API_KEY || process.env.API_KEY || "";

/**
 * Remove JWT material (`token`, `accessToken`, `refreshToken`) from a backend
 * response envelope before it is returned to the browser. The token is carried
 * exclusively by the httpOnly `auth_token` cookie. Strips both the top level
 * and the nested `data` object (the standard envelope shape).
 */
function stripTokens(responseBody: unknown): unknown {
  if (!responseBody || typeof responseBody !== "object") return responseBody;

  const omit = (obj: Record<string, unknown>): Record<string, unknown> => {
    const { token, accessToken, refreshToken, ...rest } = obj;
    void token;
    void accessToken;
    void refreshToken;
    return rest;
  };

  const top = omit(responseBody as Record<string, unknown>);
  if (top.data && typeof top.data === "object") {
    top.data = omit(top.data as Record<string, unknown>);
  }
  return top;
}

export async function POST(request: Request) {
  const csrfError = assertSameOriginOrAllowed(request);
  if (csrfError) return csrfError;

  const body = await request.json().catch(() => null);
  if (!body?.setupToken || !body?.code || !body?.encryptedSecret || !Array.isArray(body?.backupCodes)) {
    return NextResponse.json(
      {
        message:
          "setupToken, code, encryptedSecret, and backupCodes are required",
        success: false,
      },
      { status: 400 },
    );
  }

  try {
    const upstream = await fetch(
      `${API_BASE_URL}/api/v1/auth/admin/mfa/setup-confirm`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${body.setupToken}`,
          "x-forwarded-proto": "https",
          ...(SERVER_API_KEY ? { "x-api-key": SERVER_API_KEY } : {}),
        },
        body: JSON.stringify({
          code: body.code,
          encryptedSecret: body.encryptedSecret,
          backupCodes: body.backupCodes,
        }),
      },
    );

    const data = await upstream.json();
    if (!upstream.ok) {
      return NextResponse.json(
        { message: data?.message ?? "Failed to complete MFA setup", success: false },
        { status: upstream.status },
      );
    }

    const token = data?.data?.token ?? data?.token;
    if (!token) {
      return NextResponse.json(
        { message: "No token in setup-confirm response", success: false },
        { status: 502 },
      );
    }

    // The token is the credential and now lives only in the httpOnly cookie set
    // below — strip it from the JSON body so the browser never receives it.
    const response = NextResponse.json(stripTokens(data));
    response.cookies.set("auth_token", token, {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "strict",
      path: "/",
      maxAge: 60 * 60 * 4,
    });
    return response;
  } catch {
    return NextResponse.json(
      { message: "MFA setup service unavailable", success: false },
      { status: 502 },
    );
  }
}
