import express from 'express';
import overviewRoutes from './clinicalAi/overviewRoutes.js';
import governanceRoutes from './clinicalAi/governanceRoutes.js';
import outcomeScoreboardRoutes from './clinicalAi/outcomeScoreboardRoutes.js';
import documentRoutes from './clinicalAi/documentRoutes.js';
import coreClinicalRoutes from './clinicalAi/coreClinicalRoutes.js';
import careOperationsRoutes from './clinicalAi/careOperationsRoutes.js';
import revenueCycleRoutes from './clinicalAi/revenueCycleRoutes.js';
import diagnosticsMedicationRoutes from './clinicalAi/diagnosticsMedicationRoutes.js';
import facilityRiskRoutes from './clinicalAi/facilityRiskRoutes.js';
import platformWorkbenchRoutes from './clinicalAi/platformWorkbenchRoutes.js';
import knowledgeBaseRoutes from './clinicalAi/knowledgeBaseRoutes.js';
import knowledgeGovernanceRoutes from './clinicalAi/knowledgeGovernanceRoutes.js';
import patientExplainersRoutes from './clinicalAi/patientExplainersRoutes.js';
import tierAAssistantsRoutes from './clinicalAi/tierAAssistantsRoutes.js';
import tierCAssistantsRoutes from './clinicalAi/tierCAssistantsRoutes.js';
import tierDEmergencyRoutes from './clinicalAi/tierDEmergencyRoutes.js';
import tierEPatientEngagementRoutes from './clinicalAi/tierEPatientEngagementRoutes.js';
import tierFInteropRoutes from './clinicalAi/tierFInteropRoutes.js';
import tierGPublicHealthRoutes from './clinicalAi/tierGPublicHealthRoutes.js';
import tierHOperationalRoutes from './clinicalAi/tierHOperationalRoutes.js';
import surgicalAiRoutes from './clinicalAi/surgicalAiRoutes.js';
import teleconsultAiRoutes from './clinicalAi/teleconsultAiRoutes.js';
import trialSafetyOperationsRoutes from './clinicalAi/trialSafetyOperationsRoutes.js';
import dischargeComposeRoutes from './clinicalAi/dischargeComposeRoutes.js';
import priorAuthAppealRoutes from './clinicalAi/priorAuthAppealRoutes.js';
import { requireClinicalAiControl } from './clinicalAi/shared.js';

const router = express.Router();

router.use(requireClinicalAiControl);
router.use('/', overviewRoutes);
router.use('/', governanceRoutes);
router.use('/', outcomeScoreboardRoutes);
router.use('/', documentRoutes);
router.use('/', coreClinicalRoutes);
router.use('/', careOperationsRoutes);
router.use('/', revenueCycleRoutes);
router.use('/', diagnosticsMedicationRoutes);
router.use('/', facilityRiskRoutes);
router.use('/', platformWorkbenchRoutes);
router.use('/', knowledgeBaseRoutes);
router.use('/', knowledgeGovernanceRoutes);
router.use('/', patientExplainersRoutes);
router.use('/', tierAAssistantsRoutes);
router.use('/', tierCAssistantsRoutes);
router.use('/', tierDEmergencyRoutes);
router.use('/', tierEPatientEngagementRoutes);
router.use('/', tierFInteropRoutes);
router.use('/', tierGPublicHealthRoutes);
router.use('/', tierHOperationalRoutes);
router.use('/', surgicalAiRoutes);
router.use('/', teleconsultAiRoutes);
router.use('/', trialSafetyOperationsRoutes);
router.use('/', dischargeComposeRoutes);
router.use('/', priorAuthAppealRoutes);

export default router;
