"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "react-hot-toast";
import {
  getPayrollRunDetail,
  getPayrollRuns,
  issuePayslips,
  runPayroll,
  type Payslip,
  type PayrollRun,
} from "@/lib/api/payroll";
import { Modal } from "./Modal";
import { RunActions } from "./RunActions";
import { fmtCurrency, fmtMonth, MONTHS, statusBadge, unwrap } from "./helpers";

export function PayrollRunsTab() {
  const qc = useQueryClient();
  const [showRunModal, setShowRunModal] = useState(false);
  const [selectedRun, setSelectedRun] = useState<number | null>(null);
  const [runMonth, setRunMonth] = useState(new Date().getMonth() + 1);
  const [runYear, setRunYear] = useState(new Date().getFullYear());

  const { data: runsRaw, isLoading: runsLoading } = useQuery({
    queryKey: ["payroll-runs"],
    queryFn: () => getPayrollRuns(),
  });
  const runs = unwrap<PayrollRun[]>(runsRaw) ?? [];

  const { data: detailRaw, isLoading: detailLoading } = useQuery({
    queryKey: ["payroll-run-detail", selectedRun],
    queryFn: () => getPayrollRunDetail(selectedRun!),
    enabled: !!selectedRun,
  });
  const detail = unwrap<{ run: PayrollRun; payslips: Payslip[] }>(detailRaw);

  const runMut = useMutation({
    mutationFn: (data: { month: number; year: number }) => runPayroll(data),
    onSuccess: () => {
      toast.success("Payroll run complete");
      qc.invalidateQueries({ queryKey: ["payroll-runs"] });
      setShowRunModal(false);
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const issueMut = useMutation({
    mutationFn: (data: { month: number; year: number }) => issuePayslips(data),
    onSuccess: (r) => {
      const count = (unwrap<{ issued: number }>(r))?.issued ?? 0;
      toast.success(`${count} payslips issued to staff`);
      qc.invalidateQueries({ queryKey: ["payroll-runs"] });
      qc.invalidateQueries({ queryKey: ["payroll-run-detail"] });
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const thisYear = new Date().getFullYear();
  const yearOptions = [thisYear - 1, thisYear, thisYear + 1];

  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <h2 className="font-bold text-lg text-gray-800">Payroll Runs</h2>
        <button
          onClick={() => setShowRunModal(true)}
          className="bg-teal-700 text-white px-4 py-2 rounded-lg text-sm font-semibold hover:bg-teal-800 transition-colors"
        >
          + Run Payroll
        </button>
      </div>

      {/* Runs table */}
      {runsLoading ? (
        <div className="text-center py-10 text-gray-400">Loading...</div>
      ) : runs.length === 0 ? (
        <div className="text-center py-10 text-gray-400">No payroll runs yet</div>
      ) : (
        <div className="overflow-x-auto rounded-xl border border-gray-200">
          <table className="min-w-full divide-y divide-gray-200 text-sm">
            <thead className="bg-gray-50">
              <tr>
                {["Month", "Year", "Staff", "Gross", "Net", "Status", "Generated By", "Actions"].map((h) => (
                  <th key={h} className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 bg-white">
              {runs.map((run) => (
                <tr key={run.id} className="hover:bg-gray-50 cursor-pointer" onClick={() => setSelectedRun(run.id)}>
                  <td className="px-4 py-3 font-medium">{fmtMonth(run.month)}</td>
                  <td className="px-4 py-3">{run.year}</td>
                  <td className="px-4 py-3">{run.total_staff}</td>
                  <td className="px-4 py-3">{fmtCurrency(run.total_gross)}</td>
                  <td className="px-4 py-3 font-semibold text-teal-700">{fmtCurrency(run.total_net)}</td>
                  <td className="px-4 py-3">{statusBadge(run.status)}</td>
                  <td className="px-4 py-3 text-gray-500">{run.generated_by_name ?? "—"}</td>
                  <td className="px-4 py-3">
                    <RunActions run={run} issueMut={issueMut} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Run detail drawer */}
      {selectedRun && (
        <Modal
          open={!!selectedRun}
          onClose={() => setSelectedRun(null)}
          title={`Payroll Run #${selectedRun} — ${detail?.run ? `${fmtMonth(detail.run.month)} ${detail.run.year}` : "..."}`}
          maxW="max-w-5xl"
        >
          {detailLoading ? (
            <div className="text-center py-8 text-gray-400">Loading payslips...</div>
          ) : !detail?.payslips?.length ? (
            <div className="text-center py-8 text-gray-400">No payslips in this run</div>
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200 text-sm">
                <thead className="bg-gray-50">
                  <tr>
                    {["Staff", "Dept", "Present", "Gross", "Deductions", "Net", "Status", "PDF"].map((h) => (
                      <th key={h} className="px-3 py-2 text-left text-xs font-semibold text-gray-500 uppercase">{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100 bg-white">
                  {detail.payslips.map((p) => (
                    <tr key={p.id} className="hover:bg-gray-50">
                      <td className="px-3 py-2 font-medium">{p.staff_name ?? p.staff_uid?.slice(0, 8)}</td>
                      <td className="px-3 py-2 text-gray-500">{p.department ?? "—"}</td>
                      <td className="px-3 py-2">{p.days_present}/{p.total_working_days}</td>
                      <td className="px-3 py-2">{fmtCurrency(p.gross_salary)}</td>
                      <td className="px-3 py-2 text-red-600">{fmtCurrency(p.total_deductions)}</td>
                      <td className="px-3 py-2 font-bold text-teal-700">{fmtCurrency(p.net_salary)}</td>
                      <td className="px-3 py-2">{statusBadge(p.status)}</td>
                      <td className="px-3 py-2">
                        {p.pdf_key ? (
                          <span className="text-xs text-green-600 font-semibold">✓ PDF</span>
                        ) : (
                          <span className="text-xs text-gray-400">—</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Modal>
      )}

      {/* Run payroll modal */}
      <Modal open={showRunModal} onClose={() => setShowRunModal(false)} title="Run Payroll">
        <div className="space-y-4">
          <p className="text-sm text-gray-600">
            This will calculate payslips for all staff with salary config based on attendance and leave data.
          </p>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Month</label>
              <select
                value={runMonth}
                onChange={(e) => setRunMonth(Number(e.target.value))}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
              >
                {MONTHS.map((m, i) => (
                  <option key={i + 1} value={i + 1}>{m}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Year</label>
              <select
                value={runYear}
                onChange={(e) => setRunYear(Number(e.target.value))}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm"
              >
                {yearOptions.map((y) => (
                  <option key={y} value={y}>{y}</option>
                ))}
              </select>
            </div>
          </div>
          <button
            onClick={() => runMut.mutate({ month: runMonth, year: runYear })}
            disabled={runMut.isPending}
            className="w-full bg-teal-700 text-white py-2.5 rounded-lg font-semibold hover:bg-teal-800 disabled:opacity-50 transition-colors"
          >
            {runMut.isPending ? "Processing..." : `Run Payroll for ${fmtMonth(runMonth)} ${runYear}`}
          </button>
        </div>
      </Modal>
    </div>
  );
}
