#!/usr/bin/env node
// scripts/seed-dev-env.mjs
//
// Local-dev only. Writes apps/backend/.env and apps/admin/.env.local with
// fresh secrets if (and only if) they are missing. Idempotent: existing
// files are left untouched.
//
// Why this exists: 2026-04-29 e2e test discovered both env files had been
// removed from a working dev box, breaking the entire stack at boot. A
// fresh clone hits the same wall. This script unblocks `npm run dev` in
// one shot without anyone hand-rolling 5 base64 keys.
//
// Production secrets MUST come from the cluster (SealedSecrets / External
// Secrets — see docs/DEPLOYMENT_GUIDE.md#secrets). Do NOT use this for prod.

import { existsSync, writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';

if (process.env.NODE_ENV === 'production') {
  throw new Error('seed-dev-env.mjs refuses to write development secrets when NODE_ENV=production.');
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..');

const rand = () => crypto.randomBytes(32).toString('base64');
const apiKey = `devkey-${crypto.randomBytes(16).toString('hex')}`;
const jwtSecret = rand();
const fieldKey = rand();
const totpKey = rand();
const backupKey = rand();

const BACKEND_ENV_PATH = join(REPO_ROOT, 'apps', 'backend', '.env');
const ADMIN_ENV_PATH = join(REPO_ROOT, 'apps', 'admin', '.env.local');

function writeIfMissing(path, content, label) {
  if (existsSync(path)) {
    console.log(`✓ ${label} already exists at ${path}; leaving untouched.`);
    return false;
  }
  writeFileSync(path, content);
  console.log(`✓ wrote ${label} → ${path}`);
  return true;
}

const backendEnv = `# Local dev — auto-generated by scripts/seed-dev-env.mjs on ${new Date().toISOString()}
# DO NOT use these values in production. Rotate via SealedSecrets in the cluster.
API_KEY=${apiKey}
DATABASE_URL=postgresql://vhhealth@127.0.0.1:5433/vhhealth
JWT_SECRET=${jwtSecret}
ADMIN_BOOTSTRAP_PASSWORD=DevBootstrap!ab9097022423
ADMIN_BOOTSTRAP_USERNAME=admin
ADMIN_BOOTSTRAP_EMAIL=admin@vhhealth.com
ADMIN_BOOTSTRAP_NAME=Super Admin

FIELD_ENCRYPTION_KEY=${fieldKey}
TOTP_ENCRYPTION_KEY=${totpKey}
BACKUP_ENCRYPTION_KEY=${backupKey}

PORT=5000
NODE_ENV=development
ALLOWED_ORIGINS=http://localhost:3001,http://localhost:3000,http://127.0.0.1:3001

# Off in dev so the seeded SUPER_ADMIN can log in without TOTP enrolment.
REQUIRE_MFA_FOR_SUPER_ADMIN=false

LOG_FORMAT=text
ALERTS_ENABLED=false

CLINICAL_AI_PROVIDER=template
FIREBASE_AUTH_ENABLED=false
ABDM_ENABLED=false
`;

// Read the API_KEY back out of the backend .env if it already exists, so the
// admin proxy uses the same one. Otherwise use the freshly generated one.
function pairedApiKey() {
  if (!existsSync(BACKEND_ENV_PATH)) return apiKey;
  const text = readFileSync(BACKEND_ENV_PATH, 'utf-8');
  const m = text.match(/^API_KEY=(.+)$/m);
  return m ? m[1].trim() : apiKey;
}
function pairedJwt() {
  if (!existsSync(BACKEND_ENV_PATH)) return jwtSecret;
  const text = readFileSync(BACKEND_ENV_PATH, 'utf-8');
  const m = text.match(/^JWT_SECRET=(.+)$/m);
  return m ? m[1].trim() : jwtSecret;
}

const wroteBackend = writeIfMissing(BACKEND_ENV_PATH, backendEnv, 'apps/backend/.env');

const adminEnv = `# Local dev — auto-generated by scripts/seed-dev-env.mjs on ${new Date().toISOString()}
NEXT_PUBLIC_API_URL=http://127.0.0.1:5000
NEXT_PUBLIC_API_KEY=${pairedApiKey()}
BACKEND_API_KEY=${pairedApiKey()}
JWT_SECRET=${pairedJwt()}
NEXT_PUBLIC_ALLOWED_ORIGIN=http://localhost:3001
`;

const wroteAdmin = writeIfMissing(ADMIN_ENV_PATH, adminEnv, 'apps/admin/.env.local');

if (!wroteBackend && !wroteAdmin) {
  console.log('\nNothing to do — both env files already present.');
} else {
  console.log('\n→ Done. Start the backend with `npm --prefix apps/backend run dev`');
  console.log('→ Start the admin with `npm --prefix apps/admin run dev`');
}
