import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

import 'package:vhhealth/firebase_options.dart'; // generated by `flutterfire configure`

/// Initializes Firebase for every platform.
/// Call this once at app start-up (already done in `main.dart`).
class FirebaseConfig {
  static Future<void> initialize() async {
    try {
      if (Firebase.apps.isNotEmpty) return;

      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );

      if (!kReleaseMode) {
        debugPrint('✅ FirebaseCore initialized (OTP-only).');
      }
    } catch (e, st) {
      debugPrint('❌ Firebase initialization failed: $e');
      debugPrintStack(stackTrace: st);
      rethrow; // Optional: remove this line if you want to suppress the crash in production
    }
  }
}
