// GENERATED CODE - DO NOT EDIT.
// Source: apps/backend/src/config/patientNotificationTypeRegistry.js
// Regenerate: node scripts/generate-patient-notification-contract.mjs

// dart format off

enum PatientNotificationActionKind { navigate, acknowledgeOnly }

class PatientNotificationContract {
  const PatientNotificationContract({
    required this.type,
    required this.feedType,
    required this.writer,
    required this.persistence,
    required this.targetUri,
    required this.stableHydrationIds,
    required this.hydrationValidators,
    required this.authPolicy,
    required this.biometricPolicy,
    required this.priority,
    required this.deliveryReceipt,
    required this.acknowledgement,
    required this.expiry,
    required this.fallbackUri,
    required this.owner,
    required this.action,
    required this.extra,
    required this.preferenceKey,
    required this.inboxSupported,
    required this.lifecycle,
  });

  final String type;
  final String feedType;
  final String writer;
  final String persistence;
  final String targetUri;
  final List<String> stableHydrationIds;
  final Map<String, String> hydrationValidators;
  final String authPolicy;
  final String biometricPolicy;
  final String priority;
  final String deliveryReceipt;
  final String acknowledgement;
  final String expiry;
  final String fallbackUri;
  final String owner;
  final PatientNotificationActionKind action;
  final Map<String, Object?> extra;
  final String? preferenceKey;
  final bool inboxSupported;
  final String lifecycle;

  String resolveRoute(Map<String, dynamic> data) {
    var route = targetUri;
    for (final id in stableHydrationIds) {
      final value = data[id]?.toString().trim() ?? '';
      if (value.isEmpty) return fallbackUri;
      if (hydrationValidators[id] == 'positive_integer' &&
          !RegExp(r'^[1-9][0-9]*$').hasMatch(value)) {
        return fallbackUri;
      }
      route = route.replaceAll(':$id', Uri.encodeComponent(value));
    }
    return route;
  }
}

const String patientNotificationContractSourceSha256 = 'a790f742aec42d91cdc7ec038f34b0172758d95a3704558d62834211db8c8fa8';

const Map<String, PatientNotificationContract> patientNotificationContracts = {
  'appointment_reminder': PatientNotificationContract(
    type: 'appointment_reminder',
    feedType: 'appointment_reminder',
    writer: 'appointment reminder outbox and scheduled-notification sweep',
    persistence: 'required_feed_before_private_push',
    targetUri: '/appointments',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/appointments',
    owner: 'appointments',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: 'appointment_reminder',
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'appointment_confirmed': PatientNotificationContract(
    type: 'appointment_confirmed',
    feedType: 'appointment_confirmed',
    writer: 'appointment confirmation controller',
    persistence: 'required_feed_before_private_push',
    targetUri: '/appointments',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/appointments',
    owner: 'appointments',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'appointment_cancelled': PatientNotificationContract(
    type: 'appointment_cancelled',
    feedType: 'appointment_cancelled',
    writer: 'appointment cancellation controller',
    persistence: 'required_feed_before_private_push',
    targetUri: '/appointments',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/appointments',
    owner: 'appointments',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'appointment_rescheduled': PatientNotificationContract(
    type: 'appointment_rescheduled',
    feedType: 'appointment_rescheduled',
    writer: 'appointment reschedule controller',
    persistence: 'required_feed_before_private_push',
    targetUri: '/appointments',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/appointments',
    owner: 'appointments',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'appointment': PatientNotificationContract(
    type: 'appointment',
    feedType: 'appointment_reminder',
    writer: 'appointment reminder outbox and scheduled-notification sweep',
    persistence: 'transport_alias',
    targetUri: '/appointments',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/appointments',
    owner: 'appointments',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: 'appointment_reminder',
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'appointment_reminder_24h': PatientNotificationContract(
    type: 'appointment_reminder_24h',
    feedType: 'appointment_reminder',
    writer: 'appointment reminder outbox and scheduled-notification sweep',
    persistence: 'transport_alias',
    targetUri: '/appointments',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/appointments',
    owner: 'appointments',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: 'appointment_reminder',
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'appointment_reminder_1h': PatientNotificationContract(
    type: 'appointment_reminder_1h',
    feedType: 'appointment_reminder',
    writer: 'appointment reminder outbox and scheduled-notification sweep',
    persistence: 'transport_alias',
    targetUri: '/appointments',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/appointments',
    owner: 'appointments',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: 'appointment_reminder',
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'reminder': PatientNotificationContract(
    type: 'reminder',
    feedType: 'appointment_reminder',
    writer: 'appointment reminder outbox and scheduled-notification sweep',
    persistence: 'transport_alias',
    targetUri: '/appointments',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/appointments',
    owner: 'appointments',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: 'appointment_reminder',
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'investigation_result': PatientNotificationContract(
    type: 'investigation_result',
    feedType: 'investigation_result',
    writer: 'investigation report notification job and legacy order service',
    persistence: 'required_feed_before_private_push',
    targetUri: '/investigations',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/investigations',
    owner: 'investigations',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'investigation_result_ready': PatientNotificationContract(
    type: 'investigation_result_ready',
    feedType: 'investigation_result_ready',
    writer: 'investigation result service',
    persistence: 'required_feed_before_private_push',
    targetUri: '/investigations',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/investigations',
    owner: 'investigations',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: 'results_ready',
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'investigation_confirmed': PatientNotificationContract(
    type: 'investigation_confirmed',
    feedType: 'investigation_confirmed',
    writer: 'investigation booking controller',
    persistence: 'required_feed_before_private_push',
    targetUri: '/investigations',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/investigations',
    owner: 'investigations',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'investigation_booking': PatientNotificationContract(
    type: 'investigation_booking',
    feedType: 'investigation_booking',
    writer: 'investigation order and booking controllers',
    persistence: 'required_feed_before_private_push',
    targetUri: '/investigations',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/investigations',
    owner: 'investigations',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'collector_dispatched': PatientNotificationContract(
    type: 'collector_dispatched',
    feedType: 'collector_dispatched',
    writer: 'investigation booking controller',
    persistence: 'required_feed_before_private_push',
    targetUri: '/investigations',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/investigations',
    owner: 'investigations',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'investigation': PatientNotificationContract(
    type: 'investigation',
    feedType: 'investigation_result',
    writer: 'investigation report notification job and legacy order service',
    persistence: 'transport_alias',
    targetUri: '/investigations',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/investigations',
    owner: 'investigations',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'lab_result_ready': PatientNotificationContract(
    type: 'lab_result_ready',
    feedType: 'lab_result_ready',
    writer: 'lab result release service',
    persistence: 'required_feed_before_private_push',
    targetUri: '/portal/lab-results',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/lab-results',
    owner: 'laboratory',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: 'results_ready',
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'lab_result_corrected': PatientNotificationContract(
    type: 'lab_result_corrected',
    feedType: 'lab_result_corrected',
    writer: 'lab result correction service',
    persistence: 'required_feed_before_private_push',
    targetUri: '/portal/lab-results',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/lab-results',
    owner: 'laboratory',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: 'results_ready',
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'result_ready': PatientNotificationContract(
    type: 'result_ready',
    feedType: 'lab_result_ready',
    writer: 'lab result release service',
    persistence: 'transport_alias',
    targetUri: '/portal/lab-results',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/lab-results',
    owner: 'laboratory',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: 'results_ready',
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'results_ready': PatientNotificationContract(
    type: 'results_ready',
    feedType: 'lab_result_ready',
    writer: 'lab result release service',
    persistence: 'transport_alias',
    targetUri: '/portal/lab-results',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/lab-results',
    owner: 'laboratory',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: 'results_ready',
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'diagnostic_result_ready': PatientNotificationContract(
    type: 'diagnostic_result_ready',
    feedType: 'diagnostic_result_ready',
    writer: 'structured diagnostic patient notification sweep',
    persistence: 'transactional_feed_and_outbox',
    targetUri: '/portal/diagnostic-results',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/diagnostic-results',
    owner: 'diagnostics',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: 'results_ready',
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'patient_message': PatientNotificationContract(
    type: 'patient_message',
    feedType: 'patient_message',
    writer: 'patient portal secure messaging service',
    persistence: 'required_feed_before_private_push',
    targetUri: '/portal/messages/:thread_id',
    stableHydrationIds: <String>['thread_id'],
    hydrationValidators: <String, String>{'thread_id': 'positive_integer'},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/messages',
    owner: 'secure_messaging',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'secure_message': PatientNotificationContract(
    type: 'secure_message',
    feedType: 'patient_message',
    writer: 'patient portal secure messaging service',
    persistence: 'transport_alias',
    targetUri: '/portal/messages/:thread_id',
    stableHydrationIds: <String>['thread_id'],
    hydrationValidators: <String, String>{'thread_id': 'positive_integer'},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/messages',
    owner: 'secure_messaging',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'message': PatientNotificationContract(
    type: 'message',
    feedType: 'patient_message',
    writer: 'patient portal secure messaging service',
    persistence: 'transport_alias',
    targetUri: '/portal/messages/:thread_id',
    stableHydrationIds: <String>['thread_id'],
    hydrationValidators: <String, String>{'thread_id': 'positive_integer'},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/messages',
    owner: 'secure_messaging',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'portal_message': PatientNotificationContract(
    type: 'portal_message',
    feedType: 'patient_message',
    writer: 'patient portal secure messaging service',
    persistence: 'transport_alias',
    targetUri: '/portal/messages/:thread_id',
    stableHydrationIds: <String>['thread_id'],
    hydrationValidators: <String, String>{'thread_id': 'positive_integer'},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/messages',
    owner: 'secure_messaging',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'referral_response_ready': PatientNotificationContract(
    type: 'referral_response_ready',
    feedType: 'referral_response_ready',
    writer: 'referral closed-loop response transaction',
    persistence: 'transactional_feed_and_outbox',
    targetUri: '/portal/referrals',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/referrals',
    owner: 'referrals',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'referral_update': PatientNotificationContract(
    type: 'referral_update',
    feedType: 'referral_update',
    writer: 'referral workflow notification writer',
    persistence: 'required_feed_before_private_push',
    targetUri: '/portal/referrals',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/referrals',
    owner: 'referrals',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'pharmacy_order': PatientNotificationContract(
    type: 'pharmacy_order',
    feedType: 'pharmacy_order',
    writer: 'pharmacy order workflow',
    persistence: 'required_feed_before_private_push',
    targetUri: '/pharmacy',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/pharmacy',
    owner: 'pharmacy',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'pharmacy_confirmed': PatientNotificationContract(
    type: 'pharmacy_confirmed',
    feedType: 'pharmacy_confirmed',
    writer: 'pharmacy order workflow',
    persistence: 'required_feed_before_private_push',
    targetUri: '/pharmacy',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/pharmacy',
    owner: 'pharmacy',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'pharmacy_dispatched': PatientNotificationContract(
    type: 'pharmacy_dispatched',
    feedType: 'pharmacy_dispatched',
    writer: 'pharmacy order workflow',
    persistence: 'required_feed_before_private_push',
    targetUri: '/pharmacy',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/pharmacy',
    owner: 'pharmacy',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'pharmacy_delivered': PatientNotificationContract(
    type: 'pharmacy_delivered',
    feedType: 'pharmacy_delivered',
    writer: 'pharmacy order workflow',
    persistence: 'required_feed_before_private_push',
    targetUri: '/pharmacy',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/pharmacy',
    owner: 'pharmacy',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'pharmacy_order_update': PatientNotificationContract(
    type: 'pharmacy_order_update',
    feedType: 'pharmacy_order',
    writer: 'pharmacy order workflow',
    persistence: 'transport_alias',
    targetUri: '/pharmacy',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/pharmacy',
    owner: 'pharmacy',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'order_dispatched': PatientNotificationContract(
    type: 'order_dispatched',
    feedType: 'pharmacy_dispatched',
    writer: 'pharmacy order workflow',
    persistence: 'transport_alias',
    targetUri: '/pharmacy',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/pharmacy',
    owner: 'pharmacy',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'order_delivered': PatientNotificationContract(
    type: 'order_delivered',
    feedType: 'pharmacy_delivered',
    writer: 'pharmacy order workflow',
    persistence: 'transport_alias',
    targetUri: '/pharmacy',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/pharmacy',
    owner: 'pharmacy',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'document_uploaded': PatientNotificationContract(
    type: 'document_uploaded',
    feedType: 'document_uploaded',
    writer: 'electronic prescription document workflow',
    persistence: 'dispatcher_inapp',
    targetUri: '/health',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/health',
    owner: 'patient_records',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{'tab': 1},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'prescription': PatientNotificationContract(
    type: 'prescription',
    feedType: 'document_uploaded',
    writer: 'electronic prescription document workflow',
    persistence: 'transport_alias',
    targetUri: '/health',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/health',
    owner: 'patient_records',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{'tab': 1},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'prescription_ready': PatientNotificationContract(
    type: 'prescription_ready',
    feedType: 'document_uploaded',
    writer: 'electronic prescription document workflow',
    persistence: 'transport_alias',
    targetUri: '/health',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/health',
    owner: 'patient_records',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{'tab': 1},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'feedback_request': PatientNotificationContract(
    type: 'feedback_request',
    feedType: 'feedback_request',
    writer: 'scheduled notification sweep',
    persistence: 'required_feed_before_private_push',
    targetUri: '/ask-a-doubt',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/ask-a-doubt',
    owner: 'patient_feedback',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'engagement_campaign': PatientNotificationContract(
    type: 'engagement_campaign',
    feedType: 'engagement_campaign',
    writer: 'engagement campaign outbox',
    persistence: 'transactional_feed_and_outbox',
    targetUri: '/notifications',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'feed_commit_and_provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/notifications',
    owner: 'patient_engagement',
    action: PatientNotificationActionKind.acknowledgeOnly,
    extra: <String, Object?>{},
    preferenceKey: 'engagement_campaign',
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'billing': PatientNotificationContract(
    type: 'billing',
    feedType: 'billing',
    writer: 'legacy billing push transport',
    persistence: 'provider_only',
    targetUri: '/portal/bills',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/bills',
    owner: 'billing',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'bill_ready': PatientNotificationContract(
    type: 'bill_ready',
    feedType: 'billing',
    writer: 'legacy billing push transport',
    persistence: 'transport_alias',
    targetUri: '/portal/bills',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/bills',
    owner: 'billing',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'payment_link': PatientNotificationContract(
    type: 'payment_link',
    feedType: 'billing',
    writer: 'legacy billing push transport',
    persistence: 'transport_alias',
    targetUri: '/portal/bills',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/portal/bills',
    owner: 'billing',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'sos': PatientNotificationContract(
    type: 'sos',
    feedType: 'sos',
    writer: 'patient safety push transport',
    persistence: 'provider_only',
    targetUri: '/home',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/home',
    owner: 'patient_safety',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'sos_alert': PatientNotificationContract(
    type: 'sos_alert',
    feedType: 'sos',
    writer: 'patient safety push transport',
    persistence: 'transport_alias',
    targetUri: '/home',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/home',
    owner: 'patient_safety',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'feedback': PatientNotificationContract(
    type: 'feedback',
    feedType: 'feedback',
    writer: 'feedback response push transport',
    persistence: 'provider_only',
    targetUri: '/feedback-history',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/feedback-history',
    owner: 'patient_feedback',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'feedback_reply': PatientNotificationContract(
    type: 'feedback_reply',
    feedType: 'feedback',
    writer: 'feedback response push transport',
    persistence: 'transport_alias',
    targetUri: '/feedback-history',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/feedback-history',
    owner: 'patient_feedback',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'step_reward': PatientNotificationContract(
    type: 'step_reward',
    feedType: 'step_reward',
    writer: 'wellness reward push transport',
    persistence: 'provider_only',
    targetUri: '/steps',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/steps',
    owner: 'wellness',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
  'step_badge': PatientNotificationContract(
    type: 'step_badge',
    feedType: 'step_reward',
    writer: 'wellness reward push transport',
    persistence: 'transport_alias',
    targetUri: '/steps',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'provider_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/steps',
    owner: 'wellness',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: false,
    lifecycle: 'legacy_alias',
  ),
  'medication_reminder': PatientNotificationContract(
    type: 'medication_reminder',
    feedType: 'medication_reminder',
    writer: 'patient device notification scheduler',
    persistence: 'local_notification',
    targetUri: '/reminders',
    stableHydrationIds: <String>[],
    hydrationValidators: <String, String>{},
    authPolicy: 'current_patient_session',
    biometricPolicy: 'notification_inbox_gate',
    priority: 'NORMAL',
    deliveryReceipt: 'device_scheduler_receipt',
    acknowledgement: 'mark_read',
    expiry: 'source_authoritative',
    fallbackUri: '/reminders',
    owner: 'medication_adherence',
    action: PatientNotificationActionKind.navigate,
    extra: <String, Object?>{},
    preferenceKey: null,
    inboxSupported: true,
    lifecycle: 'active',
  ),
};

PatientNotificationContract? patientNotificationContractFor(Object? rawType) {
  final type = rawType?.toString().trim().toLowerCase() ?? '';
  return patientNotificationContracts[type];
}

// dart format on
