// src/services/emr/icd10SeedData.js
// Top 200 most common hospital ICD-10 codes

export const ICD10_SEED_DATA = [
  // --- Endocrine / Metabolic ---
  { code: 'E11.9', description: 'Type 2 diabetes mellitus without complications', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E11.65', description: 'Type 2 diabetes mellitus with hyperglycemia', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E11.22', description: 'Type 2 diabetes mellitus with diabetic chronic kidney disease', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E11.40', description: 'Type 2 diabetes mellitus with diabetic neuropathy, unspecified', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E11.51', description: 'Type 2 diabetes mellitus with diabetic peripheral angiopathy without gangrene', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E10.9', description: 'Type 1 diabetes mellitus without complications', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E10.65', description: 'Type 1 diabetes mellitus with hyperglycemia', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E78.5', description: 'Dyslipidemia, unspecified', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E78.0', description: 'Pure hypercholesterolemia, unspecified', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E03.9', description: 'Hypothyroidism, unspecified', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E05.90', description: 'Thyrotoxicosis, unspecified without thyrotoxic crisis or storm', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E87.1', description: 'Hypo-osmolality and hyponatremia', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E87.6', description: 'Hypokalemia', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E87.5', description: 'Hyperkalemia', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E86.0', description: 'Dehydration', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E66.01', description: 'Morbid (severe) obesity due to excess calories', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E44.1', description: 'Mild protein-calorie malnutrition', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'E55.9', description: 'Vitamin D deficiency, unspecified', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },

  // --- Circulatory System ---
  { code: 'I10', description: 'Essential (primary) hypertension', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I11.9', description: 'Hypertensive heart disease without heart failure', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I12.9', description: 'Hypertensive chronic kidney disease with stage 1–4 or unspecified CKD', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I13.10', description: 'Hypertensive heart and chronic kidney disease without heart failure, with CKD stage 1–4', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I25.10', description: 'Atherosclerotic heart disease of native coronary artery without angina pectoris', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I21.9', description: 'Acute myocardial infarction, unspecified', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I21.01', description: 'ST elevation (STEMI) myocardial infarction involving left main coronary artery', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I21.3', description: 'ST elevation (STEMI) myocardial infarction of unspecified site', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I21.4', description: 'Non-ST elevation (NSTEMI) myocardial infarction', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I20.0', description: 'Unstable angina', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I48.91', description: 'Unspecified atrial fibrillation', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I48.0', description: 'Paroxysmal atrial fibrillation', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I48.1', description: 'Persistent atrial fibrillation', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I50.9', description: 'Heart failure, unspecified', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I50.22', description: 'Chronic systolic (congestive) heart failure', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I50.32', description: 'Chronic diastolic (congestive) heart failure', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I50.42', description: 'Chronic combined systolic and diastolic (congestive) heart failure', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I63.9', description: 'Cerebral infarction, unspecified', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I63.50', description: 'Cerebral infarction due to unspecified occlusion or stenosis of unspecified cerebral artery', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I61.9', description: 'Nontraumatic intracerebral hemorrhage, unspecified', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I26.99', description: 'Other pulmonary embolism without acute cor pulmonale', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I26.02', description: 'Saddle embolus of pulmonary artery with acute cor pulmonale', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I82.401', description: 'Acute embolism and thrombosis of unspecified deep veins of right lower extremity', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I73.9', description: 'Peripheral vascular disease, unspecified', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I42.9', description: 'Cardiomyopathy, unspecified', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I44.1', description: 'Atrioventricular block, second degree', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I47.2', description: 'Ventricular tachycardia', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I71.4', description: 'Abdominal aortic aneurysm, without rupture', category: 'Diseases of the circulatory system', chapter: 'IX' },

  // --- Respiratory System ---
  { code: 'J18.9', description: 'Pneumonia, unspecified organism', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J18.1', description: 'Lobar pneumonia, unspecified organism', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J15.9', description: 'Unspecified bacterial pneumonia', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J13', description: 'Pneumonia due to Streptococcus pneumoniae', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J44.1', description: 'Chronic obstructive pulmonary disease with (acute) exacerbation', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J44.0', description: 'Chronic obstructive pulmonary disease with (acute) lower respiratory infection', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J45.41', description: 'Moderate persistent asthma with (acute) exacerbation', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J45.51', description: 'Severe persistent asthma with (acute) exacerbation', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J96.01', description: 'Acute respiratory failure with hypoxia', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J96.02', description: 'Acute respiratory failure with hypercapnia', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J96.11', description: 'Chronic respiratory failure with hypoxia', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J80', description: 'Acute respiratory distress syndrome', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J90', description: 'Pleural effusion, not elsewhere classified', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J93.0', description: 'Spontaneous tension pneumothorax', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J06.9', description: 'Acute upper respiratory infection, unspecified', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J22', description: 'Unspecified acute lower respiratory infection', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J84.10', description: 'Pulmonary fibrosis, unspecified', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'J69.0', description: 'Pneumonitis due to inhalation of food and vomit', category: 'Diseases of the respiratory system', chapter: 'X' },

  // --- Digestive System ---
  { code: 'K21.0', description: 'Gastro-esophageal reflux disease with esophagitis', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K25.9', description: 'Gastric ulcer, unspecified, without hemorrhage or perforation', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K26.9', description: 'Duodenal ulcer, unspecified, without hemorrhage or perforation', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K35.80', description: 'Unspecified acute appendicitis', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K40.90', description: 'Unilateral inguinal hernia, without obstruction or gangrene, not specified as recurrent', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K56.60', description: 'Unspecified intestinal obstruction', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K57.30', description: 'Diverticulosis of large intestine without perforation or abscess without bleeding', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K57.32', description: 'Diverticulitis of large intestine without perforation or abscess without bleeding', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K70.30', description: 'Alcoholic cirrhosis of liver without ascites', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K74.60', description: 'Unspecified cirrhosis of liver', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K72.00', description: 'Acute and subacute hepatic failure without coma', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K80.20', description: 'Calculus of gallbladder without cholecystitis, without obstruction', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K80.00', description: 'Calculus of gallbladder with acute cholecystitis without obstruction', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K85.90', description: 'Acute pancreatitis without necrosis or infection, unspecified', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K92.2', description: 'Gastrointestinal hemorrhage, unspecified', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'K92.0', description: 'Hematemesis', category: 'Diseases of the digestive system', chapter: 'XI' },

  // --- Genitourinary System ---
  { code: 'N18.3', description: 'Chronic kidney disease, stage 3 (moderate)', category: 'Diseases of the genitourinary system', chapter: 'XIV' },
  { code: 'N18.4', description: 'Chronic kidney disease, stage 4 (severe)', category: 'Diseases of the genitourinary system', chapter: 'XIV' },
  { code: 'N18.5', description: 'Chronic kidney disease, stage 5', category: 'Diseases of the genitourinary system', chapter: 'XIV' },
  { code: 'N18.6', description: 'End stage renal disease', category: 'Diseases of the genitourinary system', chapter: 'XIV' },
  { code: 'N17.9', description: 'Acute kidney failure, unspecified', category: 'Diseases of the genitourinary system', chapter: 'XIV' },
  { code: 'N39.0', description: 'Urinary tract infection, site not specified', category: 'Diseases of the genitourinary system', chapter: 'XIV' },
  { code: 'N13.30', description: 'Unspecified hydronephrosis', category: 'Diseases of the genitourinary system', chapter: 'XIV' },
  { code: 'N20.0', description: 'Calculus of kidney', category: 'Diseases of the genitourinary system', chapter: 'XIV' },
  { code: 'N40.1', description: 'Benign prostatic hyperplasia with lower urinary tract symptoms', category: 'Diseases of the genitourinary system', chapter: 'XIV' },

  // --- Infectious Diseases ---
  { code: 'A41.9', description: 'Sepsis, unspecified organism', category: 'Certain infectious and parasitic diseases', chapter: 'I' },
  { code: 'A41.01', description: 'Sepsis due to Methicillin susceptible Staphylococcus aureus', category: 'Certain infectious and parasitic diseases', chapter: 'I' },
  { code: 'A41.02', description: 'Sepsis due to Methicillin resistant Staphylococcus aureus', category: 'Certain infectious and parasitic diseases', chapter: 'I' },
  { code: 'A41.51', description: 'Sepsis due to Escherichia coli', category: 'Certain infectious and parasitic diseases', chapter: 'I' },
  { code: 'A04.72', description: 'Clostridioides difficile enterocolitis, recurrent', category: 'Certain infectious and parasitic diseases', chapter: 'I' },
  { code: 'A49.9', description: 'Bacterial infection, unspecified', category: 'Certain infectious and parasitic diseases', chapter: 'I' },
  { code: 'B34.9', description: 'Viral infection, unspecified', category: 'Certain infectious and parasitic diseases', chapter: 'I' },
  { code: 'B37.0', description: 'Candidal stomatitis', category: 'Certain infectious and parasitic diseases', chapter: 'I' },

  // --- Blood and Blood-Forming Organs ---
  { code: 'D64.9', description: 'Anemia, unspecified', category: 'Diseases of blood and blood-forming organs', chapter: 'III' },
  { code: 'D50.9', description: 'Iron deficiency anemia, unspecified', category: 'Diseases of blood and blood-forming organs', chapter: 'III' },
  { code: 'D62', description: 'Acute posthemorrhagic anemia', category: 'Diseases of blood and blood-forming organs', chapter: 'III' },
  { code: 'D69.6', description: 'Thrombocytopenia, unspecified', category: 'Diseases of blood and blood-forming organs', chapter: 'III' },
  { code: 'D68.9', description: 'Coagulation defect, unspecified', category: 'Diseases of blood and blood-forming organs', chapter: 'III' },
  { code: 'D65', description: 'Disseminated intravascular coagulation', category: 'Diseases of blood and blood-forming organs', chapter: 'III' },

  // --- Mental and Behavioral Disorders ---
  { code: 'F10.239', description: 'Alcohol dependence with withdrawal, unspecified', category: 'Mental and behavioral disorders', chapter: 'V' },
  { code: 'F10.20', description: 'Alcohol dependence, uncomplicated', category: 'Mental and behavioral disorders', chapter: 'V' },
  { code: 'F32.9', description: 'Major depressive disorder, single episode, unspecified', category: 'Mental and behavioral disorders', chapter: 'V' },
  { code: 'F41.1', description: 'Generalized anxiety disorder', category: 'Mental and behavioral disorders', chapter: 'V' },
  { code: 'F05', description: 'Delirium due to known physiological condition', category: 'Mental and behavioral disorders', chapter: 'V' },
  { code: 'F17.210', description: 'Nicotine dependence, cigarettes, uncomplicated', category: 'Mental and behavioral disorders', chapter: 'V' },

  // --- Neoplasms ---
  { code: 'C34.90', description: 'Malignant neoplasm of unspecified part of unspecified bronchus or lung', category: 'Neoplasms', chapter: 'II' },
  { code: 'C50.919', description: 'Malignant neoplasm of unspecified site of unspecified female breast', category: 'Neoplasms', chapter: 'II' },
  { code: 'C61', description: 'Malignant neoplasm of prostate', category: 'Neoplasms', chapter: 'II' },
  { code: 'C18.9', description: 'Malignant neoplasm of colon, unspecified', category: 'Neoplasms', chapter: 'II' },
  { code: 'C78.7', description: 'Secondary malignant neoplasm of liver and intrahepatic bile duct', category: 'Neoplasms', chapter: 'II' },
  { code: 'C79.51', description: 'Secondary malignant neoplasm of bone', category: 'Neoplasms', chapter: 'II' },
  { code: 'C25.9', description: 'Malignant neoplasm of pancreas, unspecified', category: 'Neoplasms', chapter: 'II' },
  { code: 'C22.0', description: 'Liver cell carcinoma', category: 'Neoplasms', chapter: 'II' },
  { code: 'C64.9', description: 'Malignant neoplasm of unspecified kidney, except renal pelvis', category: 'Neoplasms', chapter: 'II' },
  { code: 'C67.9', description: 'Malignant neoplasm of bladder, unspecified', category: 'Neoplasms', chapter: 'II' },

  // --- Musculoskeletal / Fractures ---
  { code: 'M54.5', description: 'Low back pain', category: 'Diseases of the musculoskeletal system', chapter: 'XIII' },
  { code: 'M79.3', description: 'Panniculitis, unspecified', category: 'Diseases of the musculoskeletal system', chapter: 'XIII' },
  { code: 'M81.0', description: 'Age-related osteoporosis without current pathological fracture', category: 'Diseases of the musculoskeletal system', chapter: 'XIII' },
  { code: 'M17.11', description: 'Primary osteoarthritis, right knee', category: 'Diseases of the musculoskeletal system', chapter: 'XIII' },
  { code: 'M16.11', description: 'Primary osteoarthritis, right hip', category: 'Diseases of the musculoskeletal system', chapter: 'XIII' },
  { code: 'M06.9', description: 'Rheumatoid arthritis, unspecified', category: 'Diseases of the musculoskeletal system', chapter: 'XIII' },
  { code: 'S72.001A', description: 'Fracture of unspecified part of neck of right femur, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'S72.009A', description: 'Fracture of unspecified part of neck of unspecified femur, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'S82.001A', description: 'Unspecified fracture of right patella, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'S42.001A', description: 'Fracture of unspecified part of right clavicle, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'S52.501A', description: 'Unspecified fracture of the lower end of right radius, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'S32.000A', description: 'Wedge compression fracture of unspecified lumbar vertebra, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'S22.000A', description: 'Wedge compression fracture of unspecified thoracic vertebra, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'S06.0X0A', description: 'Concussion without loss of consciousness, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },

  // --- Nervous System ---
  { code: 'G40.909', description: 'Epilepsy, unspecified, not intractable, without status epilepticus', category: 'Diseases of the nervous system', chapter: 'VI' },
  { code: 'G41.0', description: 'Grand mal status epilepticus', category: 'Diseases of the nervous system', chapter: 'VI' },
  { code: 'G20', description: 'Parkinson disease', category: 'Diseases of the nervous system', chapter: 'VI' },
  { code: 'G30.9', description: 'Alzheimer disease, unspecified', category: 'Diseases of the nervous system', chapter: 'VI' },
  { code: 'G43.909', description: 'Migraine, unspecified, not intractable, without status migrainosus', category: 'Diseases of the nervous system', chapter: 'VI' },
  { code: 'G89.4', description: 'Chronic pain syndrome', category: 'Diseases of the nervous system', chapter: 'VI' },
  { code: 'G62.9', description: 'Polyneuropathy, unspecified', category: 'Diseases of the nervous system', chapter: 'VI' },

  // --- Symptoms, Signs, Abnormal Findings ---
  { code: 'R06.02', description: 'Shortness of breath', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R07.9', description: 'Chest pain, unspecified', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R00.0', description: 'Tachycardia, unspecified', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R55', description: 'Syncope and collapse', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R11.2', description: 'Nausea with vomiting, unspecified', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R50.9', description: 'Fever, unspecified', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R41.0', description: 'Disorientation, unspecified', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R10.9', description: 'Unspecified abdominal pain', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R10.0', description: 'Acute abdomen', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R40.20', description: 'Unspecified coma', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R57.0', description: 'Cardiogenic shock', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R57.1', description: 'Hypovolemic shock', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R65.20', description: 'Severe sepsis without septic shock', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R65.21', description: 'Severe sepsis with septic shock', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R13.10', description: 'Dysphagia, unspecified', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R31.9', description: 'Hematuria, unspecified', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R04.0', description: 'Epistaxis', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R04.2', description: 'Hemoptysis', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'R42', description: 'Dizziness and giddiness', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },

  // --- Injury / External Causes ---
  { code: 'T78.2XXA', description: 'Anaphylactic shock, unspecified, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'T81.4XXA', description: 'Infection following a procedure, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'T85.71XA', description: 'Infection and inflammatory reaction due to peritoneal dialysis catheter, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'T80.211A', description: 'Bloodstream infection due to central venous catheter, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'T50.901A', description: 'Poisoning by unspecified drugs, medicaments and biological substances, accidental, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'T39.1X1A', description: 'Poisoning by 4-Aminophenol derivatives, accidental, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'W19.XXXA', description: 'Unspecified fall, initial encounter', category: 'External causes of morbidity', chapter: 'XX' },

  // --- Skin / Subcutaneous ---
  { code: 'L89.90', description: 'Pressure ulcer of unspecified site, unspecified stage', category: 'Diseases of the skin', chapter: 'XII' },
  { code: 'L89.150', description: 'Pressure ulcer of sacral region, unstageable', category: 'Diseases of the skin', chapter: 'XII' },
  { code: 'L03.90', description: 'Cellulitis, unspecified', category: 'Diseases of the skin', chapter: 'XII' },
  { code: 'L97.909', description: 'Non-pressure chronic ulcer of unspecified part of unspecified lower leg', category: 'Diseases of the skin', chapter: 'XII' },

  // --- Pregnancy / Obstetric ---
  { code: 'O80', description: 'Encounter for full-term uncomplicated delivery', category: 'Pregnancy, childbirth and the puerperium', chapter: 'XV' },
  { code: 'O82', description: 'Encounter for cesarean delivery without indication', category: 'Pregnancy, childbirth and the puerperium', chapter: 'XV' },
  { code: 'O24.419', description: 'Gestational diabetes mellitus in pregnancy, unspecified control', category: 'Pregnancy, childbirth and the puerperium', chapter: 'XV' },
  { code: 'O14.10', description: 'Severe pre-eclampsia, unspecified trimester', category: 'Pregnancy, childbirth and the puerperium', chapter: 'XV' },
  { code: 'O72.1', description: 'Other immediate postpartum hemorrhage', category: 'Pregnancy, childbirth and the puerperium', chapter: 'XV' },
  { code: 'O42.90', description: 'Premature rupture of membranes, unspecified, unspecified weeks of gestation', category: 'Pregnancy, childbirth and the puerperium', chapter: 'XV' },

  // --- Perinatal / Neonatal ---
  { code: 'P07.30', description: 'Preterm newborn, unspecified weeks of gestation', category: 'Conditions originating in the perinatal period', chapter: 'XVI' },
  { code: 'P59.9', description: 'Neonatal jaundice, unspecified', category: 'Conditions originating in the perinatal period', chapter: 'XVI' },
  { code: 'P22.0', description: 'Respiratory distress syndrome of newborn', category: 'Conditions originating in the perinatal period', chapter: 'XVI' },
  { code: 'P36.9', description: 'Bacterial sepsis of newborn, unspecified', category: 'Conditions originating in the perinatal period', chapter: 'XVI' },

  // --- Factors Influencing Health Status (Z codes) ---
  { code: 'Z87.891', description: 'Personal history of nicotine dependence', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z79.4', description: 'Long term (current) use of insulin', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z79.01', description: 'Long term (current) use of anticoagulants', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z79.899', description: 'Other long term (current) drug therapy', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z95.1', description: 'Presence of aortocoronary bypass graft', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z96.641', description: 'Presence of right artificial hip joint', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z96.651', description: 'Presence of right artificial knee joint', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z68.41', description: 'Body mass index (BMI) 40.0-44.9, adult', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z51.11', description: 'Encounter for antineoplastic chemotherapy', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z51.0', description: 'Encounter for antineoplastic radiation therapy', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z99.11', description: 'Dependence on respiratory ventilator status', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z99.2', description: 'Dependence on renal dialysis', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z23', description: 'Encounter for immunization', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z48.812', description: 'Encounter for surgical aftercare following surgery on the circulatory system', category: 'Factors influencing health status', chapter: 'XXI' },

  // --- Procedures / Encounters ---
  { code: 'Z53.09', description: 'Procedure and treatment not carried out because of other contraindication', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'Z87.39', description: 'Personal history of other diseases of the musculoskeletal system and connective tissue', category: 'Factors influencing health status', chapter: 'XXI' },

  // --- Eye / Ear ---
  { code: 'H40.9', description: 'Unspecified glaucoma', category: 'Diseases of the eye', chapter: 'VII' },
  { code: 'H26.9', description: 'Unspecified cataract', category: 'Diseases of the eye', chapter: 'VII' },

  // --- Additional common hospital codes ---
  { code: 'J95.851', description: 'Ventilator associated pneumonia', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'T82.7XXA', description: 'Infection and inflammatory reaction due to other cardiac and vascular devices, implants and grafts, initial encounter', category: 'Injury, poisoning', chapter: 'XIX' },
  { code: 'G93.1', description: 'Anoxic brain damage, not elsewhere classified', category: 'Diseases of the nervous system', chapter: 'VI' },
  { code: 'I46.9', description: 'Cardiac arrest, cause unspecified', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'J95.04', description: 'Mendelson syndrome', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'K59.00', description: 'Constipation, unspecified', category: 'Diseases of the digestive system', chapter: 'XI' },
  { code: 'R33.9', description: 'Retention of urine, unspecified', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'M62.82', description: 'Rhabdomyolysis', category: 'Diseases of the musculoskeletal system', chapter: 'XIII' },
  { code: 'E16.2', description: 'Hypoglycemia, unspecified', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'G45.9', description: 'Transient cerebral ischemic attack, unspecified', category: 'Diseases of the nervous system', chapter: 'VI' },
  { code: 'I95.1', description: 'Orthostatic hypotension', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'N10', description: 'Acute pyelonephritis', category: 'Diseases of the genitourinary system', chapter: 'XIV' },
  { code: 'R29.6', description: 'Repeated falls', category: 'Symptoms, signs and abnormal findings', chapter: 'XVIII' },
  { code: 'Z66', description: 'Do not resuscitate', category: 'Factors influencing health status', chapter: 'XXI' },
  { code: 'I25.2', description: 'Old myocardial infarction', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I35.0', description: 'Nonrheumatic aortic (valve) stenosis', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'I34.0', description: 'Nonrheumatic mitral (valve) insufficiency', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'N18.9', description: 'Chronic kidney disease, unspecified', category: 'Diseases of the genitourinary system', chapter: 'XIV' },
  { code: 'J98.11', description: 'Atelectasis', category: 'Diseases of the respiratory system', chapter: 'X' },
  { code: 'E83.42', description: 'Hypomagnesemia', category: 'Endocrine, nutritional and metabolic diseases', chapter: 'IV' },
  { code: 'D63.1', description: 'Anemia in chronic kidney disease', category: 'Diseases of blood and blood-forming organs', chapter: 'III' },
  { code: 'I97.710', description: 'Intraoperative cardiac arrest during cardiac surgery', category: 'Diseases of the circulatory system', chapter: 'IX' },
  { code: 'Z86.73', description: 'Personal history of transient ischemic attack (TIA), and cerebral infarction without residual deficits', category: 'Factors influencing health status', chapter: 'XXI' },
];
