---
- name: Restart rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
  listen: restart rke2-agent

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd
