name: Admin Portal CI

on:
  workflow_dispatch:

concurrency:
  group: ci-admin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-typecheck-build:
    uses: ./.github/workflows/_reusable-admin-ci.yml
    with:
      notify_on_failure: true
      notification_label: Admin Portal CI
    secrets: inherit
