name: Kubernetes Manifests

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: kubernetes-manifests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: ./.github/workflows/_reusable-kubernetes-manifests.yml
    secrets: inherit
